### ISSUE TITLE
我用官方提供的代码部署会报错RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by Admiraljj** [QwenLM/Qwen2#102]
这是我的代码：
`from modelscope import AutoModelForCausalLM, AutoTokenizer
device = "cuda" # the device to load the model onto

model = AutoModelForCausalLM.from_pretrained(
    "qwen/Qwen1.5-7B-Chat-GPTQ-Int8",
    torch_dtype="auto",
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained("qwen/Qwen1.5-7B-Chat-GPTQ-Int8")

prompt = "Give me a short introduction to large language model."
messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(device)

generated_ids = model.generate(
    model_inputs.input_ids,
    max_new_tokens=512
)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]`

这是报错：
`2024-02-28 19:10:06,039 - modelscope - INFO - PyTorch version 2.2.1 Found.
2024-02-28 19:10:06,039 - modelscope - INFO - Loading ast index from /home/asus/.cache/modelscope/ast_indexer
2024-02-28 19:10:06,055 - modelscope - INFO - Loading done! Current index file version is 1.12.0, with md5 e82ec0d08d5c4604494d74c4eaab14dd and a total number of 964 components indexed
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.04it/s]
2024-02-28 19:10:12,485 - modelscope - WARNING - Download interval is too small, use local cache
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151645 for open-end generation.
Traceback (most recent call last):
  File "/home/asus/Qwen/main.py", line 23, in <module>
    generated_ids = model.generate(
                    ^^^^^^^^^^^^^^^
  File "/home/asus/Downloads/yes/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/asus/Downloads/yes/lib/python3.11/site-packages/transformers/generation/utils.py", line 1520, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "/home/asus/Downloads/yes/lib/python3.11/site-packages/transformers/generation/utils.py", line 2653, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0`
求教是为什么

**Comment by laoyin** [comment]
我用7b模型好像也会，换成14b就ok的

**Comment by nicole828** [comment]
72b也会报错，什么原因呢？

**Comment by chopin1998** [comment]
> 我用7b模型好像也会，换成14b就ok的

我怎么和你是反过来的。。。。 7b可以14b出这个错

**Comment by sola634** [comment]
我也遇到相同问题，请问是否有解决方案？我的是14b

**Comment by qingqinghu1026** [comment]
7B-Int4 遇到了同样问题，请问有解决方案吗

**Comment by sola634** [comment]
这个问题我换成了14b-int4就没问题了，我之前跑的是14b-int8，感觉是机器跑int8的量化处理不过来

**Comment by qingqinghu1026** [comment]
> 这个问题我换成了14b-int4就没问题了，我之前跑的是14b-int8，感觉是机器跑int8的量化处理不过来

>我的还是不行，7B-int4 报这个错误，7B-int8能运行，但是答非所问，类似出现幻觉

**Comment by Qing1Zhong** [comment]
使用官方提供的finetune.sh （ZeRO2+QLora）微调Qwen1.5-0.5B-Chat模型后，在推理过程中遇到相同的问题。QAQ...

**Comment by yawzhe** [comment]
我也有这样的问题，怎么解决呀？我这个是两个人同时调用，线程出错后就出现这个问题，14b大模型

**Comment by lukeewin** [comment]
我今天也遇到了相同报错的问题，我用的模型是Qwen1.5-14B-Chat-GPTQ-Int8

请问你们有解决方案吗？

**Comment by bokesyo** [comment]
不要用fp16，用bf16就没有问题了 @lukeewin

**Comment by yawzhe** [comment]
在A6000上使用streamlit部署，不可以同时调用，否则就报上面的错误，使用fp32可以，如果使用3090上可以两个人同时调用，怎么解决呀，使用了bf16也不行

**Comment by PengHe66** [comment]
我在cpu上训练qwen-audio是没啥问题，但是在A100上也会出现相同的报错，不知道是为什么？

**Comment by xiaochengcheng520** [comment]
> 在A6000上使用streamlit部署，不可以同时调用，否则就报上面的错误，使用fp32可以，如果使用3090上可以两个人同时调用，怎么解决呀，使用了bf16也不行

我也是这个问题，请问你解决了吗

**Comment by xuanlx** [comment]
https://qwen.readthedocs.io/en/latest/quantization/gptq.html   参考官方 pip install -U "optimum>=1.20.0"
