### ISSUE TITLE
qwen1.5的opencompass评估是否正确？72B的智能体能力还不如4B????

### ISSUE THREAD

**Issue by laiqinghan** [QwenLM/Qwen2#117]
<img width="1211" alt="image" src="https://github.com/QwenLM/Qwen1.5/assets/22470281/bedd8299-822b-4ce4-b8ae-8eb97d59237a">
而且4B,7B,14B能力分布图相似，唯独72B有点奇怪，为啥呢？？

**Comment by laiqinghan** [comment]
<img width="1237" alt="image" src="https://github.com/QwenLM/Qwen1.5/assets/22470281/cc6b8c99-81e0-47ef-b7a7-8bf01ab5581c">
有俩数据集底的离谱

**Comment by laiqinghan** [comment]
> 与我们的代理测试不一致。不知道那里发生了什么

ok,多谢

**Comment by JianxinMa** [comment]
在咨询opencompass团队了。主要是CIBench的指标异常低，不清楚为什么。
