### ISSUE TITLE
关于72b不同量化类型的问题💡 [REQUEST] - <title>

### ISSUE THREAD

**Issue by White-Friday** [QwenLM/Qwen2#123]
### 摘要 | Summary

请问Qwen1.5-72B-Chat-GPTQ-Int4、Qwen1.5-72B-Chat-GPTQ-Int8、Qwen1.5-72B-Chat这三个版本之间的准确度差距有多大

### 基本示例 | Basic Example

请问Qwen1.5-72B-Chat-GPTQ-Int4、Qwen1.5-72B-Chat-GPTQ-Int8、Qwen1.5-72B-Chat这三个版本之间的准确度差距有多大

### 缺陷 | Drawbacks

请问Qwen1.5-72B-Chat-GPTQ-Int4、Qwen1.5-72B-Chat-GPTQ-Int8、Qwen1.5-72B-Chat这三个版本之间的准确度差距有多大

**Comment by xinzaifeixiang1992** [comment]
基于llama-factory框架微调qwen1.5-72b-chat后的模型，直接基于transformers可以正常推理。
但是量化成awq后，部署推理就不正常了。简单的问题会一直重复生成，导致推理非常耗时

**Comment by Fred199683** [comment]
> 基于llama-factory框架微调qwen1.5-72b-chat后的模型，直接基于transformers可以正常推理。 但是量化成awq后，部署推理就不正常了。简单的问题会一直重复生成，导致推理非常耗时

我也是基于llama factory微调后，你有尝试过auto gptq的量化吗
