### ISSUE TITLE
Continue pretrainig support

### ISSUE THREAD

**Issue by zhehengluoK** [QwenLM/Qwen2#143]
请问想要从release的节点继续continue pretrain的话，在训练和tokenization上有什么需要注意的点吗？和继续训练llama的话会有什么区别呢？

**Comment by JustinLin610** [comment]
things to notice:

1. we do not have bos token and eos token. we use `<|endoftext|>` to separate the docs.
2. pay attention to the rope theta. ours are usually very large. use the same one or larger one if you want to further extend the context length
