### ISSUE TITLE
如何把qwen1.5部署为api形式？你们的其他项目qwen-agent，想要调api形式的qwen1.5

### ISSUE THREAD

**Issue by GoogleAlphaZero** [QwenLM/Qwen2#146]

**Comment by JianxinMa** [comment]
个人本地跑模型，推荐用ollama，参见 https://github.com/QwenLM/Qwen-Agent/issues/95#issuecomment-1987785011

如果你有性能很好的gpu机器，可以考虑使用vllm，参见 qwen1.5（本项目）的README：https://github.com/QwenLM/Qwen-Agent/issues/95#issuecomment-1987785011

**Comment by JianxinMa** [comment]
ollama 启动 openai 的方式应该很简单，参见我上面评论的链接。

vllm 启动openai的方式也同样简单（虽然vllm可能对机器的环境要求高些），先 `pip install -U vllm` 下，然后按 README 说的执行如下命令：
```
python -m vllm.entrypoints.openai.api_server --served-model-name Qwen1.5-7B-Chat --model Qwen/Qwen1.5-7B-Chat
```
之后就获得了 openai 服务，vllm 的默认 api_base 是 `http://localhost:8000/v1`，model 和上面启动命令一致，比如 `Qwen1.5-7B-Chat` 。

@JustinLin610 要找人适配下之前的 openai_api.py 到 qwen1.5？虽然文档提了 ollama 和 vllm，但是似乎还是有很多用户看不太懂。不清楚是没讲清楚还是没提供中文文档的缘故。

**Comment by wfnian** [comment]
> ollama 启动 openai 的方式应该很简单，参见我上面评论的链接。
> 
> vllm 启动openai的方式也同样简单（虽然vllm可能对机器的环境要求高些），先 `pip install -U vllm` 下，然后按 README 说的执行如下命令：
> 
> ```
> python -m vllm.entrypoints.openai.api_server --served-model-name Qwen1.5-7B-Chat --model Qwen/Qwen1.5-7B-Chat
> ```
> 
> 之后就获得了 openai 服务，vllm 的默认 api_base 是 `http://localhost:8000/v1`，model 和上面启动命令一致，比如 `Qwen1.5-7B-Chat` 。
> 
> @JustinLin610 要找人适配下之前的 openai_api.py 到 qwen1.5？虽然文档提了 ollama 和 vllm，但是似乎还是有很多用户看不太懂。不清楚是没讲清楚还是没提供中文文档的缘故。

国产gpu不太容易安装vllm，我已经安装了两天了放弃了，希望尽快适配之前的openai_api.py接口  :octocat: :octocat: :octocat:

**Comment by JianxinMa** [comment]
> > ollama 启动 openai 的方式应该很简单，参见我上面评论的链接。
> > vllm 启动openai的方式也同样简单（虽然vllm可能对机器的环境要求高些），先 `pip install -U vllm` 下，然后按 README 说的执行如下命令：
> > ```
> > python -m vllm.entrypoints.openai.api_server --served-model-name Qwen1.5-7B-Chat --model Qwen/Qwen1.5-7B-Chat
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 之后就获得了 openai 服务，vllm 的默认 api_base 是 `http://localhost:8000/v1`，model 和上面启动命令一致，比如 `Qwen1.5-7B-Chat` 。
> > @JustinLin610 要找人适配下之前的 openai_api.py 到 qwen1.5？虽然文档提了 ollama 和 vllm，但是似乎还是有很多用户看不太懂。不清楚是没讲清楚还是没提供中文文档的缘故。
> 
> 国产gpu不太容易安装vllm，我已经安装了两天了放弃了，希望尽快适配之前的openai_api.py接口 :octocat: :octocat: :octocat:

@JustinLin610 看起来咱们考虑不周了，README也许需要为国产GPU加些说明。

**Comment by ALLinLLM** [comment]
@JianxinMa  金融行业信创要求新增硬件使用国产替代，我手上的某项目用的国产GPU是华为昇腾310，如果可以，希望能提供昇腾310上的api server的教程。国产大模型就用国产GPU，如果需要，我可以提供昇腾310的一台ECS的root密码供您调试。

**Comment by JustinLin610** [comment]
I'll promote this adaptation of Qwen1.5 to domestic GPUs, but it takes time as it is not really under my control... I am not an expert in this. oai api, how about using it with fastchat temporarily? When we got time we will create an py file like openai_api.py before.

**Comment by wfnian** [comment]
> 我会将 Qwen1.5 的这种适配推广到国产 GPU，但这需要时间，因为它并不在我的控制之下......我不是这方面的专家。OAI API，暂时将其与 FastChat 一起使用怎么样？当我们有时间时，我们将创建一个 py 文件，就像之前openai_api.py一样。

期待这个代码

**Comment by wfnian** [comment]
> I'll promote this adaptation of Qwen1.5 to domestic GPUs, but it takes time as it is not really under my control... I am not an expert in this. oai api, how about using it with fastchat temporarily? When we got time we will create an py file like openai_api.py before.

蹲一个。

**Comment by fairychao** [comment]
适配Qwen1.5的openai_api.py 有了吗

**Comment by GoogleAlphaZero** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
