### ISSUE TITLE
请问是否支持openai规范的tool_choice接口

### ISSUE THREAD

**Issue by YunmengLiu0** [QwenLM/Qwen2#148]
请问是否支持openai规范的tool_choice接口，上一个版本是支持的，但是1.5我目前使用是不支持的

**Comment by wfnian** [comment]
+1

**Comment by JianxinMa** [comment]
一般是什么场景用到tool_choice呢？上一个版本支持tool_choice的吗（没印象。。也许虽然传了能跑通但其实并没有啥作用？）

**Comment by JianxinMa** [comment]
@JustinLin610 虽然提供了vllm和ollama的启动openai api的说明，但是似乎还是有大量用户在怀念之前那个简单易用的openai_api.py（可惜那个脚本因为 .chat 方法的缺失没法用了）。@JustinLin610 你认为有必要花时间补充下那个 openai_api.py 吗？还是我们通过提供更简单易懂的中文文档来解决？

**Comment by YunmengLiu0** [comment]
上一个版本是支持的，我用着没有问题。在需要手动确认工具调用时或者模型不连外网的场景可以用到。请问是否有考虑在后续版本支持tool_choice呢

**Comment by JianxinMa** [comment]
> 上一个版本是支持的，我用着没有问题。在需要手动确认工具调用时或者模型不连外网的场景可以用到。请问是否有考虑在后续版本支持tool_choice呢

我看了下，qwen1 repo里提供的简易openai_api.py并没有实现对tool_choice的支持。请问您是用的具体什么代码启的openai api呢？
