### ISSUE TITLE
Qwen GPU memory usage/千问1.5版本显存占用问题

### ISSUE THREAD

**Issue by hheavenknowss** [QwenLM/Qwen2#175]
千问1.5版本占用的显存好像和1不是完全一样？用14b推理占用了近50gb的显存（A800），但是我看1的文档中，14b最多也才30gb，请问这是正常吗，如果不正常，请给一下各个模型占用显存大小，十分感谢！

**Comment by wadefollower** [comment]
一样的问题

**Comment by jklj077** [comment]
https://qwen.readthedocs.io/en/v1.5/benchmark/hf_infer.html
