### ISSUE TITLE
相同的程序，用 Qwen1.5-7B-Chat-GPTQ-Int4 没问题，用Int8则推理时报错

### ISSUE THREAD

**Issue by davidjia1972** [QwenLM/Qwen2#204]
相同的程序，用 Qwen1.5-7B-Chat-GPTQ-Int4 没问题，用 Qwen1.5-7B-Chat-GPTQ-Int8 在推理的时候报错：

RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by JustinLin610** [comment]
this is the problem of autogptq. gotta report this to them

**Comment by i7990X** [comment]
same here

**Comment by shikimoon** [comment]
same to me

**Comment by Rundong-Li** [comment]
same

**Comment by jklj077** [comment]
try using vllm or refer to https://github.com/QwenLM/Qwen2/issues/567
