### ISSUE TITLE
官方代码部署两个人调用会报错RuntimeError: probability tensor contains either inf, nan or element < 0 #102

### ISSUE THREAD

**Issue by yawzhe** [QwenLM/Qwen2#212]
我的是打开两个页面，同时调用或者错开调用，输入写长篇小说作文，其中一个会报上面的错误

**Comment by JustinLin610** [comment]
please provide the details for reproduction, which code, which model checkpoints. better provide a colab notebook for reproduction. 

usually, this case happens with quantized models and low temperature.

**Comment by CEfanmin** [comment]
> 我的是打开两个页面，同时调用或者错开调用，输入写长篇小说作文，其中一个会报上面的错误

请问一下，解决了吗？我也遇到了这个问题

**Comment by CEfanmin** [comment]
> please provide the details for reproduction, which code, which model checkpoints. better provide a colab notebook for reproduction.
> 
> usually, this case happens with quantized models and low temperature.



> please provide the details for reproduction, which code, which model checkpoints. better provide a colab notebook for reproduction.
> 
> usually, this case happens with quantized models and low temperature.

  File "/home/fanmin/qianwen/code/qwenLLM.py", line 56, in _call
    generated_ids = self.model.generate(model_inputs.input_ids,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fanmin/qianwen/lib64/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fanmin/qianwen/lib64/python3.11/site-packages/transformers/generation/utils.py", line 1592, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "/home/fanmin/qianwen/lib64/python3.11/site-packages/transformers/generation/utils.py", line 2734, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by sichehu** [comment]
> > 我的是打开两个页面，同时调用或者错开调用，输入写长篇小说作文，其中一个会报上面的错误
> 
> I increased the temperature and it worked.
Excuse me, what value did you set for the 'temperature' parameter to resolve the issue? Additionally, have you figured out the cause of the problem and other solutions?

**Comment by adzhua** [comment]
遇到同样的问题，同时多个调用会报错误，请问你最后是怎解决的？

**Comment by chenzaiping-dev** [comment]
在DB-GPT里会话也会出现“报错RuntimeError: probability tensor contains either inf, nan or element < 0”，老版的DB-GPT就可以，抓狂了
