### ISSUE TITLE
请教部署Qwen1.5-72B-int4模型进行压力测试问题

### ISSUE THREAD

**Issue by Hins** [QwenLM/Qwen2#233]
我用4张4090部署了Qwen1.5-72B-int4模型，用vllm作为推理框架，对模型进行压力测试。
2并发首字差不多可以在1.5秒内返回。
5并发和10并发，其中2个请求可以在1.5秒内返回，剩余请求都要在5秒甚至10秒后才能返回。
观察gpu显存，已经打满了，请问这种情况是否可以优化？

**Comment by xuexidi** [comment]
同问

**Comment by jklj077** [comment]
I don't think there is a way. vllm will queue the incoming requests if the remaining cache blocks are deemed insufficient. You can try to get more cache blocks by increasing gpu_memory_utilization, but risking OOM.

**Comment by chuangzhidan** [comment]
> 我用4张4090部署了Qwen1.5-72B-int4模型，用vllm作为推理框架，对模型进行压力测试。 2并发首字差不多可以在1.5秒内返回。 5并发和10并发，其中2个请求可以在1.5秒内返回，剩余请求都要在5秒甚至10秒后才能返回。 观察gpu显存，已经打满了，请问这种情况是否可以优化？

请问你是怎么做的压测

**Comment by xueshuai0922** [comment]
4个4090 =80G ，还没法对Qwen1.5-72B-int4  ，加载模型显存需要36G吧，加上Kv cache 等其他显存。36*1.5=54G，如果并发10 ，上下文10K ,预计65G够吧？
