### ISSUE TITLE
Error code: 400 - {'object': 'error', 'message' 'max_tokens must be at least 1, got -2815., 'type' 'BadRequestError', 'param': None, 'code': 400}

### ISSUE THREAD

**Issue by Modas-Li** [QwenLM/Qwen2#241]
INFO 04-02 14:55:30 async_llm_engine.py:508] Received request cmpl-b0572d1cb5534a5b9ccb40d91617eb16: prompt: '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n请提取问题中的关键词，需要中英文均有，可以适量补充不在问题中但相关的关键词。关键词尽量切分为动词/名词/形容词等类型，不要长词组。关键词以JSON的格式给出，比如{"keywords_zh": ["关键词1", "关键词2"], "keywords_en": ["keyword 1", "keyword 2"]}\n\nQuestion: 这篇文章的作者是谁？\nKeywords: {"keywords_zh": ["作者"], "keywords_en": ["author"]}\nObservation: ...\n\nQuestion: 解释下图一\nKeywords: {"keywords_zh": ["图一", "图 1"], "keywords_en": ["Figure 1"]}\nObservation: ...\n\nQuestion: 核心公式\nKeywords: {"keywords_zh": ["核心公式", "公式"], "keywords_en": ["core formula", "formula", "equation"]}\nObservation: ...\n\nQuestion: 上证指数多少点\nKeywords:\n<|im_end|>\n<|im_start|>assistant\n', sampling_params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.7, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['✿RESULT✿', '✿RESULT✿:', '✿RESULT✿:\n', 'Observation:', 'Observation:\n'], stop_token_ids=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=300, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt_token_ids: [151644, 8948, 198, 2610, 525, 264, 10950, 17847, 13, 151645, 198, 151644, 872, 198, 14880, 107439, 86119, 101047, 105291, 3837, 85106, 15946, 105205, 108549, 3837, 73670, 106968, 104361, 102972, 86119, 15946, 77288, 105470, 105291, 1773, 105291, 104638, 99322, 102239, 27733, 99689, 14, 113046, 14, 103196, 99689, 49567, 31905, 3837, 100148, 45861, 99689, 40027, 1773, 105291, 23031, 5370, 9370, 68805, 107485, 3837, 101912, 4913, 28995, 6415, 71, 788, 4383, 105291, 16, 497, 330, 105291, 17, 7914, 330, 28995, 6205, 788, 4383, 19863, 220, 16, 497, 330, 19863, 220, 17, 1341, 630, 14582, 25, 32181, 247, 113773, 9370, 57421, 105518, 94432, 43842, 25, 5212, 28995, 6415, 71, 788, 4383, 57421, 7914, 330, 28995, 6205, 788, 4383, 3094, 92010, 37763, 367, 25, 5468, 14582, 25, 85122, 68862, 16872, 28029, 14777, 198, 43842, 25, 5212, 28995, 6415, 71, 788, 4383, 28029, 14777, 497, 330, 28029, 220, 16, 7914, 330, 28995, 6205, 788, 4383, 22029, 220, 16, 92010, 37763, 367, 25, 5468, 14582, 25, 51461, 116, 63109, 110322, 198, 43842, 25, 5212, 28995, 6415, 71, 788, 4383, 100185, 110322, 497, 330, 110322, 7914, 330, 28995, 6205, 788, 4383, 2153, 14806, 497, 330, 59499, 497, 330, 25310, 367, 92010, 37763, 367, 25, 5468, 14582, 25, 64118, 33477, 104274, 100430, 27442, 198, 43842, 510, 151645, 198, 151644, 77091, 198], lora_request: None.
INFO 04-02 14:55:32 async_llm_engine.py:120] Finished request cmpl-b0572d1cb5534a5b9ccb40d91617eb16.
INFO: 112.65.186.246:53256 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request

**Comment by jklj077** [comment]
It appears an API issue with vllm, please seek support from them. Bad request often happens when invalid parameters are used.

**Comment by Modas-Li** [comment]
Thank you for your email !您好，你的邮件我已收到，我会尽快给你回复。
