### ISSUE TITLE
Qwen1.5-72B-chat-lora微调资源

### ISSUE THREAD

**Issue by JinXiaozhao** [QwenLM/Qwen2#245]
问题现象：
          使用lora+zero2策略对Qwen72B-chat进行微调训练，启动容器分配了1007G
          但加载模型权重是容器使用的内存超过了1007G，导致无法训练，请问模型直接加载到内存的现象是否正常？请问有没有解决办法？

**Comment by jklj077** [comment]
Please provide steps to reproduce. 
There should be an argument called low_cpu_mem_usage when loading model, which may be of help.
