### ISSUE TITLE
how to make Qwen1.5 supporty function calling like openai_api.py in Qwen

### ISSUE THREAD

**Issue by Stephen-SMJ** [QwenLM/Qwen2#252]
Dear Sir or Madam:

I just ran your function calling examples in Qwen (openai_api.py). But if I replace the model with Qwen1.5, there will be errors. 
The error is : AttributeError: 'Qwen2ForCausalLM' object has no attribute 'chat'
So I am confused about how to revise the code like openai_api.py to support Qwen1.5. Is there any idea?

Best regards.

**Comment by Stephen-SMJ** [comment]
The error is : AttributeError: 'Qwen2ForCausalLM' object has no attribute 'chat'

**Comment by samosun** [comment]
+1

**Comment by huangyunxin** [comment]
+1

**Comment by JianxinMa** [comment]
Please take a look at https://huggingface.co/Qwen/Qwen-72B-Chat/blob/main/modeling_qwen.py#L1250 which shows how .chat is implemented. Additionally, please note that the support for stop words is implemented via StopWordsLogitsProcessor.

**Comment by Stephen-SMJ** [comment]
> Please take a look at https://huggingface.co/Qwen/Qwen-72B-Chat/blob/main/modeling_qwen.py#L1250 which shows how .chat is implemented. Additionally, please note that the support for stop words is implemented via StopWordsLogitsProcessor.

Hi, 我参考您的指示重新写了一个类并继承Qwen2ForCausalLM，在这个类中新增了chat方法，但是发现qwen1.5和qwen存在一些配置上的不同：
1. Qwen1.5的model.generation_config中没有"chat_format"，"max_new_tokens"， "max_window_size"等属性，我默认了chat_format 为 chatml，但不确定后面两个属性还是否需要。
2. 在qwen_generation_utils.py中的make_context方法中
```    if chat_format == "chatml":
        im_start, im_end = "<|im_start|>", "<|im_end|>"
        im_start_tokens = [tokenizer.im_start_id]
        im_end_tokens = [tokenizer.im_end_id]
        nl_tokens = tokenizer.encode("\n")
```
'Qwen2Tokenizer' 没有 'im_start_id'属性，想问下这里该如何修改。

**Comment by JianxinMa** [comment]
> > Please take a look at https://huggingface.co/Qwen/Qwen-72B-Chat/blob/main/modeling_qwen.py#L1250 which shows how .chat is implemented. Additionally, please note that the support for stop words is implemented via StopWordsLogitsProcessor.
> 
> Hi, 我参考您的指示重新写了一个类并继承Qwen2ForCausalLM，在这个类中新增了chat方法，但是发现qwen1.5和qwen存在一些配置上的不同：
> 
> 1. Qwen1.5的model.generation_config中没有"chat_format"，"max_new_tokens"， "max_window_size"等属性，我默认了chat_format 为 chatml，但不确定后面两个属性还是否需要。
> 2. 在qwen_generation_utils.py中的make_context方法中
> 
> ```
>         im_start, im_end = "<|im_start|>", "<|im_end|>"
>         im_start_tokens = [tokenizer.im_start_id]
>         im_end_tokens = [tokenizer.im_end_id]
>         nl_tokens = tokenizer.encode("\n")
> ```
> 
> 'Qwen2Tokenizer' 没有 'im_start_id'属性，想问下这里该如何修改。

Regarding im_start and nl:

```py
>>> from transformers import AutoModelForCausalLM, AutoTokenizer
>>> tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen1.5-0.5B-Chat")
>>> tokenizer.convert_tokens_to_ids('<|im_start|>')
151644
>>> tokenizer.convert_tokens_to_ids('<|im_end|>')
151645
>>> tokenizer.tokenize('\n')
['Ċ']
>>> tokenizer.convert_tokens_to_ids(tokenizer.tokenize('\n'))
[198]
>>> from qwen_agent.utils.tokenization_qwen import tokenizer
>>> tokenizer.im_start_id
151644
>>> tokenizer.im_end_id
151645
>>> tokenizer.tokenize('\n')
[b'\n']
>>> tokenizer.convert_tokens_to_ids(tokenizer.tokenize('\n'))
[198]
>>> tokenizer.convert_tokens_to_ids(tokenizer.tokenize('<|im_start|>user\nhello<|im_end|>\n'))
[151644, 872, 198, 14990, 151645, 198]
```

As for max_new_tokens and max_window_size, you can set max_new_tokens to 2048 and set max_window_size to 32768 - 2048 = 30720 (or any other values as you deem suitable).

**Comment by Stephen-SMJ** [comment]
> > > Please take a look at https://huggingface.co/Qwen/Qwen-72B-Chat/blob/main/modeling_qwen.py#L1250 which shows how .chat is implemented. Additionally, please note that the support for stop words is implemented via StopWordsLogitsProcessor.
> > 
> > 
> > Hi, 我参考您的指示重新写了一个类并继承Qwen2ForCausalLM，在这个类中新增了chat方法，但是发现qwen1.5和qwen存在一些配置上的不同：
> > 
> > 1. Qwen1.5的model.generation_config中没有"chat_format"，"max_new_tokens"， "max_window_size"等属性，我默认了chat_format 为 chatml，但不确定后面两个属性还是否需要。
> > 2. 在qwen_generation_utils.py中的make_context方法中
> > 
> > ```
> >         im_start, im_end = "<|im_start|>", "<|im_end|>"
> >         im_start_tokens = [tokenizer.im_start_id]
> >         im_end_tokens = [tokenizer.im_end_id]
> >         nl_tokens = tokenizer.encode("\n")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 'Qwen2Tokenizer' 没有 'im_start_id'属性，想问下这里该如何修改。
> 
> Regarding im_start and nl:
> 
> ```python
> >>> from transformers import AutoModelForCausalLM, AutoTokenizer
> >>> tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen1.5-0.5B-Chat")
> >>> tokenizer.convert_tokens_to_ids('<|im_start|>')
> 151644
> >>> tokenizer.convert_tokens_to_ids('<|im_end|>')
> 151645
> >>> tokenizer.tokenize('\n')
> ['Ċ']
> >>> tokenizer.convert_tokens_to_ids(tokenizer.tokenize('\n'))
> [198]
> >>> from qwen_agent.utils.tokenization_qwen import tokenizer
> >>> tokenizer.im_start_id
> 151644
> >>> tokenizer.im_end_id
> 151645
> >>> tokenizer.tokenize('\n')
> [b'\n']
> >>> tokenizer.convert_tokens_to_ids(tokenizer.tokenize('\n'))
> [198]
> >>> tokenizer.convert_tokens_to_ids(tokenizer.tokenize('<|im_start|>user\nhello<|im_end|>\n'))
> [151644, 872, 198, 14990, 151645, 198]
> ```
> 
> As for max_new_tokens and max_window_size, you can set max_new_tokens to 2048 and set max_window_size to 32768 - 2048 = 30720 (or any other values as you deem suitable).

Hi, I successfully modified the program and it works now. But there is a warning in qwen_generation_utils.py:
        def _tokenize_str(role, content):
            return f"{role}\n{content}", tokenizer.encode(
                role, allowed_special=set()
            ) + nl_tokens + tokenizer.encode(content, allowed_special=set())

        system_text, system_tokens_part = _tokenize_str("system", system)

Once the program passed here, there is a warning: Keyword arguments {'allowed_special': set()} not recognized.
Thanks for your suggestion.

**Comment by JianxinMa** [comment]
@Stephen-SMJ Please replace `tokenizer.encode(s, allowed_special=...)` (from Qwen1) with `tokenizer.convert_tokens_to_ids(tokenizer.tokenize(s))` (for Qwen1.5).

**Comment by samosun** [comment]
@Stephen-SMJ hi  Could you please share a well-functioning reference code?

**Comment by Stephen-SMJ** [comment]
Thanks for @JianxinMa. Since some people want the code. I am considering releasing the code to the Qwen1.5 repo for your reference. Thanks.

**Comment by Stephen-SMJ** [comment]
> @Stephen-SMJ Please replace `tokenizer.encode(s, allowed_special=...)` (from Qwen1) with `tokenizer.convert_tokens_to_ids(tokenizer.tokenize(s))` (for Qwen1.5).

Hi. 我在我们自己的function calling应用中发现了一个问题。我用一张80G的A100来部署Qwen1.5-7b-Chat. 模型只占15g的内存，但是在generate()的时候，竟然会直接cuda out of memory. 同样的例子在Qwen1不会有这样的问题。我在跟Qwen1对比后发现，在generate方法中qwen1会多出一个max_window_size. 我初步感觉爆显存可能跟这个参数有关系，然而这个参数在Qwen2里我只能在make_context()中传入，但是不能在generate()方法中用kwargs传入，因为在utils.py的generation_config.validate()会报ValueError: The following `model_kwargs` are not used by the model: ['max_window_size'] (note: typos in the generate arguments will also show up in this list)。所以我觉得是Qwen2的GenerationConfig不允许有这个参数导致的。所以想确认一下Qwen2的generate()实现里面是否有必要穿入这个参数。以及您觉得有什么其他原因会导致爆显存吗，我目前Qwen2 Config的参数如下：

GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "max_new_tokens": 512,
  "pad_token_id": 151643,
  "repetition_penalty": 1.05,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

Thanks for your suggestion.

**Comment by JianxinMa** [comment]
> > @Stephen-SMJ Please replace `tokenizer.encode(s, allowed_special=...)` (from Qwen1) with `tokenizer.convert_tokens_to_ids(tokenizer.tokenize(s))` (for Qwen1.5).
> 
> Hi. 我在我们自己的function calling应用中发现了一个问题。我用一张80G的A100来部署Qwen1.5-7b-Chat. 模型只占15g的内存，但是在generate()的时候，竟然会直接cuda out of memory. 同样的例子在Qwen1不会有这样的问题。我在跟Qwen1对比后发现，在generate方法中qwen1会多出一个max_window_size. 我初步感觉爆显存可能跟这个参数有关系，然而这个参数在Qwen2里我只能在make_context()中传入，但是不能在generate()方法中用kwargs传入，因为在utils.py的generation_config.validate()会报ValueError: The following `model_kwargs` are not used by the model: ['max_window_size'] (note: typos in the generate arguments will also show up in this list)。所以我觉得是Qwen2的GenerationConfig不允许有这个参数导致的。所以想确认一下Qwen2的generate()实现里面是否有必要穿入这个参数。以及您觉得有什么其他原因会导致爆显存吗，我目前Qwen2 Config的参数如下：
> 
> GenerationConfig { "bos_token_id": 151643, "do_sample": true, "eos_token_id": [ 151645, 151643 ], "max_new_tokens": 512, "pad_token_id": 151643, "repetition_penalty": 1.05, "temperature": 0.7, "top_k": 20, "top_p": 0.8 }
> 
> Thanks for your suggestion.

qwen1 generate make_context 的max_window_size，其作用主要是用于截断过长的对话历史（见 https://huggingface.co/Qwen/Qwen-72B-Chat/blob/main/qwen_generation_utils.py#L124 ），功能上大概相当于 qwen 2 tokenizer.tokenizer.apply_chat_template 的 max_length  参数（见 https://huggingface.co/docs/transformers/v4.39.3/en/internal/tokenization_utils#transformers.PreTrainedTokenizerBase.apply_chat_template ）

**Comment by Stephen-SMJ** [comment]
> > Thanks for @JianxinMa. Since some people want the code. I am considering releasing the code to the Qwen1.5 repo for your reference. Thanks.
> 
> hi @Stephen-SMJ ，do you have a schedule for it ? it will be great helpful

Hi, @samosun and @yysturdy. it's been a long time since I used Qwen1.5.  I am not sure if they already support the characteristics I mentioned. Do you still need it?

**Comment by samosun** [comment]
yes，it is helpful



---Original---
From: ***@***.***&gt;
Date: Wed, Jun 5, 2024 23:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QwenLM/Qwen1.5] how to make Qwen1.5 supporty function callinglike openai_api.py in Qwen (Issue #252)




   
Thanks for @JianxinMa. Since some people want the code. I am considering releasing the code to the Qwen1.5 repo for your reference. Thanks.
  
hi @Stephen-SMJ ，do you have a schedule for it ? it will be great helpful
  
Hi, @samosun and @yysturdy. it's been a long time since I used Qwen1.5.  I am not sure if they already support the characteristics I mentioned. Do you still need it?

**Comment by samosun** [comment]
@Stephen-SMJ Hi, Based on the ideas you provided, I have implemented a chat method that works for now. Are there any particular issues I should pay special attention to?

**Comment by Stephen-SMJ** [comment]
> @Stephen-SMJ Hi, Based on the ideas you provided, I have implemented a chat method that works for now. Are there any particular issues I should pay special attention to? [https://github.com/samosun/learn_qwen/blob/main/to_chat_model.py](url)

Thank you @samosun , I share my code in [https://github.com/QwenLM/Qwen2/pull/662](https://github.com/QwenLM/Qwen2/pull/662). By the way, I do not have time to implement streaming feature in function calling. I would be appreciated if you have time to refine it.

**Comment by Stephen-SMJ** [comment]
Hi everyone, I share my implementation in [https://github.com/QwenLM/Qwen2/pull/662](https://github.com/QwenLM/Qwen2/pull/662) for your reference. 
Thanks.
