### ISSUE TITLE
[BUG] vllm for new 32B series not support

### ISSUE THREAD

**Issue by ticoAg** [QwenLM/Qwen2#264]
vllm version: 0.4.0.post1

code:
```python
from vllm import LLM
import os

os.environ["VLLM_USE_MODELSCOPE"] = "True"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

llm = LLM(
    model="qwen/Qwen1.5-32B-Chat-GPTQ-Int4",
    trust_remote_code=True,
    gpu_memory_utilization=0.6,
)

output = llm.generate(
    "<|im_start|>system\n"
    "You are a helpful assistant<|im_end|>\n"
    "<|im_start|>user\n"
    "hi<|im_end|>\n"
    "<|im_start|>assistant\n"
)
print(output)
```

output:

[RequestOutput(request_id=0, prompt='<|im_start|>system\nYou are a helpful assistant<|im_end|>\n<|im_start|>user\nhi<|im_end|>\n<|im_start|>assistant\n', prompt_token_ids=[151644, 8948, 198, 2610, 525, 264, 10950, 17847, 151645, 198, 151644, 872, 198, 6023, 151645, 198, 151644, 77091, 198], prompt_logprobs=None, outputs=[CompletionOutput(index=0, text='!!!!!!!!!!!!!!!!', token_ids=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], cumulative_logprob=nan, logprobs=None, finish_reason=length, stop_reason=None)], finished=True, metrics=RequestMetrics(arrival_time=1712546427.2980602, last_token_time=1712546427.2980602, first_scheduled_time=1712546427.3036706, first_token_time=1712546427.37775, time_in_queue=0.005610466003417969, finished_time=1712546427.6158664), lora_request=None)]

**Comment by TingsongYu** [comment]
No special token is required, just enter the command directly, eg: 
```python
output = llm.generate("Hi")

**Comment by JustinLin610** [comment]
use awq but not gptq for vllm. https://huggingface.co/Qwen/Qwen1.5-32B-Chat-GPTQ-Int4
