### ISSUE TITLE
Qwen1.5-7b-chat cannot be loaded to GPU after fine-tuning with qlora

### ISSUE THREAD

**Issue by orderer0001** [QwenLM/Qwen2#273]
Qwen1.5-7b-chat loads normally before fine-tuning. After fine-tuning, qlora loads the model and consumes video memory. 4090 24g , what is the reason?

**Comment by jklj077** [comment]
I don't think I understand your description of issue. Do you mean that a QLoRA-tuned Qwen1.5-7B-Chat takes up more than 24GB GPU memory? If so, please provide steps to reproduce.

**Comment by orderer0001** [comment]
I fine-tuned Qlora according to this: https://github.com/OpenAccess-AI-Collective/axolotl. After training, part of it is loaded into the cpu when loading. I am using 4090 24g. But my adapter_model.safetensors are only 300mb. Even with the original 7B model, it should not exceed 24G. Don't know what the reason is
