### ISSUE TITLE
关于device_map的问题

### ISSUE THREAD

**Issue by datuizhuang** [QwenLM/Qwen2#286]
我在使用device_map='auto'后，就会在某些layer中报错，tensor分布在了多个GPU上，请问如何解决？

**Comment by JustinLin610** [comment]
`device_map='auto'` will automatically enables your model to run on multiple GPUs. If you would like to use only 1 GPU, you can set `device` or set the environment variable like `CUDA_VISIBLE_DEVICES=0`. Please provide the detailed code for reproduction.
