### ISSUE TITLE
qwen1.5-32b训练大概需要多少显存？我是用8卡A800，长度2k和4k都会显存溢出。但Yi-34B是可以全参数训练

### ISSUE THREAD

**Issue by huanghuidmml** [QwenLM/Qwen2#300]

**Comment by baisechundu** [comment]
- Deepspeed stage3: As for qwen1.3-32b, full parameter finetune need 4 machine(A800)，which are 32 gpus。
- But if you just use lora, qwen-72b could run  in one machine(A800)。

> When you make a "sft" task, it's better to print the model to ensure the Attention block is what you have set. Qwen1.5 provide three ATTENTION_CLASS:
```
QWEN2_ATTENTION_CLASSES = {
    "eager": Qwen2Attention,
    "flash_attention_2": Qwen2FlashAttention2,
    "sdpa": Qwen2SdpaAttention,
}
```
**Default mode is eager, which need more GPU memory. Suggest to choose flash_attention_2 or sdpa.**

Hope to help you!

**Comment by huanghuidmml** [comment]
好的，谢谢。不过qwen1.5这么耗显存的原因是此表太大吗

**Comment by WeixuanXiong** [comment]
> 好的，谢谢。不过qwen1.5这么耗显存的原因是词表太大吗？因为同等规模的Yi-34B在单台A800是可以全参数微调的

感觉跟词表的关系不太大，之前试过qwen1的sft，显存占用比qwen1.5理想很多，然而这俩模型用的是同一个tokenizer。我也很想知道为什么这俩模型在训练的时候显存占用差距这么大。

**Comment by jiangix-paper** [comment]
同问。qwen1.5-14B，单台A100机器最大长度是16384。但是codellama 13B，单台A100可以达到32768，且占用显存比qwen 14b的16384还少。

**Comment by HalcyonLiang** [comment]
同问 vllm 4*A10 相同数据  yi34B可以推理，qwen32B OOM...

**Comment by paulcx** [comment]
这个问题不仅是Qwen1.5，Qwen2.5也同样会出现OOM情况，例如Qwen2.5-32B完全相同的参数配置，Yi-1.5-34B都可以全参数微调，但是32B模型即使一般的长度都会出现oom。
