### ISSUE TITLE
使用Qwen1.5-14b-chat或者Qwen1.5-32b-chat-awq，用英文提问时均会有概率出现中英混杂的情况

### ISSUE THREAD

**Issue by lin-xiaosheng** [QwenLM/Qwen2#302]
该情况也出现在官方demo中
![image](https://github.com/QwenLM/Qwen1.5/assets/131971238/7986a04f-d349-471c-9522-fbc9bff20b15)

**Comment by JustinLin610** [comment]
this is a known issue of the models. no good way to solve this problem temporarily until we update the checkpoints.

**Comment by chenwr727** [comment]
@JustinLin610 When will you update the checkpoints? Do you have any plans?

**Comment by JustinLin610** [comment]
no eta. still working on it

**Comment by yezhongxiuchan** [comment]
这个问题存在于 qen1.5-72B中么？ 我们用 qwen1.5-72B-gptq-int4 ，也会产生这个问题。

**Comment by SongXiaoMao** [comment]
> 这个问题存在于 qen1.5-72B中么？ 我们用 qwen1.5-72B-gptq-int4 ，也会产生这个问题。

我使用qwen1.5-72b AWQ没有发现这个情况

**Comment by deeplearning-LI** [comment]
我也是，现在qwen2也这样。。。。我去用其他模型先了

**Comment by jklj077** [comment]
Hi, Qwen2 should be doing much better in this regard and we advise you to upgrade to Qwen2. If you still encounter this problem in your usecase, please open a new issue and post your case there.
