### ISSUE TITLE
[BUG]  Issue serving Qwen/Qwen1.5-14B-Chat using vLLM OpenAI Client(Online serving)

### ISSUE THREAD

**Issue by rbgo404** [QwenLM/Qwen2#308]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

I have been trying to serve the [Qwen/Qwen1.5-14B-Chat](https://huggingface.co/Qwen/Qwen1.5-14B-Chat) using the vLLM openAI client. Here's the API endpoint: http://localhost:8000/v1/completions|
If I use the generate endpoint it works but completions doesn't return on some prompts.
I have used the chat template as well.

### 期望行为 | Expected Behavior

It should return for any prompts.

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
Do you have example data that can be publicly shared so that we can reproduce the issue?
