### ISSUE TITLE
我想通过gptq量化qwen-moe-a2.7b。但是好像不支持，请问官方怎么量化的。

### ISSUE THREAD

**Issue by wellcasa** [QwenLM/Qwen2#328]
Traceback (most recent call last):
  File "/home/admin/workspace/aop_lab/app_source/run_gptq.py", line 89, in <module>
    model = AutoGPTQForCausalLM.from_pretrained(args.model_name_or_path, quantize_config, device_map="auto",
  File "/home/admin/miniconda3/lib/python3.10/site-packages/auto_gptq/modeling/auto.py", line 75, in from_pretrained
    model_type = check_and_get_model_type(pretrained_model_name_or_path, trust_remote_code)
  File "/home/admin/miniconda3/lib/python3.10/site-packages/auto_gptq/modeling/_utils.py", line 305, in check_and_get_model_type
    raise TypeError(f"{config.model_type} isn't supported yet.")
TypeError: qwen2_moe isn't supported yet.

# Name                    Version                   Build  Channel
auto-gptq                 0.7.1                    pypi_0    pypi
# Name                    Version                   Build  Channel
transformers              4.40.0                   pypi_0    pypi

**Comment by bozheng-hit** [comment]
You can try codes in this PR: https://github.com/AutoGPTQ/AutoGPTQ/pull/593.

**Comment by zxs-learn** [comment]
> You can try codes in this PR: [AutoGPTQ/AutoGPTQ#593](https://github.com/AutoGPTQ/AutoGPTQ/pull/593).

你好，我安装你提交的分支后对 Qwen2-57B-A14B-Instruct 这个模型进行量化，但是报了错误: 

TypeError: "Qwen2MoeDecoderLayer." forward() got multiple values for argument 'attention_mask'

不知道哪里操作错误了， 能麻烦您指导一下么？谢谢。
