### ISSUE TITLE
使用Adgen广告数据微调Qwen-MoE，输出问题

### ISSUE THREAD

**Issue by cooper12121** [QwenLM/Qwen2#333]
我使用Adgen广告数据微调Qwen-MoE-chat模型时，输出开头会有一些特殊的字段
![image](https://github.com/QwenLM/Qwen1.5/assets/55910045/17ea3941-0da1-435d-868c-acb6dcfadb20)
如”Humanmade“、”Humanity“、”Human“等，我的训练数据中没有这些字段，我的prompt构造也是符合你们的模板，在微调其他MoE模型时均没有出现过这种情况？

**Comment by jklj077** [comment]
May I know how you have finetuned model? Is it full-parameter finetuning or something else? Based on the limited information, it is hard to tell why (especially the `<UNK>`).

**Comment by cooper12121** [comment]
> May I know how you have finetuned model? Is it full-parameter finetuning or something else? Based on the limited information, it is hard to tell why (especially the `<UNK>`).

yeah, i use the sft data Adgen to finetune Qwen-MoE, <UNK> is due to the presence of training data, but other special worlds ,such as "Humanmade“、”Humanity“、”Human", there is no these worlds in train data, i don't know why

i also use our company's business data to finetune this model, there also apperas special world "Human", i don't know why ?

i use "<im_start>"as bos token and "<im_end>"as eos token, "endoftext"as pad token, use transformers.Tranier to train the model

**Comment by jklj077** [comment]
I think a reproduction script is needed as my best guess is that the Human/Assistant format is used somewhere.

**Comment by cooper12121** [comment]
> I think a reproduction script is needed as my best guess is that the Human/Assistant format is used somewhere.

actually, my prompt must have no "Human/Assistant", and the result also has"Humanmade“、”Humanity“, which make me very confused?
