### ISSUE TITLE
使用examples 里的sft 代码进行全参数微调，同样的参数、数据集，每次训练的loss不一样，是哪里有随机性吗？

### ISSUE THREAD

**Issue by atri2549** [QwenLM/Qwen2#334]

**Comment by jklj077** [comment]
Please first refer to PyTorch's official documentation on this topic: <https://pytorch.org/docs/stable/notes/randomness.html>.

In addition, for large language model training, bit-by-bit reproducibility is hard to achieve and often unnecessary.

**Comment by atri2549** [comment]
> Please first refer to PyTorch's official documentation on this topic: https://pytorch.org/docs/stable/notes/randomness.html.
> 
> In addition, for large language model training, bit-by-bit reproducibility is hard to achieve and often unnecessary.

谢谢，不过pytorch 和 cuda 的相关的都固定过了，没有用。
因为其他网络之前试过都是稳定复现的，Qwen1.5 有点奇怪，在数据的seq_len较长时（大概 >300），会出现同样的数据训练结果不一样的情况。
