### ISSUE TITLE
有计划适配unsloth吗？

### ISSUE THREAD

**Issue by rangehow** [QwenLM/Qwen2#339]
这个训练上比FA2更快，而且vram占用更少，在llama2的测试上非常有效。然而还不支持原生的qwen2，尽管有些三方脚本支持llamafy qwen，但是因为潜在的实现错误风险，让人不太有尝试欲望。unsloth已经被集成到llamafactory中。

benchmark：https://unsloth.ai/blog/mistral-benchmark#Benchmark%20tables
仓库：https://github.com/unslothai/unsloth

**Comment by jklj077** [comment]
Hi, unsloth has supported Qwen2 in May, 2024. Check it out!
