### ISSUE TITLE
[Question]Preprocess function: target_ids did not mask the prompt section.

### ISSUE THREAD

**Issue by GenerallyCovetous** [QwenLM/Qwen2#343]
I found that target_ids = input_ids.clone() and just mask the padding section. Is it ok that target_ids contains the prompt section?
And I just customly modify this part of code to mask the prompt section to make sure the target_ids be like [-100, -100, ... 5949(which is " Response", ... , -100, -100...]。But when I run finetune.py the loss value had actually incresed ? ?

**Comment by jklj077** [comment]
The `finetune.py` script within the `examples/sft` directory serves as a foundational example with ample room for customization and enhancement. Its simplicity underscores the need for users to tailor their data preprocessing and utilization strategies according to specific requirements and scenarios. When deciding whether to mask user input, consider factors such as domain uniqueness--unmasked for distinct domains--or presence of noise--masked to filter distractions. Ultimately, the effectiveness of your approach will be determined by empirical results. We encourage users to explore and implement personalized solutions to optimize their model's performance.

For users seeking a turnkey or codeless solution, explore the alternatives outlined in 
<https://github.com/QwenLM/Qwen1.5#finetuning>.
