### ISSUE TITLE
6张卡，怎么能够让vllm启动qwen1.5-32b-chat

### ISSUE THREAD

**Issue by Hjiassen** [QwenLM/Qwen2#344]
--tensor-parallel-size 6，无法通过vllm加速推理qwen1.5-32b-chat，大佬们知道怎么解决吗？

**Comment by jklj077** [comment]
Please provide the error logs.

**Comment by Hjiassen** [comment]
ValueError: Total number of attention heads (40) must be divisible by tensor parallel size (6).

**Comment by Hjiassen** [comment]
> Please provide the error logs.

ValueError: Total number of attention heads (64) must be divisible by tensor parallel size (5).

**Comment by jklj077** [comment]
Oh, I see. When configuring tensor parallelism, it's crucial to set the parallel size as a divisor of the total number of attention heads. For instance, with 40 attention heads, choices include 2, 4, or 8--the use of 5 is technically possible but not advised. Similarly, for a model with 64 attention heads, consider using 2, 4, 8, 16, or 32.

**Comment by Hjiassen** [comment]
> Oh, I see. When configuring tensor parallelism, it's crucial to set the parallel size as a divisor of the total number of attention heads. For instance, with 40 attention heads, choices include 2, 4, or 8--the use of 5 is technically possible but not advised. Similarly, for a model with 64 attention heads, consider using 2, 4, 8, 16, or 32.

好的，谢谢
