### ISSUE TITLE
Qwen1.5-7B-Chat AWQ量化的MMLU评测效果相比Qwen1.5-7B-Chat-GPTQ-Int4和Qwen1.5-7B-Chat相差特别大

### ISSUE THREAD

**Issue by luchangli03** [QwenLM/Qwen2#349]
我评测了Qwen1.5-7B-Chat和两个量化模型的MMLU效果，发现AWQ的分数特别低，比直接naive 4bit还差。这是什么情况呢？
浮点模型分数0.60，而GPTQ版本0.59而AWQ版本只有0.45，naive的版本都有0.589
GPTQ和AWQ量化模型:
https://huggingface.co/Qwen/Qwen1.5-7B-Chat-AWQ
https://huggingface.co/Qwen/Qwen1.5-7B-Chat-GPTQ-Int4

**Comment by jklj077** [comment]
How did you conduct the evaluation?

**Comment by luchangli03** [comment]
直接用的lm evaluation harness评测的



---- 回复的原邮件 ----
| 发件人 | Ren ***@***.***> |
| 日期 | 2024年04月26日 15:17 |
| 收件人 | ***@***.***> |
| 抄送至 | Luchang ***@***.***>***@***.***> |
| 主题 | Re: [QwenLM/Qwen1.5] Qwen1.5-7B-Chat AWQ量化的MMLU评测效果相比Qwen1.5-7B-Chat-GPTQ-Int4和Qwen1.5-7B-Chat相差特别大 (Issue #349) |

How did you conduct the evaluation?

**Comment by luchangli03** [comment]
lm_eval --model hf \
    --model_args pretrained=${model_path},trust_remote_code=true,dtype=float16 \
    --tasks mmlu \
    --batch_size 1 \
    --device cuda \
    --output_path $out_dir
