### ISSUE TITLE
多卡训练报错：ImportError: /root/.cache/torch_extensions/py38_cu118/fused_adam/fused_adam.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Qinger27** [QwenLM/Qwen2#350]
使用多卡训练的时候，会报错 ImportError: /root/.cache/torch_extensions/py38_cu118/fused_adam/fused_adam.so: cannot open shared object file: No such file or directory，通过多种方式重新安装了 deepspeed 仍然报错，有人可以帮忙解决一下吗？

**Comment by jklj077** [comment]
It seems the previous compilation failed. Please try removing the cached files:
```bash
rm -r /root/.cache/torch_extensions/py38_cu118/fused_adam/
```
