### ISSUE TITLE
Qwen1.5-110B-Chat-GPTQ-Int4模型在system提示词中加入引号或者换行会导致模型不输出

### ISSUE THREAD

**Issue by QYCin2020** [QwenLM/Qwen2#351]
前提条件：
1. Qwen1.5-110B-Chat-GPTQ-Int4模型在ModelScope下载
2. 使用llama_factory+vllm以OpenAI API格式服务部署
3. 同样的问题在Qwen1.5 7B、32B上没有出现

能正常输出的system提示如下：
system =  '你是一个有用的助手'

不生成结果的system提示如下：
systemp = '你是一个有用的助手"'
或者
systemp = '你是一个有用的助手\n'

**Comment by JustinLin610** [comment]
we'll take a look but some strange things may happen at quantized models time to time. not sure if we can solve this, but just advise you to use a stable system prompt
