### ISSUE TITLE
Qwen1.5-110B-Chat的中文能力是否评测过，如cmmlu，ceval等

### ISSUE THREAD

**Issue by wuyaoxuehun** [QwenLM/Qwen2#352]
根据https://qwenlm.github.io/blog/qwen1.5-110b 
可以看出英文能力确实可以和llama3媲美，请问是否评测过Qwen1.5-110B-Chat的中文能力，如cmmlu，ceval等

**Comment by JustinLin610** [comment]
Yeah it even outcomptes 72B a lot. but as it is sometimes meaningless for these benchmarks to really reflect the quality and as we have confidence in Chinese, we did not share it for comparison with Llama-3 (as it almost knows little about Chinese). Sure, we can add it to the blog later

**Comment by wuyaoxuehun** [comment]
> Yeah it even outcomptes 72B a lot. but as it is sometimes meaningless for these benchmarks to really reflect the quality and as we have confidence in Chinese, we did not share it for comparison with Llama-3 (as it almost knows little about Chinese). Sure, we can add it to the blog later

Thanks for you reply. Maybe you can compare it with other Chinese LLMs, such as Yi-34B, Qwen1.5-72B, or Chinese OpenCompass 2.0 benchmark with Claude and GPT-4. 

Awesome Work!
