### ISSUE TITLE
Qwen1.5量化结果不一致

### ISSUE THREAD

**Issue by leiwen83** [QwenLM/Qwen2#372]
Hi，

我这边想咨询一下量化相关问题，比如https://huggingface.co/Qwen/Qwen1.5-72B-Chat-GPTQ-Int4 和https://huggingface.co/Qwen/Qwen1.5-72B-Chat-AWQ，这两个模型为基于Qwen1.5-72B-Chat分别通过GPTQ和AWQ量化方法得到的int4模型。但是实验发现这两个int4模型的回答并不一致，相差较大。

且本地通过autoawq得到的int4模型和官方提供的awq模型回答相比，也有较大出入，请问int4量化是否需要额外的校准？
如何保证：
1. 本地量化效果和官方一致
2. 不同量化方法效果一致。

多谢~

**Comment by jklj077** [comment]
1. GPTQ and AWQ both need a calibration dataset to produce the quantized weights. Different calibration dataset will produce different quantized models.
2. I don't think it is expected that AutoGPTQ and AutoAWQ would produce the same quantized model or is it necessary. Use the other one if one method is not satisfactory. May I know what is your usecase?

**Comment by leiwen83** [comment]
我这边的主要述求是能够和达到官方一致的量化效果。
请问目前GPTQ和AWQ官方发布版本校准dataset是使用的是哪一个？用户可以本地重现量化结果吗？。。

**Comment by jklj077** [comment]
In-house dataset. I don't think it is fully reproducible...
