### ISSUE TITLE
qwen1.5如何在t4卡中运行？

### ISSUE THREAD

**Issue by ye7love7** [QwenLM/Qwen2#373]
T4卡不能装cu12，无法安装torch2.1，我很好奇有人用t4启动了千问1.5的模型，是因为忽略新版transformers的torch冲突吗？

**Comment by jklj077** [comment]
CUDA 12.1 supports T4. PyTorch 2.1 also supports T4. Which version of transformers raises what errors of conflicts?

**Comment by ye7love7** [comment]
toch2.1不支持t4呀，需要cuda12x，t4不行



---原始邮件---
发件人: "Ren ***@***.***&gt;
发送时间: 2024年5月6日(周一) 晚上8:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [QwenLM/Qwen1.5] qwen1.5如何在t4卡中运行？ (Issue #373)




 
CUDA 12.1 supports T4. PyTorch 2.1 also supports T4. Which version of transformers raises what errors of conflicts?
