### ISSUE TITLE
Will Qwen1.5-110B-GPTQ-Int8 be released?

### ISSUE THREAD

**Issue by baiyongrui** [QwenLM/Qwen2#375]
Hello,
Is it any plan to release GPTQ Int8 quantized of 110B model?
Thanks for the Qwen1.5 open source great job!

**Comment by jklj077** [comment]
Hi! Unfortunately, we are currently having trouble in quantizing the model checkpoints with GPTQ and the resulted model is more likely to encounter NaNs. Before the issue is resolved, please try using the AWQ one instead.
