### ISSUE TITLE
how to reproduce QWEN1.5-7B-CHAT results

### ISSUE THREAD

**Issue by chunniunai220ml** [QwenLM/Qwen2#382]
how to reproduce QWEN1.5-7B-CHAT results as you report:

![image](https://github.com/QwenLM/Qwen1.5/assets/17668109/3c634665-4907-4d0b-b60c-b097a9a70981)

i got to TOEFL=30.198 by https://github.com/OpenLMLab/LEval as u mentioned

**Comment by hzhwcmhf** [comment]
[tpo.pred.json](https://github.com/QwenLM/Qwen1.5/files/15304654/tpo.pred.json)

Here is the output. We use greedy decoding, and the score may variance a little due to the precision problem. @chunniunai220ml

**Comment by chunniunai220ml** [comment]
> [tpo.pred.json](https://github.com/QwenLM/Qwen1.5/files/15304654/tpo.pred.json)
> 
> Here is the output. We use greedy decoding, and the score may vary a little due to the precision problem. @chunniunai220ml

can u provide example code with LEVAL? like https://github.com/OpenLMLab/LEval/blob/main/Baselines/llama2-chat-test.py, i modified the file to adapt QWEN1.5-CHAT-7B, but failed to reproduce your results

**Comment by chunniunai220ml** [comment]
@hzhwcmhf  hi, any further infomation for  example code with LEVAL
