### ISSUE TITLE
用2080TI 22G单张显卡跑 qwen 1.5 32B-INT4模型没有成功

### ISSUE THREAD

**Issue by zhuyang2356** [QwenLM/Qwen2#389]
总是报显存过小问题，设置了一些（比如 gpu_memory_utilzation, quantization）也没有用。请大伙帮忙看看
顺带提一下，2080TI 22G显卡是有22356MB的总显存。
#环境
ubuntu 20.04
cuda 12.1
pytorch 2.3.0+cu121
transformers 4.40.2
vllm 0.4.2

#代码如下：
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
tokenizers=AutoTokenizer.from_pretrained("../QwenModel/qwen15/Qwen1.5-32B-Chat-GPTQ-Int4")

sampling_params = SamplingParams(temperature=0.7, top_p=0.8, repetition_penalty=1.05, max_tokens=512)

llm = LLM(model="../QwenModel/qwen15/Qwen1.5-32B-Chat-GPTQ-Int4",
          gpu_memory_utilization=0.99,
          quantization="gptq")

prompt = "Tell me something about large language models."
messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

outputs = llm.generate([text], sampling_params)

for output in outputs:
      prompt = output.prompt
      generated_text = output.outputs[0].text
      print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

#报错如下

![image](https://github.com/QwenLM/Qwen1.5/assets/43929214/07eedc9c-d9ca-4ae0-8088-2cd83dca4bbb)

**Comment by jklj077** [comment]
Hi! Please first try **lowering** `gpu_memory_utilization` to preserve space for CUDA graph or setting `enforce_eager`.

**Comment by zhuyang2356** [comment]
> Hi! Please first try **lowering** `gpu_memory_utilization` to preserve space for CUDA graph or setting `enforce_eager`.

Hi， I have configured enforce_eager=True & gpu_memory_utilization=0.35, still the same problem.
![image](https://github.com/QwenLM/Qwen1.5/assets/43929214/2cbd3fb6-5326-436e-b2e6-5dea4eaf0f23)
![image](https://github.com/QwenLM/Qwen1.5/assets/43929214/6d5fddca-c097-4b01-b4a8-c52e3bfef2f2)

**Comment by heart18z** [comment]
单卡跑32B-int4   占用显存41G

**Comment by akai-shuuichi** [comment]
我单卡24G 占用21G, 你这个按理说跑得起来

**Comment by okone1995** [comment]
max_tokens=128 or 256 or 64试试

**Comment by WangJianQ-cmd** [comment]
是不是跑到一张卡上去了，看一下卡的占用情况

**Comment by zhuyang2356** [comment]
> 是不是跑到一张卡上去了，看一下卡的占用情况

我自己电脑就是单卡，买的2080 22G卡，就琢磨着单卡跑32B INT4来

**Comment by zhuyang2356** [comment]
> 我也遇到这种问题，大家有找到解决方案了吗。显存是够的，但总是显示cuda显存不够，然后报错

等你消息

**Comment by xuyuedream** [comment]
close gnome.
vllm serve Qwen/Qwen2.5-32B-Instruct-GPTQ-Int4 --dtype=float16 --gpu-memory-utilization 0.99 --max-model-len=4096  --enforce_eager
