### ISSUE TITLE
Not able to setup Qwen1.5-72B-Chat with Taskweaver

### ISSUE THREAD

**Issue by Haxeebraja** [QwenLM/Qwen2#390]
Not able to run taskweaver with locally hosted Qwen1.5-72B-Chat.
Taskweaver worked fine with Qwen-72B-Chat.

Getting error:
Exception: OpenAI API request was invalid: Error code: 400 - {'object': 'error', 'message': 'top_p must be in (0, 1], got 0.0.', 'type': 'BadRequestError', 'param': None, 'code': 400}

Qwen hosted using vllm:
python -m vllm.entrypoints.openai.api_server --served-model-name Qwen1.5-72B-Chat --model Qwen/Qwen1.5-72B-Chat 

Taskweaver config file:
{
"llm.api_base": "http://172.17.0.8:8283/v1",
"llm.api_key": "Null", 
"llm.model": "Qwen1.5-72B-Chat",
"execution_service.kernel_mode": "local"}

Following call work fine with ChatOpenAI in other application:
model = ChatOpenAI(
    model_name = 'Qwen1.5-72B-Chat',
    base_url = "http://172.17.0.8:8283/v1/",
    api_key = "EMPTY",
    temperature=0
)

**Comment by jklj077** [comment]
It appears that vllm has returned the error, because `top_p=0` is explicitly passed to the API call by TaskWeaver. I'm not sure why TaskWeaver would pass 0 to the API but you could try setting it to other values. I don't think your taskweaver config file is complete either, missing llm.api_type.
