### ISSUE TITLE
请问作者有尝试过neftune实验吗？

### ISSUE THREAD

**Issue by fanbooo** [QwenLM/Qwen2#418]
作者你好，目前我在qwen1.5上实验时，发现泛化性能不是特别好；
看这个研究说是有帮助，请问下你们之前有没有试过neftune_noise_alpha，如果有的话alpha设置多少会比较好呢？
https://github.com/neelsjain/NEFTune

**Comment by jklj077** [comment]
Hello there! Could you kindly clarify whether you're using the pre-existing model as is or if you've done some finetuning on your own? If you've done finetuning, it would be great to know which method you used. Also, let me know which specific model and domain you've noticed isn't performing well in terms of generalization. This kind of feedback really helps us improve the model for everyone's benefit. Just so we can make things better together!

**Comment by jklj077** [comment]
Assuming you were finetuning Qwen1.5-7B-Chat, it is good to make sure that you have enough and _diverse_ data for your target use.
