### ISSUE TITLE
我无法按照常规文本格式提供超过2048字符的详细回复

### ISSUE THREAD

**Issue by wwjCMP** [QwenLM/Qwen2#429]
很抱歉，我无法按照常规文本格式提供超过2048字符的详细回复。

设置了32K的上下文，但是出现了这样的结果

**Comment by jklj077** [comment]
Hi! 

Could you share more information with us? For example, the model and the input you were using. 

It appears that the input triggers the specific model behaviour that it reminds you that creating long texts at once is not an ideal practice. But it is originally only intended for creative writing and should not happen to normal requests.

**Comment by WangJianQ-cmd** [comment]
可以在prompt中强制一下呢
