### ISSUE TITLE
4张4090都启动不了Qwen1.5-14b-chat，报cuda内存不足。

### ISSUE THREAD

**Issue by zmxccxy** [QwenLM/Qwen2#439]
<img width="1903" alt="87f4e528b3492c65abdd23ada1bee27" src="https://github.com/QwenLM/Qwen1.5/assets/150102974/a29d6236-fde2-446d-b255-8b94e3df5ebb">
有4张4090还不够，感觉其他3张都没用上，大佬帮忙看看

<img width="1607" alt="750afd2d2ba20a6902c02eb34f66566" src="https://github.com/QwenLM/Qwen1.5/assets/150102974/2d71f349-e9ef-4314-85ad-34de67991208">

<img width="1382" alt="1130bc92c56efd2d74aec8f797a2728" src="https://github.com/QwenLM/Qwen1.5/assets/150102974/7e38af72-fecb-48da-8374-9f1e5969b40a">

启动：就是这段代码，放在demo.py文件里，然后python demo.py

![image](https://github.com/QwenLM/Qwen1.5/assets/150102974/b83e1837-fc92-4f7e-a61e-40b8ed82549a)

**Comment by WangJianQ-cmd** [comment]
指定一下启动的时候GPU

**Comment by jklj077** [comment]
Hi,

There is a message in your screenshot that explains the issue:
```
We've detected an older driver with an RTX 4000 series GPU. These drivers have issues with P2P. This can affect the multi-gpu inference when using accelerate device_map. Please make sure to update your driver to the latest version which resolves this.
```

You will need to update your GPU driver.

**Comment by jun0403** [comment]
我两张4090也爆显存，请问您最后解决了吗

**Comment by jun0403** [comment]
> <img alt="87f4e528b3492c65abdd23ada1bee27" width="1903" src="https://private-user-images.githubusercontent.com/150102974/333977418-a29d6236-fde2-446d-b255-8b94e3df5ebb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkyNDA4ODcsIm5iZiI6MTczOTI0MDU4NywicGF0aCI6Ii8xNTAxMDI5NzQvMzMzOTc3NDE4LWEyOWQ2MjM2LWZkZTItNDQ2ZC1iMjU1LThiOTRlM2RmNWViYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxMVQwMjIzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmEwMTAyOTY1Njg2YWJhYjUwMGFiZWFkZThiODM5NWQ4YmI1OWE0MmVjZDg4ZmFlOTEwNTg0NjU2ZGFmMzNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.usE1qGoqVl9IEXMB5izzDBsz9qCyN0ea27DaH4xgl4w"> 有4张4090还不够，感觉其他3张都没用上，大佬帮忙看看 <img alt="750afd2d2ba20a6902c02eb34f66566" width="1607" src="https://private-user-images.githubusercontent.com/150102974/333977486-2d71f349-e9ef-4314-85ad-34de67991208.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkyNDA4ODcsIm5iZiI6MTczOTI0MDU4NywicGF0aCI6Ii8xNTAxMDI5NzQvMzMzOTc3NDg2LTJkNzFmMzQ5LWU5ZWYtNDMxNC04NWFkLTM0ZGU2Nzk5MTIwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxMVQwMjIzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWQwMjIyZGU0OWRlOTYwMTU2N2YzM2JmNmMwODk0MzczZWU3NzQzODNjNmY2ZjEyNzhhMjNiNmYxM2ZkOGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UKo_BgfsXiAg03ZmQcfmYAaus_TTOQIwMKWxDg8MuVk"> <img alt="1130bc92c56efd2d74aec8f797a2728" width="1382" src="https://private-user-images.githubusercontent.com/150102974/333977511-7e38af72-fecb-48da-8374-9f1e5969b40a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkyNDA4ODcsIm5iZiI6MTczOTI0MDU4NywicGF0aCI6Ii8xNTAxMDI5NzQvMzMzOTc3NTExLTdlMzhhZjcyLWZlY2ItNDhkYS04Mzc0LTlmMWU1OTY5YjQwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxMVQwMjIzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTUxMzZjNWEyNzU1Yjg0ZDFhYWQxODA3N2UwMGEyMzllMTc0ZjI3MDNhMWZmMTEyMDBiYWE1ZGIxMGMzNzZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mUPwzcTv59q7RhK-rb-obL_fi7mABj9S4wLlBATIvWw">
> 启动：就是这段代码，放在demo.py文件里，然后python demo.py
> 
> ![image](https://github.com/QwenLM/Qwen1.5/assets/150102974/b83e1837-fc92-4f7e-a61e-40b8ed82549a)

请问您解决了吗
