### ISSUE TITLE
Qwen1.5-32B-chat自己量化后问知识库相关信息，总是出现更新截止时间xx年xx月

### ISSUE THREAD

**Issue by wf4867612** [QwenLM/Qwen2#447]
模型版本：Qwen1.5-32B-chat
微调：继续微调了自我认识
量化：基于模型进行了auto-awq量化
问题：提问这种带有阶段性时间的问题会出现如下内容，如图
![image](https://github.com/QwenLM/Qwen1.5/assets/49296681/8c11ffbc-677c-4196-af4d-a22c889c5b9b)
然后我们对比了魔塔的Qwen1.5-32B-chat demo，没有这个问题，如图
![img_v3_02b9_5bc16edf-f58f-4482-9959-232a1c6351bg](https://github.com/QwenLM/Qwen1.5/assets/49296681/31afe426-1681-4839-86db-7e384bf6ce56)

请问，这是这是什么原因导致的？量化之后损失了么？

**Comment by jklj077** [comment]
Hi,

Please first check if the non-quantized version has the same issue. If the non-quantized version works fine, it could be related to the calibration dataset used in the AWQ. If the non-quantized version shows the same problem, it is advised to check the finetuning dataset.
