### ISSUE TITLE
vllm 32BAWQ  4卡生成正常 8卡生成异常

### ISSUE THREAD

**Issue by wingjson** [QwenLM/Qwen2#454]
![image](https://github.com/QwenLM/Qwen1.5/assets/20148421/023adc28-e449-4265-8e82-bd720d799809)
![image](https://github.com/QwenLM/Qwen1.5/assets/20148421/6e01aa2e-d823-4772-b51f-a8a91a0bfac8)
会一直打印log，但是不输出结果，四张4090就没问题

**Comment by jklj077** [comment]
Hi, thanks for the report. I could indeed reproduce this. It is not slow with 8 GPUs per se. The model appears broken with tp=8 in vllm and as the stopping tokens are never generated, it just keeps going until max_tokens is met. In your case, generating 32K tokens will take a lot of time. We will be investigating the cause, but for now I haven't found a workaround. Please keep using tp=4 for this model in vllm for now.

**Comment by wingjson** [comment]
thanks
