### ISSUE TITLE
Flash Attention version of Qwen2

### ISSUE THREAD

**Issue by Pashisfisuta** [QwenLM/Qwen2#468]
ValueError: You are attempting to perform batched generation with padding_side='right' this may lead to unexpected behaviour for Flash Attention version of Qwen2. Make sure to  call `tokenizer.padding_side  = 'left'` before tokenizing the input.

**Comment by jklj077** [comment]
Hi, please make sure to call `tokenizer.padding_side  = 'left'` before tokenizing the input or pass `padding_side="left"` to the tokenizer call or set `padding_side="left"` when initializing the tokenizer if you're conducting batch inference with flash attention v2 in transformers.

**Comment by Pashisfisuta** [comment]
> Hi, please make sure to call `tokenizer.padding_side = 'left'` before tokenizing the input or pass `padding_side="left"` to the tokenizer call or set `padding_side="left"` when initializing the tokenizer if you're conducting batch inference with flash attention v2 in transformers.

tokenizer = AutoTokenizer.from_pretrained(
        model_args.model_name_or_path,
        use_fast=False,
        trust_remote_code=True,
        model_max_length=training_args.model_max_length,
        cache_dir=training_args.cache_dir,
        padding_side="left"
    )
    # tokenizer.padding_side  = 'left'
I have tried both methods, but still get an error. Does this have anything to do with the version of flashattn?

**Comment by jklj077** [comment]
Hi, 

Please share a script for reproduction and we can look into it.
