### ISSUE TITLE
全参数finetune时grad norm不收敛问题

### ISSUE THREAD

**Issue by fanbooo** [QwenLM/Qwen2#469]
Hi：
    我在qwen1.5-7B-chat的基础上，进行了全参数微调，数据量6w左右；观察到loss收敛正常，grad_norm不收敛，请问这个是什么原因导致的？是超参不合理还是训练数据中分布有问题？learning rate采用了cosine，最大学习率1e-5；

![8071de481c1e42c976e41e592405b1b8e1751a64](https://github.com/QwenLM/Qwen1.5/assets/27717525/f1cc298c-c3d7-4cd6-9cb8-c80c5af3e01c)
![b8ec40fdc1bc9e47de31b938bcebf4d9e0447cbb](https://github.com/QwenLM/Qwen1.5/assets/27717525/f55e59c5-304a-40f1-b84c-ab4ef8a554cd)
![2e8e5b2c1acef07ec8e3ed2a5f9197c5dd99fdef](https://github.com/QwenLM/Qwen1.5/assets/27717525/28270c06-fecf-4423-85f6-06ddd9b9eb52)

**Comment by fanbooo** [comment]
没有解决，训练的loss和梯度曲线还是遵循上图样式，但是测试的模型效果是符合预期的；

**Comment by flyrainer** [comment]
> 没有解决，训练的loss和梯度曲线还是遵循上图样式，但是测试的模型效果是符合预期的；

请问你说的效果符合预期， 是什么样的？ 我的loss降到这个程度， 基本就是过拟合了。 比如按照 sft里的问题问， 基本能回答正确。 稍微换个换法问， 就不行了。
