### ISSUE TITLE
ollama运行qwen2：7b一直输出大写字母G

### ISSUE THREAD

**Issue by Halflifefa** [QwenLM/Qwen2#485]
![image](https://github.com/QwenLM/Qwen2/assets/131593638/e9c1b9be-84fb-4a10-baa6-757aa8a39dcb)
无论问什么，都是输出G
是直接从ollama官方库拉的模型，ollama run qwen2

**Comment by cedarice** [comment]
我这儿也是一样的
![image](https://github.com/QwenLM/Qwen2/assets/12607063/6e608e58-ff20-478a-9889-6a286bf22a2b)

**Comment by yunzhichen** [comment]
+1

**Comment by jklj077** [comment]
Hi, all! 

There is an ongoing issue with the models running with `ollama` and we are actively working with them to pinpoint the root cause. For now, please use our GGUF model checkpoints with `llama.cpp`.

**Comment by JustinLin610** [comment]
We are collaborating with them to figure out where the problem comes from. My alternative solution is:

1. Download our GGUF file, say [qwen2-7b-instruct-q5_k_m.gguf](https://huggingface.co/Qwen/Qwen2-7B-Instruct-GGUF);
2. create a file named "Modelfile", whiose content is:

```
FROM qwen2-7b-instruct-q5_k_m.gguf

# set the temperature to 1 [higher is more creative, lower is more coherent]
PARAMETER temperature 0.7
PARAMETER top_p 0.8
PARAMETER repeat_penalty 1.05
TEMPLATE """{{ if and .First .System }}<|im_start|>system
{{ .System }}<|im_end|>
{{ end }}<|im_start|>user
{{ .Prompt }}<|im_end|>
<|im_start|>assistant
{{ .Response }}"""
# set the system message
SYSTEM """
You are a helpful assistant.
"""
```

3. Run `ollama create qwen2-7b -f Modelfile`;
4. Run `ollama run qwen2-7b`

This is how mine looks like:
![image](https://github.com/QwenLM/Qwen2/assets/27664428/162cbd99-2dd3-47ec-a3d9-6b77af291b0a)

**Comment by JustinLin610** [comment]
But actually even the ollama official manifest works for me. So strange. It might be a problem in llama.cpp that has caused all this.

![image](https://github.com/QwenLM/Qwen2/assets/27664428/0ca8b60c-1d13-47be-8854-abb414ee5632)

**Comment by muwei1989** [comment]
用llama.cpp也是一样的错误，
![qwerr](https://github.com/QwenLM/Qwen2/assets/5842444/4545abea-a8fd-49de-81f7-54515c93e3b2)

**Comment by jklj077** [comment]
Hi, there appears an issue with the GPU backend with llama.cpp, which ollama also uses.

In ollama, try this:
```
>>> /set parameter num_gpu 0
Set parameter 'num_gpu' to '0'
>>> hi
Hello! How can I assist you today?
```

**Comment by yangtianyu92** [comment]
> But actually even the ollama official manifest works for me. So strange. It might be a problem in llama.cpp that has caused all this.

thank you

**Comment by muwei1989** [comment]
> 用llama.cpp也是一样的错误， ![qwerr](https://private-user-images.githubusercontent.com/5842444/337501690-4545abea-a8fd-49de-81f7-54515c93e3b2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MzA0MjMsIm5iZiI6MTcxNzczMDEyMywicGF0aCI6Ii81ODQyNDQ0LzMzNzUwMTY5MC00NTQ1YWJlYS1hOGZkLTQ5ZGUtODFmNy01NDUxNWM5M2UzYjIuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMDMxNTIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzY5ZDhjNTVhZWM2N2M5NGI4NWI4ODI0MTQ5MWQ2NmVjZmRiODY3Zjc3NDU3YzgwZDkxYjk1MDIyNGExMWViZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9F65F3SezkHhP8UkLj6IC8B2bH8aonxZotOGecx7QYw)

llama.cpp可以工作，原来需要开启flash attention，server.exe -ngl 29 -fa -m qwen2-7b-instruct-q8.0.gguf
![qwok](https://github.com/QwenLM/Qwen2/assets/5842444/79eedd95-f45d-4992-8589-b75627f23b45)

**Comment by muwei1989** [comment]
llama.cpp可以工作，原来需要开启flash attention（增加-fa参数），server.exe -ngl 29 -fa -m qwen2-7b-instruct-q8.0.gguf
![qwok](https://github.com/QwenLM/Qwen2/assets/5842444/bfa1ca99-1924-4be9-9933-382dc6f1c70b)

**Comment by yangtianyu92** [comment]
3060解决方案是在启动ollama之前，set OLLAMA_FLASH_ATTENTION=True
就可以推理了，而且好像还快了。

**Comment by jklj077** [comment]
Hi, we have updated the README and provide a temporary workaround for llama.cpp and ollama running on GPU. The root cause is being resolved.

**Comment by sz0717** [comment]
Ollama has released v0.1.42 to solve this problem

**Comment by Sadeghi85** [comment]
ExllamaV2 is also affected. On my device it only generates token_id: 60021

![image](https://github.com/QwenLM/Qwen2/assets/2411443/142e15be-7cd4-4bfb-b0dd-829fa0da7f92)

**Comment by deadash** [comment]
设置环境变量。`set OLLAMA_FLASH_ATTENTION=True`，然后重启ollama, 

使用最新版本`ollama (0.1.42-0-gce0dc33)`

然后就可以了，速度起飞

**Comment by Lyzin** [comment]
> llama.cpp可以工作，原来需要开启flash attention（增加-fa参数），server.exe -ngl 29 -fa -m qwen2-7b-instruct-q8.0.gguf ![qwok](https://private-user-images.githubusercontent.com/5842444/337509718-bfa1ca99-1924-4be9-9933-382dc6f1c70b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzYwNTAsIm5iZiI6MTcxNzc3NTc1MCwicGF0aCI6Ii81ODQyNDQ0LzMzNzUwOTcxOC1iZmExY2E5OS0xOTI0LTRiZTktOTkzMy0zODJkYzZmMWM3MGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDdUMTU1NTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGM3NzdhN2Y3OWJmZmI3NGYzNTI5MDkzM2U4MTJhMjY0NjI5NmM5OWViOGI1YTlhODI1OWM4MmFkYzg0YTljNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JHZAPKHdPcnz2-VmS1gVYhcZVr6s4im4zvPWSLcRF6Y)

确实需要加-fa参数，我没加的时候，一直乱码，加了以后就正常了，用的llama.cpp(version:b2927)，而且推理速度更快了

**Comment by Hansimov** [comment]
> 设置环境变量。`set OLLAMA_FLASH_ATTENTION=True`，然后重启ollama,
> 
> 使用最新版本`ollama (0.1.42-0-gce0dc33)`
> 
> 然后就可以了，速度起飞

Thanks! You solution works for me with ollama v0.1.41.

First serve with `OLLAMA_FLASH_ATTENTION=True`:

```sh
OLLAMA_FLASH_ATTENTION=True ollama serve
```

Then run model:

```sh
ollama run qwen2:7b-instruct-q8_0
```

**Comment by ddup001** [comment]
> 设置环境变量。`set OLLAMA_FLASH_ATTENTION=True`，然后重启ollama,
> 
> 使用最新版本`ollama (0.1.42-0-gce0dc33)`
> 
> 然后就可以了，速度起飞

在哪里设置环境变量呢

**Comment by Goldlionren** [comment]
总结一下N卡遇到这个问题的话，如果是windows，可以在环境变量中设置OLLAMA_FLASH_ATTENTION为True，这样windows版本的ollama就没有问题了。

**Comment by jerell2isekai** [comment]
There seems to be the same issue with LM Studio.

**Comment by ddzyx** [comment]
环境变量在哪设置

**Comment by yangbin8** [comment]
> There seems to be the same issue with LM Studio.

LM Studio enables Flash Attention

**Comment by louis-gg** [comment]
> LM Studio 似乎也存在同样的问题。

可以在GPU Acceleration选项下，选择GPU OFFLOAD设置为0，使用CPU模式，就可以了。
我猜测，后续更新会解决这个问题。
![image](https://github.com/QwenLM/Qwen2/assets/63628324/34b8a0c1-379a-49e8-b55a-9ee6aab750d7)

**Comment by shaoguowen** [comment]
windows 更新到 0.1.42 以上版本就好了：https://github.com/ollama/ollama/releases/download/v0.1.43/OllamaSetup.exe

**Comment by lh61500** [comment]
![image](https://github.com/QwenLM/Qwen2/assets/54268962/d461e855-4bf0-4b0a-a1b6-9f6e31443c67)
这里设置环境变量就可以用了

**Comment by wzphood** [comment]
我的是这样的，跑7b没问题
ollama run qwen2-57b:latest
>>> 你好
H7=BC00$+663G1D@9:.1>)9:!@G<F<0DB-:F5E834>AH#D)A-F29F7516EGG*DA)%D=%<*#3@&##F;GE8CGB@GA,8*2A<5E<"D"+00";(.-3D":%;<CH7=BC00$+663G1D@9:.1>)9:!@G<F<0DB-:F5E834>AH#D)A-F29F7516EGG*DA)%D=%<*#3@&##F;GE8CGB@GA,8*2A<5E<"D"+00";(.-3D":%;<CA4@%-<!.G&DC@A*7E6,B5;@>:A*(C+4(97(C6"4%=G,F:;B1.F.8F.%"+)16H#4F1-*)*&"-.GE"D-"B=(D@.5AE3D1:@53(C&($3>G;F47-02A6)AB;4@%-<!.G&DC@A*7E6,B5;@>:A*(C+4(97(C6"4%=G,F:;B1.F.8F.%

**Comment by syd168** [comment]
ubuntu环境下，升级ollama到0.1.48 既可。亲测有效。而且速度起飞。
curl -fsSL https://ollama.com/install.sh | sh

**Comment by wzphood** [comment]
> ubuntu环境下，升级ollama到0.1.48 既可。亲测有效。而且速度起飞。 curl -fsSL https://ollama.com/install.sh | sh
还是这样。。。准备换一个小一点的模型试试。我在知乎上看有人用4090跑qwen2-57b，不知道为什么我的会乱码
&#0):"15;A#AA1(7=1-5!--((3@>9-F@H7!1&G5)-;0<31;89"!1:0(DC%686#%68!<#D1:(%9.C6"#9#7=<H#BC,BC%#2;+\7!>G9-2F>C;%)!(C%,E<,E74=,#5(&262G+!HG)>C(2$1:,,<+*7F4<)%#:A2@0.%+>"#,.31E&(3G55:&4B,=5,>-H5,,<+∗7F4<)+A<:A=$"@&.;;FEB%0-!,#,<DF!.&+F:5(;87

**Comment by Airbala** [comment]
我把4bit量化改成8bit量化就不会乱码了
