### ISSUE TITLE
Qwen2是不是bos token id有误？

### ISSUE THREAD

**Issue by Jerry-hyl** [QwenLM/Qwen2#486]
config文件中显示bos token对应的是<endoftext>,是否应该是<|im-start|>?

**Comment by jklj077** [comment]
Hi, may I know where this config file is?

For Qwen models, there is actually no BOS token in the sense that it should be added to all the input sequences. BOS token, even if it is set, should never be used.

<|im_start|> is used to mark the start of the converation turn in the chat template. The chat template should be handled correctly by most frameworks if they are using the embedded jinja template in the model files.

**Comment by Jerry-hyl** [comment]
Meanwhile, I have another question. When I finetune the base Qwen model with QA pairs, I can use the given chat template like `<im-start>user xxx<im-end><im-start>assistant xxx<im-end>`. But when I'm doing some domain-adapter pretraining, what template should I follow? I just have domain-related texts instead of QA pairs.

**Comment by jklj077** [comment]
Hi, that's intended. 

Certain third-parity frameworks require the existence of BOS token and it cannot be set to None or null. Setting it to <|endoftext|>, which is used to separate documents in sequences in pretraining (it appears before the document and after the document), can help people get started more easily.

**Comment by Jerry-hyl** [comment]
> Hi, that's intended.
> 
> Certain third-party frameworks require the existence of BOS token and it cannot be set to None or null. Setting it to <|endoftext|>, which is used to separate documents in sequences in pretraining (it appears before the document and after the document), can help people get started more easily.

Oh, I have got you point. Thanks!

**Comment by jklj077** [comment]
For pretrainig, we just concatenate the tokens from different documents and separate them with <|endoftext|> (151643), and then the tokens are split into batches of an equal length for training.

**Comment by zhanghanweii** [comment]
> Hi, may I know where this config file is?
> 
> For Qwen models, there is actually no BOS token in the sense that it should be added to all the input sequences. BOS token, even if it is set, should never be used.
> 
> <|im_start|> is used to mark the start of the converation turn in the chat template. The chat template should be handled correctly by most frameworks if they are using the embedded jinja template in the model files.

意思是代码中有bos的话，计算loss的时候不应该算入是吗

**Comment by LukeLIN-web** [comment]
How to set "eos_token" in qwen ?
