### ISSUE TITLE
GGUF for Qwen2-57B-A14B

### ISSUE THREAD

**Issue by jcl2023** [QwenLM/Qwen2#487]
I don't see ollama supports Qwen2-57B-A14B.
Any good reason for this? 
Is Qwen2-57B-A14B gguf available?

Thanks,

**Comment by jklj077** [comment]
Hi, 

ollama currently only has the llama.cpp backend. Although we have been working with llama.cpp to support Qwen2 MoE and the fp16 version should work out of the box, there have been reports that the quantized versions are not working. As people turn to llama.cpp or ollama most for quantized models, we just didn't release it in GGUF at all. We do have plans though.

So the short answer is currently no, but should be available later on.

**Comment by jcl2023** [comment]
@jklj077 

   Thanks for the update。 Let me know when it is available with Ollama

**Comment by cbrwx** [comment]
is it not this one? 

https://ollama.com/mannix/qwen2-57b:q4_k_m

**Comment by jcl2023** [comment]
Thanks for the info and I will try it later

**Comment by jklj077** [comment]
Thanks to contribution from the community. llama.cpp can run Qwen2-57B-A14B in its latest commit.
