### ISSUE TITLE
ollama 官方拉取的qwen2:7b 对话时出现乱码

### ISSUE THREAD

**Issue by yunzhichen** [QwenLM/Qwen2#488]
![_20240607080325](https://github.com/QwenLM/Qwen2/assets/18484282/0a2e0c12-ea8b-4b15-b85d-2412b889f3b3)
如上图，不知道是什么原因？

**Comment by Robin021** [comment]
<img width="1075" alt="image" src="https://github.com/QwenLM/Qwen2/assets/22043214/30596153-a201-4cc4-b4ef-2af7afff9281">
我也遇到了

**Comment by deadash** [comment]
一样，无法使用 `ollama version is 0.1.41`

**Comment by jklj077** [comment]
Hi, all! 

There is an ongoing issue with the models running with `ollama` and we are actively working with them to pinpoint the root cause. For now, please use our GGUF model checkpoints with `llama.cpp`.

**Comment by jklj077** [comment]
Hi, we are merging this issue with <https://github.com/QwenLM/Qwen2/issues/485> for better tracking. Please go there for future updates. Thanks!
