### ISSUE TITLE
GPQA、MATH 和 ARC-C 评估指标的疑问

### ISSUE THREAD

**Issue by mzchtx** [QwenLM/Qwen2#489]
关于[官网](https://qwenlm.github.io/blog/qwen2/)上的评估指标有几个疑问：
1. GPQA 使用的是哪个集合？Main、Diamond 还是 Extended？
2. ARC-C 是 25-shot 吗？为什么其它模型的 25-shot 指标都比较高，很多都到了 90+，而 Qwen2 评估的都比较低？是不是 0-shot？
3. GSM-8K 是 4-shot 吗？其它评估任务都使用的 8-shot，而且看着对比指标也像 8-shot 的？
<img width="905" alt="image" src="https://github.com/QwenLM/Qwen2/assets/37564754/e6ecc23f-044d-4f14-acaf-2389ca002805">

**Comment by liudayiheng** [comment]
GPQA/GSM8K采用science leaderboad的测法，ARC-C采用open llm leaderboard的测法

**Comment by mzchtx** [comment]
> GPQA/GSM8K采用science leaderboad的测法，ARC-C采用open llm leaderboard的测法

在 science leaderboad 和 open llm leaderboard 里没看到相关配置，所以咱们采用的配置是什么呢？

**Comment by qimw** [comment]
same question
