### ISSUE TITLE
如何配置使支持128K上下文？

### ISSUE THREAD

**Issue by momandai** [QwenLM/Qwen2#490]

**Comment by jklj077** [comment]
Hi, please refer the model card of the respective model. For example, <https://huggingface.co/Qwen/Qwen2-72B-Instruct#processing-long-texts>.

**Comment by 520jefferson** [comment]
> Hi, please refer to the model card of the respective model. For example, https://huggingface.co/Qwen/Qwen2-72B-Instruct#processing-long-texts. Please note that it is supported by Qwen2-7B-Instruct and Qwen2-72-Instruct and the latest vllm is needed to make use of it.

            "original_max_position_embeddings": 32768,

**Comment by lonngxiang** [comment]
具体怎么使用呢，链接里yarn没看明白怎么使用 @jklj077

**Comment by lonngxiang** [comment]
@jklj077 按要求配置了，输入6万字左右报错了：BadRequestError: Error code: 400 - {'object': 'error', 'message': "This model's maximum context length is 32768 tokens. However, you requested 37055 tokens in the messages, Please reduce the length of the messages.", 'type': 'BadRequestError', 'param': None, 'code': 400}

**Comment by kitty-nami** [comment]
@lonngxiang 你可能没有改对config文件

**Comment by lonngxiang** [comment]
> @lonngxiang 你可能没有改对config文件

你好，这边后续添加测试了，两张4090。也有点问题max-model-len 80000 ；输入长度超过58000后，输出全是感叹号，基本也难超过10万长度

**Comment by kitty-nami** [comment]
32k吧最多



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月13日 11:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [QwenLM/Qwen2] 如何配置使支持128K上下文？ (Issue #490) |

@lonngxiang 你可能没有改对config文件

你好，这边后续添加测试了，两张4090。也有点问题max-model-len 80000 ；输入长度超过58000后，输出全是感叹号，基本也难超过10万长度

**Comment by jorjiang** [comment]
> > @lonngxiang 你可能没有改对config文件
> 
> 你好，这边后续添加测试了，两张4090。也有点问题max-model-len 80000 ；输入长度超过58000后，输出全是感叹号，基本也难超过10万长度
仔细看下readme 上下文支持128k，但是输出只能到8K

> Context length support up to 128K tokens and can generate up to 8K tokens.
