### ISSUE TITLE
How to Reproduct the Evaluation

### ISSUE THREAD

**Issue by tonyw** [QwenLM/Qwen2#494]
How to Reproduct Qwen2-72B-Instruct evaluation, like  https://qwenlm.github.io/blog/qwen2/ PR results.
And I need the prompts for the evaluations.

**Comment by hzhwcmhf** [comment]
We are preparing the reproduction instructions. Please stay tuned.

If you have a specific dataset, maybe I can give a quick instruction.

**Comment by zjintheroom** [comment]
> We are preparing the reproduction instructions. Please stay tuned.
> 
> If you have a specific dataset, maybe I can give a quick instruction.

你好，问一下。现在评测脚本的进度如何，大概什么时间可以公开呢。谢谢
