### ISSUE TITLE
'Qwen2ForCausalLM' object has no attribute 'create_or_update_model_card'

### ISSUE THREAD

**Issue by wheresmyhair** [QwenLM/Qwen2#495]
Hi Qwen dev team, first thanks for the great contribution! I don't know if here's the right place but could you please look at this issue we encountered? Or post an issue at [transformers](https://github.com/huggingface/transformers)?

https://github.com/OptimalScale/LMFlow/pull/849

**Comment by jklj077** [comment]
Hi, 

The method `create_or_update_model_card` is provided by `peft` and should be called upon the `PeftModel` class, not the base `transformer` model (`Qwen2ModelForCausalLM` in this case). I don't know much detail but it appears a compatibility issue with `transformers` and `peft`. I would suggest turning to them for a prompt solution.
