### ISSUE TITLE
vllm0.40+Qwen1.5-32B-Chat-GPTQ-Int4，奇怪的生成问题，对于某些生成任务无法正确输出，对于其他的任务却能够正常输出

### ISSUE THREAD

**Issue by maoulee** [QwenLM/Qwen2#496]
环境：cu118
vllm=0..4.0
普通的文本生成任务：
![image](https://github.com/QwenLM/Qwen2/assets/110097108/f27c133f-c9fa-41a4-897d-3cf8720ff866)
总结性任务能够正常生成：
![image](https://github.com/QwenLM/Qwen2/assets/110097108/5156c2de-4496-49cb-b8d5-2eabf1e9442b)
vllm本地部署存在同样的问题：
![image](https://github.com/QwenLM/Qwen2/assets/110097108/8d8b62ca-fae6-4d15-8c69-530444322f3e)

请问这是参数设置不对，还是vllm问题？

**Comment by FightingSrain** [comment]
vllm版本问题

**Comment by jklj077** [comment]
Hi, 

Generating "!!!!" typically suggests Inf or NaN was met during computation. It is related both to the model itself, e.g., the quantization algorithm used, the original model behaviour, etc, and the implementation details in each framework or even in each version. The checkpoints quantized using GPTQ for Qwen1.5-32B can be vulnerable to such problem in the vllm implementation across multiple versions. We advise you to use Qwen1.5-32B-Chat-AWQ instead.
