### ISSUE TITLE
请问官网dashscope什么时候支持qwen2系列模型api调用

### ISSUE THREAD

**Issue by cgq0816** [QwenLM/Qwen2#497]
如题

**Comment by jklj077** [comment]
Hi, it should be there now: https://help.aliyun.com/zh/dashscope/developer-reference/tongyi-qianwen-7b-14b-72b-api-detailes

**Comment by cgq0816** [comment]
> Hi, it should be there now: https://help.aliyun.com/zh/dashscope/developer-reference/tongyi-qianwen-7b-14b-72b-api-detailes

调用报错
{'message': {'code': -1, 'message': 'NotFound'}, 'sender': 'ai', 'result_type': '文本', 'clean_chat_memory': False, 'status': 404}
