### ISSUE TITLE
[BUG] 输出全是 'GGGGGGGGGGGGGGGGGGGGGGG'

### ISSUE THREAD

**Issue by osbi-code** [QwenLM/Qwen2#500]
显卡：nvidia rtx 4060 ti 16G显存
运行：通过docker的ollama软件

1、开启GPU加速，问任何问题都是乱码回复 GGGGGG
2、不开启GPU，只用CPU输出一切正常

**Comment by osbi-code** [comment]
> 显卡：nvidia rtx 4060 ti 16G显存 运行：通过docker的ollama软件
> 
> 1、开启GPU加速，问任何问题都是乱码回复 GGGGGG 2、不开启GPU，只用CPU输出一切正常

用得模型：qwen2:7b

**Comment by jklj077** [comment]
Hi, 

This is a duplicate issue: <https://github.com/QwenLM/Qwen2/issues/485>.

Please refer to the README for a temporary workaround until the fix is released with ollama or llama.cpp.
