### ISSUE TITLE
lm_eval results is weird for Qwen2-1.5B

### ISSUE THREAD

**Issue by SefaZeng** [QwenLM/Qwen2#501]
I try to test the results of some benchmarks. But the score is too low:
```
| Tasks  |Version|Filter|n-shot| Metric |Value |   |Stderr|
|--------|------:|------|-----:|--------|-----:|---|-----:|
|arc_easy|      1|none  |     0|acc     |0.2647|±  |0.0091|
|        |       |none  |     0|acc_norm|0.2597|±  |0.0090|

|  Tasks   |Version|Filter|n-shot|Metric|Value |   |Stderr|
|----------|------:|------|-----:|------|-----:|---|-----:|
|winogrande|      1|none  |     0|acc   |0.5107|±  | 0.014|
```

**Comment by jklj077** [comment]
Hi, 

We follow the practice of Open LLM Leaderboard (which makes use of lm_evaluation_harness), the automatic evaluation results run by the HuggingFace Team for Qwen2-1.5B can be found at <https://huggingface.co/datasets/open-llm-leaderboard/details_Qwen__Qwen2-1.5B>.

You can also run the evaluation by yourself following <https://huggingface.co/spaces/open-llm-leaderboard/open_llm_leaderboard> in the `About` tab.
