### ISSUE TITLE
把Qwen2-57B-A14B跑起来需要多少显存啊？

### ISSUE THREAD

**Issue by NimbleDev** [QwenLM/Qwen2#502]
需要120G吗？我看评测里都是跟32B的模型做对比，需要的显存数量差不多吗？

**Comment by xuexiCh** [comment]
可以参考这个
![image](https://github.com/QwenLM/Qwen2/assets/107031948/61207387-46a2-4269-8c8a-9491885ca5b3)

**Comment by jklj077** [comment]
Hi, 

The total parameter count for this model is 57B, so it will need at least 114GB memory to load the parameters in 16bit floats. However, in generation, the activation is at the level of 14B models and much less than that of a dense model of the same size.

You can find our profiling [results](https://qwen.readthedocs.io/en/latest/benchmark/speed_benchmark.html) on GPU memory from the link provided in [README](https://github.com/QwenLM/Qwen2#requirements).
