### ISSUE TITLE
ollama  qwen2:7b  乱码， 只会回复"GGG GGGGG”

### ISSUE THREAD

**Issue by nne998** [QwenLM/Qwen2#505]
- 系统: debian 12
- qwen1.5 正常， qwen2 不正常：

<img width="590" alt="image" src="https://github.com/QwenLM/Qwen2/assets/148901/2c412dfb-e55e-4757-b009-01c578056bd4">

**Comment by jklj077** [comment]
Hi, 

This is a duplicate issue: <https://github.com/QwenLM/Qwen2/issues/485>.

Please refer to the README for a temporary workaround until the fix is released with ollama or llama.cpp.
