### ISSUE TITLE
Using unk_token, but it is not set yet.

### ISSUE THREAD

**Issue by FlorientHuang** [QwenLM/Qwen2#507]

**Comment by FlorientHuang** [comment]
is this a normal error?

**Comment by jklj077** [comment]
Hi, could you provide more context?

**Comment by FlorientHuang** [comment]
Iim trying to use qwen2

mycode

`
        doc_tokenizer = Qwen2Tokenizer.from_pretrained(
            model_args.doc_model_name_or_path,
            model_max_length=training_args.model_max_length,
            padding_side="right",
            use_fast=False,
            add_eos_token=False,
            unk_token='<|endoftext|>'
        )
        print('eos token', doc_tokenizer.eos_token, doc_tokenizer.eos_token_id)
        print('pad token', doc_tokenizer.pad_token, doc_tokenizer.pad_token_id)
        print(doc_tokenizer("你好吗 [SEP] [sep] iPhone 西瓜视频 在西江千户苗寨读艾青诗选 <endoftext>"))
        print(doc_tokenizer._tokenize("你好吗 [SEP] [sep] iPhone 西瓜视频 在西江千户苗寨读艾青诗选"))
        breakpoint()
        

`

output
`eos token <|im_end|> 151643
pad token <|endoftext|> None
{'input_ids': [108386, 101037, 508, 81376, 60, 508, 28036, 60, 12167, 8908, 58098, 100857, 87140, 73562, 60686, 69177, 99320, 17523, 101233, 101505, 57553, 102071, 99467, 100045, 30767, 366, 8691, 723, 427, 29], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
['ä½łå¥½', 'åĲĹ', 'Ġ[', 'SEP', ']', 'Ġ[', 'sep', ']', 'ĠiPhone', 'Ġè', '¥¿', 'çĵľ', 'è§Ĩé¢ĳ', 'Ġåľ¨', 'è¥¿', 'æ±Ł', 'åįĥ', 'æĪ·', 'èĭĹ', 'å¯¨', 'è¯»', 'èī¾', 'éĿĴ', 'è¯Ĺ', 'éĢī']`

**Comment by FlorientHuang** [comment]
分词的结果非常诡异，我手动加入了unk_token

并且我发现没有 pad_token_id

这两个现象都让我非常困惑

**Comment by FlorientHuang** [comment]
<img width="1791" alt="image" src="https://github.com/QwenLM/Qwen2/assets/92563084/f44351e4-f4b5-4f2d-a48c-8fbf6c71b9e2">

如果我尝试tokenize一句话，就会大量报错

**Comment by jklj077** [comment]
Hi,

That warning is fine as long as you are not actually using the unk token. For the type of tokenizers that Qwen uses, there is no unk any way.

The tokenizer is based on byte pair encoding on the UTF-8 encoded byte level. There is a bunch of issues on this. You can just search for them: <https://github.com/QwenLM/Qwen2/issues/314>, <https://github.com/QwenLM/Qwen2/issues/316>, etc.

**Comment by FlorientHuang** [comment]
那有什么办法可以可视化分词后的结果呢
