### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by jav-ed** [QwenLM/Qwen2#510]
I have a question about the "Tongyi Qianwen LICENSE AGREEMENT". It says (https://huggingface.co/Qwen/Qwen2-72B-Instruct/blob/main/LICENSE) usage would be allowed. However, if one would have more than some million active users, a license should be inquired. 

My scenario is that I am thinking of using qwen72b as a translator. Now, once I have translated the English text to Urdu, I might put it on my website. For the moment, it is far away from making any money. But, let's assume I would make money through this webpage and would get the translations through qwen72b. 

Thus, I would not get money or sell qwen72b itself, I would use its translations. In this described case, would I still have to apply for a licence if a very high number of active user is found?

**Comment by jklj077** [comment]
Hi,

You probably should apply a commercial license in that case, but you don't need to do it now, and can always apply later when the MAU reaches 100 million.

Please note the above response shall not be interpreted as legal advice.
