### ISSUE TITLE
ollama下跑qwen2:7b好像乱码了？

### ISSUE THREAD

**Issue by blue-eyed-g** [QwenLM/Qwen2#511]
![image](https://github.com/QwenLM/Qwen2/assets/67051930/709f2937-0d66-4282-a1a6-e93e6a5db4a7)

**Comment by Mrhyuan** [comment]
一样的问题

**Comment by ddup001** [comment]
一样的问题，手动pull、改参数，命令行下可行，api还是一样的GGG，根本没法用， 这么匆忙的推出完全不能用的版本，合适吗

**Comment by Anrunlu** [comment]
一样的问题
![image](https://github.com/QwenLM/Qwen2/assets/41146980/8374e981-5d19-47c6-91dc-45eb41dde4cc)

**Comment by Anrunlu** [comment]
ollama [v0.1.42](https://github.com/ollama/ollama/releases/tag/v0.1.42) 解决了这个问题。
![image](https://github.com/QwenLM/Qwen2/assets/41146980/6fa95f82-c83a-44aa-ab92-5ed1ae69edc9)

**Comment by crybest** [comment]
一样的问题，用CPU不会乱码，GPU乱码

**Comment by wwwzhouhui** [comment]
看这篇文章 https://www.toutiao.com/article/7377968523059970560/?log_from=9346a1546b0e6_1717830654195#/

**Comment by blue-eyed-g** [comment]
更新了最新版的ollama，已经解决
