### ISSUE TITLE
官方镜像跑示例代码，undefined symbol: _ZN3c104cuda9SetDeviceEi

### ISSUE THREAD

**Issue by yaogang2060** [QwenLM/Qwen2#512]
Dockers Image: [qwenllm/qwen:2-cu121](https://hub.docker.com/layers/qwenllm/qwen/2-cu121/images/sha256-97189c82950cced3d4d97f8a2f95842bbff27ed10a561b002261047da138d973?context=explore) 

code: in /data/shared/Qwen/, run `python web_demo.py`(只改了模型地址，使用了本地下载好的模型）：

![image](https://github.com/QwenLM/Qwen2/assets/12131589/abf95728-698b-41cb-a630-3dd13f455f6a)

version:
![image](https://github.com/QwenLM/Qwen2/assets/12131589/23d5ad31-51f7-4a4c-83c3-7bc002384c8b)

after `pip install --upgreade falsh-attn`, it works.

所以，这个镜像默认情况下是不是有问题？

**Comment by cnnu** [comment]
pip install --upgrade flash-attn

**Comment by yaogang2060** [comment]
> pip install --upgrade flash-attn

老兄，我在描述中写了这样可以。我就是质疑一下他们。 :)

**Comment by zidong-onepiece1** [comment]
我在微调时也遇到了相同的报错，qwenllm/qwen:2-cu121这个镜像提供的库无法正常使用，希望官方可以修复该问题。

**Comment by fyabc** [comment]
@yaogang2060 @zidong-onepiece1 您好，dockerhub上的镜像`qwenllm/qwen:2-cu121`和`qwenllm/qwen:latest`已更新，修复了这个问题，请重新尝试。
