### ISSUE TITLE
ollama 0.1.42下无法正常运行

### ISSUE THREAD

**Issue by liuaifu** [QwenLM/Qwen2#514]
C:\Users\laf163>ollama -v
ollama version is 0.1.42

C:\Users\laf163>ollama run qwen2:7b
```
>>> 天空为什么是蓝色的？
H2O

,@human_C0931

8667

天空EE为什么.B是D4蓝色*A,6因为D)光C5:!!F在1B(到达H大气0层9时,X&%*FG(,5G2会J@2与大气6"AE分子%9和,F@;颗粒C=发生E散射
1QC.=U因为3短,波6紫3色H的,A58光<频率F比2其他9)颜色"长%4波<长2光+更容易!#F-;G019散G射=。由于AB$天空;96(3主要&包含<的
是2\*蓝色#和绿#色*8光!，@0我们&">看到C:A1E

>>> Send a message (/? for help)
```

**Comment by liduang** [comment]
ollama run qwen2:7b-instruct 试试，我这个可以

**Comment by jklj077** [comment]
Hi, 

![image](https://github.com/QwenLM/Qwen2/assets/17811943/5efec1f5-c29c-4439-bfe5-735f87fdb634)


I'm currently unable to reproduce. 

Do you happen to know your driver version?
