### ISSUE TITLE
Continual Pretrain on qwen2-7b-instruct

### ISSUE THREAD

**Issue by michelyang** [QwenLM/Qwen2#517]
Hi team,
Thank you very much for the great work of qwen2. I am doing continual pretraining of qwen2-7b-instruct model using some Chinese and Korean text data. How to tokenize the examples? Do I need to add BOS and EOS tokens? Is the template look like [BOS text EOS] or [BOS text] or [text EOS]. I think qwen2-7b-instruct does not have BOS token, right? Thank you.

**Comment by jklj077** [comment]
Hi, 

[text EOS] should be fine.
