### ISSUE TITLE
Chat messages cannot end with the "system" role

### ISSUE THREAD

**Issue by linuxsong** [QwenLM/Qwen2#518]
In some complex tasks, there may be multiple "system" roles in a conversation, and the conversation ends with the "system" role. For example, when use Autogen executes the group chat demo task (https://microsoft.github.io/autogen/docs/tutorial/conversation-patterns#group-chat), the conversation message generated is as follows:

```
        messages=[
            {
                "content": "You are in a role play game. The following roles are available:\n                Adder_Agent: Add 1 to each input number.\nMultiplier_Agent: Multiply each input number by 2.\nSubtracter_Agent: Subtract 1 from each input number.\nDivider_Agent: Divide each input number by 2.\nNumber_Agent: Return the numbers given..\n                Read the following conversation.\n                Then select the next role from ['Adder_Agent', 'Multiplier_Agent', 'Subtracter_Agent', 'Divider_Agent', 'Number_Agent'] to play. Only return the role.",
                "role": "system",
            },
            {
                "content": "My number is 3, I want to turn it into 13.",
                "role": "user",
            },
            {
                "content": "Read the above conversation. Then select the next role from ['Adder_Agent', 'Multiplier_Agent', 'Subtracter_Agent', 'Divider_Agent', 'Number_Agent'] to play. Only return the role.",
                "role": "system",
            },
        ],

```

The message ends with "system" role.
When I use dashscope api request, it will response: 
```
{'code': 'invalid_parameter_error', 'param': None, 'message': 'Role must be user or assistant and Content length must be greater than 0', 'type': 'invalid_request_error'}
```

The same messages is work  when it is replaced with gpt-4 api(use with openrouter).

If I append  one   "user" role  message with something  to the messages , the response is ok.
Same result with "qwen1.5-110b-chat" or "qwen2-72b-instruct" model.

Is this dashscope's limit or model's  limit?And how to I solve it?

Thanks for your good job!

**Comment by jklj077** [comment]
Hi, 

I think the model is not trained with that format. There should be only one system message and it should be at the first place. I am not sure what DashScope does to allow two system messages. It could be okay if the last system message is merged with the last user message or the first system message.

**Comment by linuxsong** [comment]
It's  support two system  role messages when they are placed  front of messages.
Like this:

```
        messages=[
            {
                "content": "Your name is Qwen.",
                "role": "system",
            },
            {
                "content": "Your favorite color is blue.",
                "role": "system",
            },
            {
                "content": "What's your name and what's your favorite color?",
                "role": "user",
            },
        ]
```
It's works fine.

**Comment by jklj077** [comment]
As stated, I am not sure what DashScope does to allow two system messages. Please open a ticket to Aliyun if you have questions on DashScope.

**Comment by linuxsong** [comment]
> As stated, I am not sure what DashScope does to allow two system messages. Please open a ticket to Aliyun if you have questions on DashScope.

OK，thanks for your reply.
