### ISSUE TITLE
Is there any way to visualize the Chinese word segmentation results of qwen2?

### ISSUE THREAD

**Issue by FlorientHuang** [QwenLM/Qwen2#519]
Trying to use qwen2

mycode

`
doc_tokenizer = Qwen2Tokenizer.from_pretrained(
model_args.doc_model_name_or_path,
model_max_length=training_args.model_max_length,
padding_side="right",
use_fast=False,
add_eos_token=False,
unk_token='<|endoftext|>'
)
print('eos token', doc_tokenizer.eos_token, doc_tokenizer.eos_token_id)
print('pad token', doc_tokenizer.pad_token, doc_tokenizer.pad_token_id)
print(doc_tokenizer("你好吗 [SEP] [sep] iPhone 西瓜视频 在西江千户苗寨读艾青诗选 "))
print(doc_tokenizer._tokenize("你好吗 [SEP] [sep] iPhone 西瓜视频 在西江千户苗寨读艾青诗选"))
breakpoint()

`

output
eos token <|im_end|> 151643 pad token <|endoftext|> None {'input_ids': [108386, 101037, 508, 81376, 60, 508, 28036, 60, 12167, 8908, 58098, 100857, 87140, 73562, 60686, 69177, 99320, 17523, 101233, 101505, 57553, 102071, 99467, 100045, 30767, 366, 8691, 723, 427, 29], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]} ['ä½łå¥½', 'åĲĹ', 'Ġ[', 'SEP', ']', 'Ġ[', 'sep', ']', 'ĠiPhone', 'Ġè', '¥¿', 'çĵľ', 'è§Ĩé¢ĳ', 'Ġåľ¨', 'è¥¿', 'æ±Ł', 'åįĥ', 'æĪ·', 'èĭĹ', 'å¯¨', 'è¯»', 'èī¾', 'éĿĴ', 'è¯Ĺ', 'éĢī']

**Comment by jklj077** [comment]
Hi, 

You could try decode the ids.

```python
>>> from transformers import AutoTokenizer
>>> tokenizer = AutoTokenizer.from_pretrained("Qwen2-72B-Instruct")
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
>>> ids = tokenizer("你好吗 [SEP] [sep] iPhone 西瓜视频 在西江千户苗寨读艾青诗选").input_ids
>>> ids
[108386, 101037, 508, 81376, 60, 508, 28036, 60, 12167, 8908, 58098, 100857, 87140, 73562, 60686, 69177, 99320, 17523, 101233, 101505, 57553, 102071, 99467, 100045, 30767]
>>> [tokenizer.decode(i) for i in ids]
['你好', '吗', ' [', 'SEP', ']', ' [', 'sep', ']', ' iPhone', ' �', '��', '瓜', '视频', ' 在', '西', '江', '千', '户', '苗', '寨', '读', '艾', '青', '诗', '选']
```

The Unicode replacement character is there because those two tokens corresponding to byte sequences that are not valid UTF-8 by itself and you cannot "visualize" as unicode strings. As explained in the response to your previous issue, it is expected, as you should only decode on the complete id sequences.

```python
>>>  tokenizer.decode([8908, 58098])
' 西'
```

Or if you are verse in UTF-8 encoded byte sequences, you can also do this
```python
>>> tokenizer = AutoTokenizer.from_pretrained("Qwen2-72B-Instruct", use_fast=False)
>>> [bytes(tokenizer.byte_decoder[x] for x in tokenizer.decoder[y]) for y in ids if y <= tokenizer.vocab_size]
[b'\xe4\xbd\xa0\xe5\xa5\xbd', b'\xe5\x90\x97', b' [', b'SEP', b']', b' [', b'sep', b']', b' iPhone', b' \xe8', b'\xa5\xbf', b'\xe7\x93\x9c', b'\xe8\xa7\x86\xe9\xa2\x91', b' \xe5\x9c\xa8', b'\xe8\xa5\xbf', b'\xe6\xb1\x9f', b'\xe5\x8d\x83', b'\xe6\x88\xb7', b'\xe8\x8b\x97', b'\xe5\xaf\xa8', b'\xe8\xaf\xbb', b'\xe8\x89\xbe', b'\xe9\x9d\x92', b'\xe8\xaf\x97', b'\xe9\x80\x89']
```
