### ISSUE TITLE
Error with Qwen2-7B-instruct-AWQ : RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by lindylin1817** [QwenLM/Qwen2#522]
I tried the AWQ of Qwen2-7B-instruct. I used the AWQ model released by QWen2. But I got the runtime error when use model.generate(). 

`Traceback (most recent call last):

  File "/home/yhlin/qwen_try/test_qwen.py", line 70, in <module>
    generated_ids = model.generate(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1758, in generate
    result = self._sample(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2437, in _sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)

RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
`
May I know how to deal with it? I used torch 2.1.0. Thanks!

**Comment by andyjhj** [comment]
I have the same problem with you .

**Comment by jklj077** [comment]
Hi,

It is a common issue that the quantized models may encounter Infs and NaNs, as they run in fp16. However, there are some options that you could try:
1. Upgrade transformers, awq, and awq_extensions.
2. Adjust top_p or top_k instead of temperature in generation.
3. Use a different framework, e.g, vllm.

**Comment by wangchunlin** [comment]
how did you solve this problem? i am using gptq-int8 and got the same issue.
