### ISSUE TITLE
后续更新有计划提升知识库日期吗

### ISSUE THREAD

**Issue by gengjiawen** [QwenLM/Qwen2#525]
> My training data was last updated in 2021

当前看21年的，很多事情多不知道。谢谢开源这么棒的模型。

**Comment by jklj077** [comment]
Hi,

It is generally considered unreliable to ask a large language model its knowledge cutoff, as there is no way for the models to learn in pretraining and the date is injected in post-training.

The training data (including pretraining and posttraining) of the model contains materials as late as the end of 2023. 

In addition, Qwen models are causal language models and do not make use of knowledge base tenchinques.
