### ISSUE TITLE
为什么模型文件里面没有tokenizer.model 文件

### ISSUE THREAD

**Issue by Tendo33** [QwenLM/Qwen2#530]
如题

**Comment by jklj077** [comment]
Because it doesn't?

**Comment by Tendo33** [comment]
Ah ok, I'm just curious. Because I looked at other open source models such as yi1.5 glm4. They all have tokenizer models.

**Comment by jklj077** [comment]
Hi, 

`tokenizer.model` often comes with models that use the `sentencepiece` package for tokenization with byte pair encoding (BPE). For Qwen models, we have used the BPE algorithms at the byte level and the file counterpart is `merges.txt`.
