### ISSUE TITLE
Incomplete model response！！！

### ISSUE THREAD

**Issue by snowforlight** [QwenLM/Qwen2#531]
When generating a reply, a larger token value has been set, but the reply given by the model is not complete, as evidenced by the presence of an ellipsis in the middle part of the reply skipping some steps, and the end of the reply is still relatively complete. I have tried to add hints to let it describe the process of analyzing clearly, but there are still a lot of ellipses in its reply. What is causing this and how can I fix it?

**Comment by jklj077** [comment]
Hi,

We would greatly appreciate it if you could share such a case for us to reproduce.

**Comment by snowforlight** [comment]
![image](https://github.com/QwenLM/Qwen2/assets/96424578/7aaae1e5-96a2-46b6-9e07-056b9c16fc4b)
![image](https://github.com/QwenLM/Qwen2/assets/96424578/47cd1cda-7566-4bc9-b0c8-f5449df63f4d)
In both quizzes, the model responses were not hastily interrupted at the end, which should not be a limitation of the token value, and there were cases of ellipses skipped in the middle of the responses, despite the clarification of the need for a complete step-by-step analysis.The case of the Json format output, where only three objects were left to be displayed, was still skipped.

**Comment by snowforlight** [comment]
> 你好
> 
> 如果您能分享这样的案例供我们复制，我们将不胜感激。

Thank you so much for piping up with this question and also for guiding me as a beginner.

**Comment by jklj077** [comment]
Hi, 

It appears that you are running in a jupyter notebook and by default the output in notebook is truncated if it is too long. If it is the case, there will be an note at the end of the output and you can click the `text editor` link to view the full output.

P.S.: By sharing such a case, we would prefer if you could share the query instead of the response.

**Comment by snowforlight** [comment]
Thank you very much for your help! (Please pardon my oversight)
Here is what my query was about:
messages = [
    ("system","你是一名专业的新闻学专家，具有很强的信息抓取能力。请完整展示全部信息"),
    ("human","请你根据这篇报道地上下文场景，提取出其中出现的人名及其所担任的职务，并且将答案以json格式输出。"+"报道内容："+context),
]

messages = [
    ("system","你是一个聪明的高中学生，请运用你所学的高中物理知识，分步骤、有条理、逐题项回答以下物理问题，请注意思考的逻辑和顺序，不要跳过任何步骤。"),
    ("human","某航空公司的一架客机，在正常航线上作水平飞行时，由于突然受到强大垂直气流的作用，使飞机在10s内高度下降1700m造成众多乘客和机组人员的伤害事故，如果只研究飞机在竖直方向 上的运动 且假定这一运动是匀变速直线运动试计算： （1）飞机在竖直方向上产生的加速度多大？方向怎样？ （2）乘客所系安全带必须提供相当于乘客体重多少倍的竖直拉力，才能使乘客不脱离座椅？取10m/s） （3）未系安全带的乘客，相对于机舱将向什么方向运动？最可能受到伤害的是人体的什么部位？（注：飞机上乘客所系的安全带是固定连结在飞机座椅和乘客腰部的较宽的带子，它使乘客与飞机座椅连为一体）"),
]
chat = ChatOpenAI(model="qwen2",max_tokens=3000,temperature=0,max_retries=2).invoke(messages)
print(chat.content)

Finally, thanks again for your help!
