### ISSUE TITLE
qwen2-7b推理无法正常终止，额外输出不相关内容

### ISSUE THREAD

**Issue by AME430** [QwenLM/Qwen2#532]
运行环境：
![image](https://github.com/QwenLM/Qwen2/assets/52948042/407e6b1a-c46a-4bf4-adc9-737cdc41b04a)
![image](https://github.com/QwenLM/Qwen2/assets/52948042/0f014f6c-0e94-4450-bddf-766419d9676a)

使用transformers/vllm启动均会出现该问题
输入问题： 你好
输出如下图所示：
![image](https://github.com/QwenLM/Qwen2/assets/52948042/6a126d69-9662-4f69-b8a6-0bd452b70566)

**Comment by jklj077** [comment]
Hi, please provide code for reproduction. My best guess is that you are using the base model instead of the instruct model. If that's the case, use the instruct model.

**Comment by jklj077** [comment]
@bestzy6 Hi, it is possible that the temperature is too low for this model and you should also adjust the repetition penalty.

**Comment by AME430** [comment]
> Hi, please provide code for reproduction. My best guess is that you are using the base model instead of the instruct model. If that's the case, use the instruct model.

It works. Thank you!
