### ISSUE TITLE
添加rope_scaling后输出结果无法通过参数控制

### ISSUE THREAD

**Issue by xpcc355** [QwenLM/Qwen2#534]
加rope_scaling后，每次调用大模型，返回结果都不一样，temperature、top_p都设置为0.001。去除rope_scaling后输出在几个结果间变化，temperature设置为0貌似正常。
环境: 模型72B-instruct-gptq-int4
vllm0.4.3，torch2.3.0，transformers4.41.2
运行命令：python -m vllm.entrypoints.openai.api_server --model /Qwen2-72B-Instruct-GPTQ-Int4 --served-model-name Qwen2-72B-Instruct-GPTQ-Int4 --trust-remote-code --host 0.0.0.0 --port 8000 --quantization gptq --enforce-eager --dtype float16 --tensor-parallel-size 4

**Comment by hzhwcmhf** [comment]
vllm根据kernel实现引入的误差，greedy解码结果不同是正常的。这些回答里有明显质量很差的吗？

**Comment by xpcc355** [comment]
> vllm根据kernel实现引入的误差，greedy解码结果不同是正常的。这些回答里有明显质量很差的吗？

具体效果还没有对比。再请问一下，在最大128k输入长度下，需要输出固定的答案要怎么做？

**Comment by xpcc355** [comment]
> vllm根据kernel实现引入的误差，greedy解码结果不同是正常的。这些回答里有明显质量很差的吗？

具体效果还没有对比。再请问一下，在最大128k输入长度下，需要输出固定的答案要怎么做？
