### ISSUE TITLE
量化推理细节

### ISSUE THREAD

**Issue by zixi01chen** [QwenLM/Qwen2#535]
请问一下，我看Qwen模型的量化模型效果损失较小，全程都是用Int8推理的吗？还是只是参数Int8，中间反量化为fp16去推理了？

**Comment by jklj077** [comment]
Hi, 

We have provided quantized models in 4 formats, GPTQ, AWQ, GGUF, and MLX, and all of them are weight quantization.

**Comment by zixi01chen** [comment]
Only weight quantization without calculate quantization ?
