### ISSUE TITLE
全量微调的checkpoint推理时generate不停，不返回答案

### ISSUE THREAD

**Issue by ssgg-code** [QwenLM/Qwen2#536]
我用LLAMA FACTORY对qwen2-7b-instruct进行全量微调，用的zero3.
中间的checkpoint保存下来的模型，加载后在一些答案比较长的问题上会卡死，用model.generate不返回正确答案，我测试在max_new_token小于100的时候都能被截断正常返回，但是128以及更长的时候则跑不出正常的答案。
这个问题在最后训练完毕保存的模型上又没有checkpoint那么明显了，不太懂具体是什么原因。

**Comment by jklj077** [comment]
Hi, 

Could you please explain what "128以及更长的时候则跑不出正常的答案" means? Did you meet an error or the did the model generate weird stuff or did the model generate extra stuff even if the proper response had been generated?

**Comment by ssgg-code** [comment]
> Hi,
> 
> Could you please explain what "128以及更长的时候则跑不出正常的答案" means? Did you meet an error or the did the model generate weird stuff or did the model generate extra stuff even if the proper response had been generated?

我使用readme案例的model.generate接口来对话，模型会一直卡在执行model.generate这一块而不会正常返回response。
之后我尝试使用streamer来看，发现response会卡在某一个字之后就不继续输出了，会一直卡死在这。

目前我对比发现deepspeed保存的checkpoint会把config的use_cache改为false， 我把这个修改成true后问题解决。 不过依然不懂为什么false的时候会卡死。

**Comment by jklj077** [comment]
Hi,

`use_cache` specifies whether KV cache is used in inference. If it is set to false, the longer the sequence is, the slower the inference will be. However, even if it is false, the generation will complete eventually. I don't think it could explain the issue you have described, i.e., the generation stucks or cannot properly stop.

Did you happen to observe the GPU util and memory usage when the generation stucked?

**Comment by ssgg-code** [comment]
> Hi,
> 
> `use_cache` specifies whether KV cache is used in inference. If it is set to false, the longer the sequence is, the slower the inference will be. However, even if it is false, the generation will complete eventually. I don't think it could explain the issue you have described, i.e., the generation stucks or cannot properly stop.
> 
> Did you happen to observe the GPU util and memory usage when the generation stucked?
![截图_17182013059410](https://github.com/QwenLM/Qwen2/assets/97082858/5af13753-aa8c-424e-a1d5-d2a01d5a091e)
用streamer可以更好的展示，把use_cache设置为False，当输出到一定的位置的时候，gpu的算力使用为0%，但是这个接口并不会正常结束返回答案，之前尝试过四个小时都没停。

不清楚会不会是我的一些库版本问题
cuda 11.6
transformers 4.41.2
pytorch 1.13.1
accelerate 0.30.1

**Comment by jklj077** [comment]
Hi, it appears that OOM has occurred but the process failed to exit. Upgrade driver and pytorch could help.
