### ISSUE TITLE
比较好奇Qwen的中文token的形式

### ISSUE THREAD

**Issue by Songjw133** [QwenLM/Qwen2#537]
![image](https://github.com/QwenLM/Qwen2/assets/63960777/7bd82c03-47ee-48bb-80ce-c1de357f89a5)
Qwen的中文token在词表中的是这种形式。
比如”你是“编码后的索引是105043，其词表中对应的本体是”"ä½łæĺ¯"。这一步转化是在哪里实现的呢？如何得到汉字与索引直接对应的词表？

**Comment by gg22mm** [comment]
词表这个很蛋疼，牵扯到很多： 正则、分词、utf-8、bytes、unicode ，牵扯到的知识很多~~

**Comment by ailungoal** [comment]
同问，qwen的中文是怎么表达

**Comment by PaperPlaneDeemo** [comment]
`def analyze_string_decode_to_chinese(input_string):
    print("原始字符串:", input_string)

    unicode_points = [ord(char) for char in input_string]
    print("Unicode 码点:", unicode_points)

    decoded_points = [point - 162 if point > 255 else point for point in unicode_points]
    print("调整后的码点:", decoded_points)

    try:
        # 将调整后的码点转换为字节
        byte_array = bytes(decoded_points)
        # 直接使用 UTF-8 解码转换为字符串
        decoded_string = byte_array.decode('utf-8')
        print("解码后的字符串:", decoded_string)
    except Exception as e:
        print("解码失败:", e)

# 使用之前的测试字符串
test_string = 'ä½łæĺ¯'
analyze_string_decode_to_chinese(test_string)`

**Comment by FloatFrank** [comment]
> ```python
> def analyze_string_decode_to_chinese(input_string):
>     print("原始字符串:", input_string)
> 
>     unicode_points = [ord(char) for char in input_string]
>     print("Unicode 码点:", unicode_points)
> 
>     decoded_points = [point - 162 if point > 255 else point for point in unicode_points]
>     print("调整后的码点:", decoded_points)
> 
>     try:
>         # 将调整后的码点转换为字节
>         byte_array = bytes(decoded_points)
>         # 直接使用 UTF-8 解码转换为字符串
>         decoded_string = byte_array.decode('utf-8')
>         print("解码后的字符串:", decoded_string)
>     except Exception as e:
>         print("解码失败:", e)
> 
> # 使用之前的测试字符串
> test_string = 'ä½łæĺ¯'
> analyze_string_decode_to_chinese(test_string)
> ```

大佬，试试“字”这个字呢，åŃĹ，转出来是塗
