### ISSUE TITLE
Extra tokens missing.

### ISSUE THREAD

**Issue by TikoTako** [QwenLM/Qwen2#539]
I checked the 0.5B and 0.5B-Instruct of Qwen2 and there is no extra tokens, i also checked the 7B and there is none too.
Isnt supposed to  have a list of extra tokens from `<|extra_0|>` to `<|extra_204|>`  as stated here `https://github.com/QwenLM/Qwen/blob/main/tokenization_note.md` or that was for the old version only?

**Comment by jklj077** [comment]
Hi,

You are correct that that document applies to Qwen1.0 instead of Qwen2.

Now, it is possible to add special tokens just as any other tokenizers and models in transformers.
