### ISSUE TITLE
Qwen2-1.5B / 7B could not be quantized by autoAWQ

### ISSUE THREAD

**Issue by oyy2000** [QwenLM/Qwen2#546]
I found that Qwen2-1.5B and Qwen2-7B could not be quantized by autoawq and the error is not clear. But instead, Qwen2-0.5B could be quantized successfully. Could someone help me find out the problem?

## My code
from awq import AutoAWQForCausalLM
from transformers import AutoTokenizer
model_path = "Qwen/Qwen2-1.5B"
quant_path = "Qwen2-1.5B-g128"
quant_config = { "zero_point": True, "q_group_size": 128, "w_bit": 4, "version": "GEMM" }

tokenizer = AutoTokenizer.from_pretrained(model_path)
model = AutoAWQForCausalLM.from_pretrained(model_path, device_map="auto", safetensors=True)
model.quantize(tokenizer, quant_config=quant_config)
model.save_quantized(quant_path, safetensors=True, shard_size="4GB")
tokenizer.save_pretrained(quant_path)

## Errors
<img width="1417" alt="image" src="https://github.com/QwenLM/Qwen2/assets/56588848/9390bcce-9d8e-40d1-b822-fd9bdd190d6c">
<img width="1448" alt="image" src="https://github.com/QwenLM/Qwen2/assets/56588848/8ad30949-3c22-4921-be82-b7bb33836deb">
<img width="1436" alt="image" src="https://github.com/QwenLM/Qwen2/assets/56588848/229a8256-03ed-4ed0-94a7-4da3fcf4b3ef">

## My Environment

Package                       Version
----------------------------- --------------
accelerate                    0.30.1
aiohttp                       3.9.5
aiosignal                     1.3.1
annotated-types               0.7.0
anyio                         4.4.0
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
asttokens                     2.4.1
async-lru                     2.0.4
async-timeout                 4.0.3
attrs                         23.2.0
autoawq                       0.2.4
autoawq_kernels               0.0.6
Babel                         2.15.0
beautifulsoup4                4.12.3
bleach                        6.1.0
certifi                       2024.6.2
cffi                          1.16.0
charset-normalizer            3.3.2
cmake                         3.25.0
comm                          0.2.2
datasets                      2.19.2
debugpy                       1.8.1
decorator                     5.1.1
deepspeed                     0.14.2
defusedxml                    0.7.1
dill                          0.3.8
einops                        0.8.0
exceptiongroup                1.2.1
executing                     2.0.1
fastjsonschema                2.19.1
filelock                      3.14.0
fqdn                          1.5.1
frozenlist                    1.4.1
fsspec                        2024.3.1
h11                           0.14.0
hjson                         3.1.0
httpcore                      1.0.5
httpx                         0.27.0
huggingface-hub               0.23.3
idna                          3.7
importlib_metadata            7.1.0
ipykernel                     6.29.4
ipython                       8.18.1
ipywidgets                    8.1.3
isoduration                   20.11.0
jedi                          0.19.1
Jinja2                        3.1.4
json5                         0.9.25
jsonpointer                   2.4
jsonschema                    4.22.0
jsonschema-specifications     2023.12.1
jupyter                       1.0.0
jupyter_client                8.6.2
jupyter-console               6.6.3
jupyter_core                  5.7.2
jupyter-events                0.10.0
jupyter-lsp                   2.2.5
jupyter_server                2.14.1
jupyter_server_terminals      0.5.3
jupyterlab                    4.2.1
jupyterlab_pygments           0.3.0
jupyterlab_server             2.27.2
jupyterlab_widgets            3.0.11
lit                           15.0.7
MarkupSafe                    2.1.5
matplotlib-inline             0.1.7
mistune                       3.0.2
mpmath                        1.3.0
multidict                     6.0.5
multiprocess                  0.70.16
nbclient                      0.10.0
nbconvert                     7.16.4
nbformat                      5.10.4
nest-asyncio                  1.6.0
networkx                      3.2.1
ninja                         1.11.1.1
notebook                      7.2.0
notebook_shim                 0.2.4
numpy                         1.26.4
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.20.5
nvidia-nvjitlink-cu12         12.5.40
nvidia-nvtx-cu12              12.1.105
overrides                     7.7.0
packaging                     24.0
pandas                        2.2.2
pandocfilters                 1.5.1
parso                         0.8.4
peft                          0.11.1
pexpect                       4.9.0
pillow                        10.2.0
pip                           24.0
platformdirs                  4.2.2
prometheus_client             0.20.0
prompt_toolkit                3.0.46
psutil                        5.9.8
ptyprocess                    0.7.0
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
pyarrow                       16.1.0
pyarrow-hotfix                0.6
pycparser                     2.22
pydantic                      2.7.3
pydantic_core                 2.18.4
Pygments                      2.18.0
pynvml                        11.5.0
python-dateutil               2.9.0.post0
python-json-logger            2.0.7
pytz                          2024.1
PyYAML                        6.0.1
pyzmq                         26.0.3
qtconsole                     5.5.2
QtPy                          2.4.1
referencing                   0.35.1
regex                         2024.5.15
requests                      2.32.3
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rpds-py                       0.18.1
safetensors                   0.4.3
scipy                         1.13.1
Send2Trash                    1.8.3
setuptools                    69.5.1
six                           1.16.0
sniffio                       1.3.1
soupsieve                     2.5
stack-data                    0.6.3
sympy                         1.12.1
terminado                     0.18.1
tiktoken                      0.7.0
tinycss2                      1.3.0
tokenizers                    0.19.1
tomli                         2.0.1
torch                         2.0.1+cu118
torchaudio                    2.0.2+cu118
torchvision                   0.15.2+cu118
tornado                       6.4
tqdm                          4.66.4
traitlets                     5.14.3
transformers                  4.40.0
transformers-stream-generator 0.0.4
triton                        2.0.0
types-python-dateutil         2.9.0.20240316
typing_extensions             4.12.1
tzdata                        2024.1
uri-template                  1.3.0
urllib3                       2.2.1
wcwidth                       0.2.13
webcolors                     1.13
webencodings                  0.5.1
websocket-client              1.8.0
wheel                         0.43.0
widgetsnbextension            4.0.11
xxhash                        3.4.1
yarl                          1.9.4
zipp                          3.19.2
zstandard                     0.22.0

**Comment by yangyo** [comment]
You can try using this code: https://github.com/yangyo/AutoAWQ.git

**Comment by yangyo** [comment]
You can try using this code: https://github.com/yangyo/AutoAWQ.git

**Comment by oyy2000** [comment]
Great job! I'd like to ask how do you find these tricky nans out of curiosity.
