### ISSUE TITLE
LOSS

### ISSUE THREAD

**Issue by yangliuIOC** [QwenLM/Qwen2#548]
我看官方给的模板是用的 input==label来进行训练的sft，是否合理？
还是说只需要对 label进行训练即可

**Comment by jklj077** [comment]
For causual language models, the training objective is next token prediction and the label is the shifted input. I am a bit lost in your description of the issue. From what I understand, I think it is similar to <https://github.com/QwenLM/Qwen2/issues/343>. Please refer to the response there.
