### ISSUE TITLE
72b int8 效果比 int4 要差

### ISSUE THREAD

**Issue by tao-githup** [QwenLM/Qwen2#549]
为啥72b 的模型，int8 效果比 int4 还差，是不是写反了

**Comment by jklj077** [comment]
Hi,

If you were refering to the results at <https://qwen.readthedocs.io/en/latest/benchmark/quantization_benchmark.html>, we can confirm that it is correct.

**Comment by hzhwcmhf** [comment]
这个测试集覆盖还不是很全面，有量化的随机因素影响。你可以认为在这几个任务上，int4、int8、bf16效果接近，差距不显著。
