### ISSUE TITLE
如何使用通意思千文去理解文档和图片？

### ISSUE THREAD

**Issue by jungyin** [QwenLM/Qwen2#550]
rt，最近我正在学这个，想知道应该如何传入图片，并让通意千文生成对应的回答，或绘制我需要的图片，还有如何让qwen输出如数学公式图这些较为特殊的图片，如何让通义千文生成pdf这些

**Comment by jklj077** [comment]
Hi,

We must note that Qwen is a casual language model and it does not natively support understanding and generating multi-modal content. Therefore, it cannot achieve the use cases that you have listed on its own. For vision language models that can undstand images, please refer to Qwen-VL. For document understanding, please refer to the examples at Qwen-Agent.

P.S.: The consumer product is 通义千问. While Qwen is a fundamental part of the product, the product is much more complex.
