### ISSUE TITLE
Qwen2-72b-instruct gguf

### ISSUE THREAD

**Issue by ChenTao98** [QwenLM/Qwen2#551]
请问一下Qwen2-72b-instruct的gguf可以提供下载吗。modelscope和huggingface上都没有看到官方发布的gguf文件

**Comment by jklj077** [comment]
https://huggingface.co/Qwen/Qwen2-72B-Instruct-GGUF

**Comment by ChenTao98** [comment]
> https://huggingface.co/Qwen/Qwen2-72B-Instruct-GGUF

抱歉，这个链接点进去404，找不到相关的文件

**Comment by jklj077** [comment]
Hi, let us check; it is indeed not public now.

**Comment by jklj077** [comment]
It's there now!
