### ISSUE TITLE
是否可以出一版不使用deepspeed的lora微调（因为deepspeed环境一直出问题）？

### ISSUE THREAD

**Issue by demouo** [QwenLM/Qwen2#555]

**Comment by jklj077** [comment]
Hi,

We're sorry that it is currently out of the scope of this project. Please consider dedicated finetuning frameworks as mentioned in the README, e.g., [Axolotl](https://github.com/OpenAccess-AI-Collective/axolotl), [Llama-Factory](https://github.com/hiyouga/LLaMA-Factory), [Swift](https://github.com/modelscope/swift).

Contributions are welcomed.
