### ISSUE TITLE
Qwen2_7B模型generate提示Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation

### ISSUE THREAD

**Issue by k1e3v1i4n** [QwenLM/Qwen2#560]
每一次正常内容output完之后，总会输出一段奇怪的文字“If $x$ is a real number and $x^2 = 16$, what is the sum of all possible values of $x$? The equation $x^2 = 16$ has two solutions: $x = 4$ and $x = -4$.。。。。。。。。。。。。。” 然后提示Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation

transformers==4.40.0

input_ = tokenizer.apply_chat_template(messages,tokenize=False,add_generation_prompt=True)

batched_inputs = tokenizer(input_, return_tensors="pt")
input_token_len = batched_inputs.input_ids.shape[1]
batched_inputs = batched_inputs.to(model.device)

gen_kwargs = {
	"temperature": 0.1,
	"num_beams": 1,
	"max_new_tokens": 512
}
batched_outputs = model.generate(**batched_inputs, **gen_kwargs)
llm_output = tokenizer.batch_decode(batched_outputs[:, input_token_len:], skip_special_tokens=True)[0]

**Comment by jklj077** [comment]
Hi,

1. Ignore the warning.
2. Use `-Instruct` models instead. That weird behavior was a hint that you were using the wrong model.

**Comment by wxjttxs** [comment]
我这里也是总会出现 “Setting pad_token_id to eos_token_id:151643 for open-end generation”， 这个问题的原因是啥呀？怎么解决？

**Comment by zhaozhizhuo** [comment]
请问解决了吗

**Comment by Jackmoyu001** [comment]
> Hi,
> 
> 1. Ignore the warning.
> 2. Use  models instead. That weird behavior was a hint that you were using the wrong model.`-Instruct`

我应该使用什么样的模型    不带Instruct 的模型吗
