### ISSUE TITLE
[QA] Number of training tokens

### ISSUE THREAD

**Issue by cslydia** [QwenLM/Qwen2#562]
Hi,

What is the number of training tokens for the base models Qwen 1.5 0.5B, 1.8B, 4B, 7B, 14B, 72B,110B、Qwen2  7B 72B models?

Thanks for the great work!

**Comment by jklj077** [comment]
Hi,

We are not authorized to share the details right now but the rough number is over 3T tokens for Qwen1.5 and over 7T tokens for Qwen2.

**Comment by cslydia** [comment]
Thanks a lot！
