### ISSUE TITLE
Fine tuning for another language

### ISSUE THREAD

**Issue by JJhooww** [QwenLM/Qwen2#564]
Congratulations, this is by far the best 7B model I have used.

It’s fast, follows instructions well, and has a great context window.

I always like to do some extra fine-tuning in my language, which is Portuguese, but this time I’m afraid the model might ‘forget’ the function calls.

Is there any example dataset on how I should organize for function calls?

I have been using Qwen agent.

**Comment by jklj077** [comment]
Hi,

Qwen-Agent uses a customized template for function calls, and I would suggest following the code at <https://github.com/QwenLM/Qwen-Agent/blob/1d52252c06417b899c97d5e2dd82a1c3bcee75ac/qwen_agent/llm/function_calling.py#L87>. You can also use the ReAct template, which is also supported.

 I don't think there is an example dataset though, but the code should be easy to understand.
