### ISSUE TITLE
Qwen2-7B-instruct在HumanEval上的表现达到了79.9，但是在qwen1提示词的情况下，复现只有62，能否公开qwen2的部分测试提示词？

### ISSUE THREAD

**Issue by aa327chenge** [QwenLM/Qwen2#569]
如题

**Comment by ShrimpSlide1** [comment]
同求，希望还能公开后处理代码。我使用qwen1的后处理代码，在没有提示词的情况下，复现只有62.2，希望后处理代码也能公开给我们参考复现一下

**Comment by huybery** [comment]
https://github.com/QwenLM/CodeQwen1.5/tree/main/evaluation/eval_plus

**Comment by aa327chenge** [comment]
我们使用了codeQwen1.5的提示词，和qwen1的前后处理逻辑，在qwen2-7b上面测试发现也只有70.2

**Comment by huybery** [comment]
@aa327chenge Qwen2 uses a review of CodeQwen 1.5, and we have also provided the evaluation toolkit; differences may come from post-processing.

**Comment by SefaZeng** [comment]
> @aa327chenge Qwen2 uses a evaluation of CodeQwen 1.5, and we have also provided the evaluation toolkit; differences may come from post-processing.

请问这里的后处理是指什么？
