### ISSUE TITLE
TypeError: torch.finfo() requires a floating point input type. Use torch.iinfo to handle 'torch.finfo' When using Qwen2-1.5B-Instruct

### ISSUE THREAD

**Issue by LyuLumos** [QwenLM/Qwen2#571]
## Description

I want to fine tune `Qwen2-1.5B-Instruct`using lora, the inputs are text embedding and visual embedding. And the code is shown below.

```py
self.tokenizer = AutoTokenizer.from_pretrained(
    args["model_name"],
    pad_token='<|extra_0|>',
    eos_token='<|endoftext|>', # for qwen
)
self.language_model = AutoModelForCausalLM.from_pretrained(
    args["model_name"],
    device_map="auto",
    pad_token_id=self.tokenizer.pad_token_id,
    torch_dtype=torch.bfloat16,
)
lora_config = LoraConfig(
    task_type="CAUSAL_LM",
    inference_mode=False,
    r=self.args["lora_r"],
    lora_alpha=self.args["lora_alpha"],
    lora_dropout=self.args["lora_dropout"],
    target_modules=self.args["lora_target_modules"],
)

self.language_model = get_peft_model(self.language_model, lora_config)
self.language_model.print_trainable_parameters()
# ....
wrapped_embeds = torch.randint(1, 20000, (1, 1547, 1536), dtype=torch.long).to(self.device)
wrapped_atts = torch.ones(1, 1547, dtype=torch.long).to(self.device)
wrapped_targets_ids = torch.randint(1, 20000, (1, 1547), dtype=torch.long).to(self.device)
outputs = self.language_model(
    inputs_embeds=wrapped_embeds,   # [batch_size, seq_len, hidden_size]
    attention_mask=wrapped_atts,    # [batch_size, seq_len]
    return_dict=True,
    output_hidden_states=True,
    labels=wrapped_targets_ids,     # [batch_size, seq_len]
)
self.tokenizer.padding_side = "left"
```

The error message is 

```
Traceback (most recent call last):
  File "llm.py", line 308, in <module>
    train_on_single_gpu()
  File "llm.py", line 303, in train_on_single_gpu
    trainer.train()
  File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/trainer.py", line 2216, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/trainer.py", line 3238, in training_step
    loss = self.compute_loss(model, inputs)
  File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/trainer.py", line 3264, in compute_loss
    outputs = model(**inputs)
  File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "llm.py", line 217, in forward
    outputs = self.language_model(
  File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/peft/peft_model.py", line 1430, in forward
    return self.base_model(
  File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/peft/tuners/tuners_utils.py", line 179, in forward
    return self.model.forward(*args, **kwargs)
  File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1149, in forward
    outputs = self.model(
  File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1004, in forward
    attention_mask = _prepare_4d_causal_attention_mask(
  File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/modeling_attn_mask_utils.py", line 323, in _prepare_4d_causal_attention_mask
    attention_mask = attn_mask_converter.to_4d(
  File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/modeling_attn_mask_utils.py", line 121, in to_4d
    causal_4d_mask = self._make_causal_mask(
  File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/modeling_attn_mask_utils.py", line 158, in _make_causal_mask
    mask = torch.full((tgt_len, tgt_len), torch.finfo(dtype).min, device=device)
TypeError: torch.finfo() requires a floating point input type. Use torch.iinfo to handle 'torch.finfo'
```

## Environment
```
transformers              4.41.2                   pypi_0    pypi
peft                      0.11.1                   pypi_0    pypi
pytorch                   1.13.1          py3.8_cuda11.6_cudnn8.3.2_0    pytorch
pytorch-cuda              11.6                 h867d48c_1    pytorch
```

I'm wondering why this is happening, shouldn't the attention mask be a 0/1 value.

Thanks to the authors for their excellent work. Thanks to those who helped me answer this question

**Comment by jklj077** [comment]
Hi,

The attention mask is supposed to be a boolean tensor.

**Comment by niceeeeharamiko** [comment]
> ## Description
> I want to fine tune `Qwen2-1.5B-Instruct`using lora, the inputs are text embedding and visual embedding. And the code is shown below.
> 
> ```python
> self.tokenizer = AutoTokenizer.from_pretrained(
>     args["model_name"],
>     pad_token='<|extra_0|>',
>     eos_token='<|endoftext|>', # for qwen
> )
> self.language_model = AutoModelForCausalLM.from_pretrained(
>     args["model_name"],
>     device_map="auto",
>     pad_token_id=self.tokenizer.pad_token_id,
>     torch_dtype=torch.bfloat16,
> )
> lora_config = LoraConfig(
>     task_type="CAUSAL_LM",
>     inference_mode=False,
>     r=self.args["lora_r"],
>     lora_alpha=self.args["lora_alpha"],
>     lora_dropout=self.args["lora_dropout"],
>     target_modules=self.args["lora_target_modules"],
> )
> 
> self.language_model = get_peft_model(self.language_model, lora_config)
> self.language_model.print_trainable_parameters()
> # ....
> wrapped_embeds = torch.randint(1, 20000, (1, 1547, 1536), dtype=torch.long).to(self.device)
> wrapped_atts = torch.ones(1, 1547, dtype=torch.long).to(self.device)
> wrapped_targets_ids = torch.randint(1, 20000, (1, 1547), dtype=torch.long).to(self.device)
> outputs = self.language_model(
>     inputs_embeds=wrapped_embeds,   # [batch_size, seq_len, hidden_size]
>     attention_mask=wrapped_atts,    # [batch_size, seq_len]
>     return_dict=True,
>     output_hidden_states=True,
>     labels=wrapped_targets_ids,     # [batch_size, seq_len]
> )
> self.tokenizer.padding_side = "left"
> ```
> 
> The error message is
> 
> ```
> Traceback (most recent call last):
>   File "llm.py", line 308, in <module>
>     train_on_single_gpu()
>   File "llm.py", line 303, in train_on_single_gpu
>     trainer.train()
>   File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/trainer.py", line 1885, in train
>     return inner_training_loop(
>   File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/trainer.py", line 2216, in _inner_training_loop
>     tr_loss_step = self.training_step(model, inputs)
>   File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/trainer.py", line 3238, in training_step
>     loss = self.compute_loss(model, inputs)
>   File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/trainer.py", line 3264, in compute_loss
>     outputs = model(**inputs)
>   File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "llm.py", line 217, in forward
>     outputs = self.language_model(
>   File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/peft/peft_model.py", line 1430, in forward
>     return self.base_model(
>   File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/peft/tuners/tuners_utils.py", line 179, in forward
>     return self.model.forward(*args, **kwargs)
>   File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1149, in forward
>     outputs = self.model(
>   File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1004, in forward
>     attention_mask = _prepare_4d_causal_attention_mask(
>   File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/modeling_attn_mask_utils.py", line 323, in _prepare_4d_causal_attention_mask
>     attention_mask = attn_mask_converter.to_4d(
>   File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/modeling_attn_mask_utils.py", line 121, in to_4d
>     causal_4d_mask = self._make_causal_mask(
>   File "/root/miniconda3/envs/audio/lib/python3.8/site-packages/transformers/modeling_attn_mask_utils.py", line 158, in _make_causal_mask
>     mask = torch.full((tgt_len, tgt_len), torch.finfo(dtype).min, device=device)
> TypeError: torch.finfo() requires a floating point input type. Use torch.iinfo to handle 'torch.finfo'
> ```
> 
> ## Environment
> ```
> transformers              4.41.2                   pypi_0    pypi
> peft                      0.11.1                   pypi_0    pypi
> pytorch                   1.13.1          py3.8_cuda11.6_cudnn8.3.2_0    pytorch
> pytorch-cuda              11.6                 h867d48c_1    pytorch
> ```
> 
> I'm wondering why this is happening, shouldn't the attention mask be a 0/1 value.
> 
> Thanks to the authors for their excellent work. Thanks to those who helped me answer this question

请问您解决了这个问题吗，我也遇到了同样的问题
