### ISSUE TITLE
docker镜像拉取失败

### ISSUE THREAD

**Issue by wells-Qiang-Chen** [QwenLM/Qwen2#572]
镜像拉不动，有好用的源吗 
docker pull qwenllm/qwen:1.5-cu121
1.5-cu121: Pulling from qwenllm/qwen
96d54c3075c9: Retrying in 1 second
755e535b54a3: Retrying in 1 second
24ff69e0a1e4: Retrying in 1 second
76a627ca5e65: Waiting
35817692a87e: Waiting
84b6a42e847a: Waiting
4639b7cd68e5: Waiting
a7bc10701a5b: Waiting
7d32a9230f8f: Waiting
8c35a1861813: Waiting
e3f63d7242f5: Waiting
afa75cca3a04: Waiting
7f2f3df7d40c: Waiting
effb9636c5d5: Waiting
48327c7f35fb: Waiting
57789402a9b0: Waiting
4f4fb700ef54: Waiting
abb1d69f27ac: Waiting
e0ca71d1a62f: Waiting
27cbf0d1b839: Waiting
e6b25515aa6b: Waiting
ea278ac08796: Waiting
c994b81dcc65: Waiting
649b24b6bec3: Waiting
34dbfe62ee6b: Waiting
error pulling image configuration: download failed after attempts=6: dial tcp 173.252.105.21:443: i/o timeout

**Comment by Forevery1** [comment]
目前docker源不是在国内不能用了么？你可以换个docker源试试，我这边反正之前可以拉的docker镜像目前都拉不了，换成阿里的docker源就好了，所有镜像都可以拉了

**Comment by wells-Qiang-Chen** [comment]
> 目前docker源不是在国内不能用了么？你可以换个docker源试试，我这边反正之前可以拉的docker镜像目前都拉不了，换成阿里的docker源就好了，所有镜像都可以拉了

docker pull qwenllm/qwen:1.5-cu121 我用阿里的源好像也不行，大佬试试看？

**Comment by yangdongdong2000** [comment]
同  换源了用这个也不行docker pull qwenllm/qwen:1.5-cu121

**Comment by Forevery1** [comment]
> > 目前docker源不是在国内不能用了么？你可以换个docker源试试，我这边反正之前可以拉的docker镜像目前都拉不了，换成阿里的docker源就好了，所有镜像都可以拉了
> 
> docker pull qwenllm/qwen:1.5-cu121 我用阿里的源好像也不行，大佬试试看？

我也试了下，确实拉不到，不过肯定的是就是源的问题。看有没有人把镜像传到其他源上，比如阿里官方源

**Comment by JadonZhang** [comment]
确实拉取不了，有什么解决办法吗

**Comment by wells-Qiang-Chen** [comment]
拉取国外源才行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jeremy Sun ***@***.***&gt;
发送时间: 2024年7月29日 10:52
收件人: QwenLM/Qwen2 ***@***.***&gt;
抄送: wells-Qiang-Chen ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [QwenLM/Qwen2] docker镜像拉取失败 (Issue #572)





 
没人管管吗
