### ISSUE TITLE
function call调用出错，The [function_call] is not supported in the message; however, you may be able to use [tool_calls]

### ISSUE THREAD

**Issue by franklucky001** [QwenLM/Qwen2#573]
使用openai api接口demo调用function call的testcase, 在第三次调用qwen_call出错。

# test code
```python
def call_qwen(messages, functions=None):
    print('input:')
    pprint(messages, indent=2)
    if functions:
        response = client.chat.completions.create(model="qwen2-72b-instruct",
                                                  messages=messages,
                                                  functions=functions
                                                  )
    else:
        response = client.chat.completions.create(model="qwen2-72b-instruct",
                                                  messages=messages
                                                  )
    response = response.choices[0].message
    response = response.to_dict()  # fix zh rendering
    print('output:')
    pprint(response, indent=2)
    print()
    return response

def test_2():
    functions = [
        {
            'name_for_human':
                '谷歌搜索',
            'name_for_model':
                'google_search',
            'description_for_model':
                '谷歌搜索是一个通用搜索引擎，可用于访问互联网、查询百科知识、了解时事新闻等。' +
                ' Format the arguments as a JSON object.',
            'parameters': [{
                'name': 'search_query',
                'description': '搜索关键词或短语',
                'required': True,
                'schema': {
                    'type': 'string'
                },
            }],
        },
        {
            'name_for_human':
                '文生图',
            'name_for_model':
                'image_gen',
            'description_for_model':
                '文生图是一个AI绘画（图像生成）服务，输入文本描述，返回根据文本作画得到的图片的URL。' +
                ' Format the arguments as a JSON object.',
            'parameters': [{
                'name': 'prompt',
                'description': '英文关键词，描述了希望图像具有什么内容',
                'required': True,
                'schema': {
                    'type': 'string'
                },
            }],
        },
    ]

    messages = [{'role': 'user', 'content': '（请不要调用工具）\n\n你好'}]
    call_qwen(messages, functions)
    messages.append({
        'role': 'assistant',
        'content': '你好！很高兴见到你。有什么我可以帮忙的吗？'
    }, )

    messages.append({'role': 'user', 'content': '搜索一下谁是周杰伦'})
    call_qwen(messages, functions)
    messages.append({
        'role': 'assistant',
        'content': '我应该使用Google搜索查找相关信息。',
        'function_call': {
            'name': 'google_search',
            'arguments': '{"search_query": "周杰伦"}',
        },
    })

    messages.append({
        'role': 'tool',
        'name': 'google_search',
        'content': 'Jay Chou is a Taiwanese singer.',
    })
    call_qwen(messages, functions)
    messages.append(
        {
            'role': 'assistant',
            'content': '周杰伦（Jay Chou）是一位来自台湾的歌手。',
        }, )

    messages.append({'role': 'user', 'content': '搜索一下他老婆是谁'})
    call_qwen(messages, functions)
    messages.append({
        'role': 'assistant',
        'content': '我应该使用Google搜索查找相关信息。',
        'function_call': {
            'name': 'google_search',
            'arguments': '{"search_query": "周杰伦 老婆"}',
        },
    })

    messages.append({
        'role': 'tool',
        'name': 'google_search',
        'content': 'Hannah Quinlivan'
    })
    call_qwen(messages, functions)
    messages.append(
        {
            'role': 'assistant',
            'content': '周杰伦的老婆是Hannah Quinlivan。',
        }, )

    messages.append({'role': 'user', 'content': '用文生图工具画个可爱的小猫吧，最好是黑猫'})
    call_qwen(messages, functions)
    messages.append({
        'role': 'assistant',
        'content': '我应该使用文生图API来生成一张可爱的小猫图片。',
        'function_call': {
            'name': 'image_gen',
            'arguments': '{"prompt": "cute black cat"}',
        },
    })

    messages.append({
        'role':
            'tool',
        'name':
            'image_gen',
        'content':
            '{"image_url": "https://image.pollinations.ai/prompt/cute%20black%20cat"}',
    })
    call_qwen(messages, functions)
```
# traceback
> ### Test Case 2 - Use Qwen-Style Functions (函数调用，千问格式) ###
input:
[{'content': '（请不要调用工具）\n\n你好', 'role': 'user'}]
output:
{'content': '你好！有什么可以帮助你的吗？', 'role': 'assistant'}

input:
[ {'content': '（请不要调用工具）\n\n你好', 'role': 'user'},
  {'content': '你好！很高兴见到你。有什么我可以帮忙的吗？', 'role': 'assistant'},
  {'content': '搜索一下谁是周杰伦', 'role': 'user'}]
output:
{ 'content': '周杰伦是一位著名的台湾歌手、作曲人和演员，出生于1979年1月18日。他是华语流行音乐界的代表性人物之一，被誉为“流行天王”和“音乐鬼才”。他的歌曲风格多样，涵盖了流行、摇滚、R&B、嘻哈、电子等多种音乐类型。周杰伦在音乐领域取得了巨大的成功，发行了多张畅销专辑，并获得了多项音乐奖项。此外，他还涉足电影和电视剧领域，出演过《头文字D》、《不能说的秘密》等作品。周杰伦在全球范围内拥有庞大的粉丝群体，对华语流行文化产生了深远的影响。',
  'role': 'assistant'}

input:
[ {'content': '（请不要调用工具）\n\n你好', 'role': 'user'},
  {'content': '你好！很高兴见到你。有什么我可以帮忙的吗？', 'role': 'assistant'},
  {'content': '搜索一下谁是周杰伦', 'role': 'user'},
  { 'content': '我应该使用Google搜索查找相关信息。',
    'function_call': { 'arguments': '{"search_query": "周杰伦"}',
                       'name': 'google_search'},
    'role': 'assistant'},
  { 'content': 'Jay Chou is a Taiwanese singer.',
    'name': 'google_search',
    'role': 'tool'}]
Traceback (most recent call last):
  File "E:\workspace\python\langchain-demo\langchain_qwen_demo.py", line 255, in <module>
    test_2()
  File "E:\workspace\python\langchain-demo\langchain_qwen_demo.py", line 129, in test_2
    call_qwen(messages, functions)
  File "E:\workspace\python\langchain-demo\langchain_qwen_demo.py", line 28, in call_qwen
    response = client.chat.completions.create(model="qwen2-72b-instruct",
  File "C:\Users\frank\.pyenv-win-venv\envs\langchain\lib\site-packages\openai\_utils\_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\frank\.pyenv-win-venv\envs\langchain\lib\site-packages\openai\resources\chat\completions.py", line 606, in create
    return self._post(
  File "C:\Users\frank\.pyenv-win-venv\envs\langchain\lib\site-packages\openai\_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "C:\Users\frank\.pyenv-win-venv\envs\langchain\lib\site-packages\openai\_base_client.py", line 921, in request
    return self._request(
  File "C:\Users\frank\.pyenv-win-venv\envs\langchain\lib\site-packages\openai\_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'code': 'invalid_parameter_error', 'param': None, 'message': 'The [function_call] is not supported in the message; however, you may be able to use [tool_calls]', 'type': 'invalid_request_error'}}

**Comment by jklj077** [comment]
Hi,

Please refer to the README on the function call support in the OpenAI compatible APIs in inference frameworks. Also see Qwen-Agent for more information.
