### ISSUE TITLE
qwen2 tokenizer并行处理速度

### ISSUE THREAD

**Issue by qiaojiim** [QwenLM/Qwen2#574]
我希望在多线程中使用qwen2 tokenizer并行处理大量文本，示例代码如下
``` python
from tqdm.contrib.concurrent import thread_map
process_data = thread_map(process, data, max_workers=16)

def process(doc):
    ......
    text=doc['text']
    tmp_content_ids = tokenizer(text).input_ids
   ......
```
但是`max_workers=16`相比`max_workers=1`时，处理速度并没有提升，几乎持平甚至略有下降。
qwen2 tokenizer应该如何并行处理文本，来达到加速的效果呢

**Comment by jklj077** [comment]
Python threads can be slow due to GIL; consider using multiprocessing.
