### ISSUE TITLE
Qwen2-72B-Instruct-GPTQ-Int8模型的量化问题

### ISSUE THREAD

**Issue by Sebastian-Getts** [QwenLM/Qwen2#578]
AutoGPTQ版本：0.7.1
量化精度：8bit
GPU：2XA800
vllm：0.4.0.post1

参考了qwen的[GPTQ量化文档](https://qwen.readthedocs.io/en/latest/quantization/gptq.html)，我之前用AutoGPTQ对`Qwen1.5-72B-Chat`做了8bit的量化，可以成功用vllm部署。
现在我尝试对`Qwen2-72B-Instruct`做同样的量化，使用vllm部署无法正常启动。我发现我量化后模型文件内的config.json与官方GPTQ版本`Qwen2-72B-Instruct-GPTQ-Int8`不同，例如: intermediate_size，我这边量化后的值是29568，而官方提供的GPTQ-Int8版本是29696。

请教下官方的GPTQ-Int8版本是如何量化的，能否指导下如何做GPTQ量化？

**Comment by jklj077** [comment]
Hi, 

The problem is similar to the Qwen1.5-14B: the intermediate size 29568 divided by the group_size 128 is 231, which makes it impossible to deploy on 2, 4, 6, 8 devices (you can do 3 or 7 devices though).

The GPTQ models released by us is made by padding the parameters with zeros, so that its size is divisble by 128 * 8 = 1024.

**Comment by Sebastian-Getts** [comment]
@jklj077 感谢回复~

我尝试了使用3张A800启动量化后的模型，仍然失败了。无法从64和231中取得一个合适的值。
```
ValueError: Total number of attention heads (64) must be divisible by tensor parallel size (3).
```
回复中提到的`padding the parameters with zeros`，我们普通用户要想使用它来让量化后的模型可以多卡部署，是否具备可行性，该如何操作呢？

**Comment by lxb0425** [comment]
大佬 解决了 吗。我也是跟你一样去的问题

**Comment by jklj077** [comment]
After loading the orignal Qwen2-72B model, try the following:
```
import torch
from torch.nn import functional as F

pad_size = 128

sd = model.state_dict()

for i, k in enumerate(sd):
    v = sd[k]
    print(k, i)
    if ('mlp.up_proj.weight' in k) or ('mlp.gate_proj.weight' in k):
        prev_v = F.pad(v.unsqueeze(1), (0, 0, 0, 1, 0, 0)).reshape(29568*2, -1)[:pad_size*2]
        new_v = torch.cat([prev_v, v[pad_size:]], dim=0)
        sd[k] = new_v
    elif 'mlp.down_proj.weight' in k:
        prev_v= F.pad(v.unsqueeze(2), (0, 1)).reshape(8192, 29568*2)[:, :pad_size*2]
        new_v = torch.cat([prev_v, v[:, pad_size:]], dim=1)
        sd[k] = new_v

torch.save(sd, '/path/to/padded_model/pytorch_model.bin')
```

This will save the padding checkpoints to the specified directory. Then copy other files from the original checkpoint to the new directory and modify the intermediate_size in config.json to 29696.

**Comment by Sebastian-Getts** [comment]
@jklj077 谢谢，我对量化前的模型执行后得到了新的权重文件，将`config.json`内的intermediate_size改为了29696。当前模型文件包含：`added_tokens.json  config.json  merges.txt  pytorch_model.bin  special_tokens_map.json  tokenizer_config.json  vocab.json`

现在我发现更新后模型无法再被加载，而且使用vllm部署时会报错，帮忙看看我需要如何调整？

现象1：模型无法加载
```
# 使用AutoGPTQForCausalLM.from_pretrained加载模型，进度卡在这里
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
```

现象2：vllm部署报错
```
  File "/workspace/qsw/vllm/.vllm_0.4/lib/python3.10/site-packages/vllm/worker/worker.py", line 107, in load_model
    self.model_runner.load_model()
  File "/workspace/qsw/vllm/.vllm_0.4/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 95, in load_model
    self.model = get_model(
  File "/workspace/qsw/vllm/.vllm_0.4/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 101, in get_model
    model.load_weights(model_config.model, model_config.download_dir,
  File "/workspace/qsw/vllm/.vllm_0.4/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 370, in load_weights
    param = params_dict[name]
KeyError: 'model.model.embed_tokens.weight'
```

**Comment by jklj077** [comment]
Have you quantize the new model checkpoint?

**Comment by jklj077** [comment]
@hzhwcmhf can you take look at the error? that vllm  error is strange.

**Comment by paxtonlin** [comment]
@jklj077 We have encountered the same problem.    KeyError: 'model.model.embed_tokens.weight'

**Comment by hzhwcmhf** [comment]
> @jklj077 谢谢，我对量化前的模型执行后得到了新的权重文件，将`config.json`内的intermediate_size改为了29696。当前模型文件包含：`added_tokens.json config.json merges.txt pytorch_model.bin special_tokens_map.json tokenizer_config.json vocab.json`
> 
> 现在我发现更新后模型无法再被加载，而且使用vllm部署时会报错，帮忙看看我需要如何调整？
> 
> 现象1：模型无法加载
> 
> ```
> # 使用AutoGPTQForCausalLM.from_pretrained加载模型，进度卡在这里
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
> ```
> 
> 现象2：vllm部署报错
> 
> ```
>   File "/workspace/qsw/vllm/.vllm_0.4/lib/python3.10/site-packages/vllm/worker/worker.py", line 107, in load_model
>     self.model_runner.load_model()
>   File "/workspace/qsw/vllm/.vllm_0.4/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 95, in load_model
>     self.model = get_model(
>   File "/workspace/qsw/vllm/.vllm_0.4/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 101, in get_model
>     model.load_weights(model_config.model, model_config.download_dir,
>   File "/workspace/qsw/vllm/.vllm_0.4/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 370, in load_weights
>     param = params_dict[name]
> KeyError: 'model.model.embed_tokens.weight'
> ```


(1) It is caused by large checkpoint without sharding. You may need at least 300GB CPU memory to load the checkpoint and be patient.

(2) I am not sure where the problem is. Replacing 
``torch.save(sd, '/path/to/padded_model/pytorch_model.bin')``
by
``torch.save({"model." + k: v for k, v in sd.items()}, '/path/to/padded_model/pytorch_model.bin')``
may help.
@Sebastian-Getts @paxtonlin

**Comment by paxtonlin** [comment]
你好，感谢你的邮件，我会尽快查看并回复你的，再次感谢！--林攀学

**Comment by Sebastian-Getts** [comment]
@hzhwcmhf 谢谢回复！我尝试了`torch.save({"model." + k: v for k, v in sd.items()}, '/path/to/padded_model/pytorch_model.bin')`，使用vllm部署还是有一样的报错：`KeyError: 'model.model.model.embed_tokens.weight'`。

我尝试使用*AutoGPTQForCausalLM.from_pretrained*加载了模型，等待了一段时间后控制台打印了下面的信息：
`Some weights of the model checkpoint at /data/model-dev/qwen/Qwen2-72B-Instruct-padding were not used when initializing Qwen2ForCausalLM: ['model.lm_head.weight', 'model.model.embed_tokens.weight', 'model.model.layers.0.input_layernorm.weight', 'model.model.layers.0.mlp.down_proj.weight', 'model.model.layers.0.mlp.gate_proj.weight', 'model.model.layers.0.mlp.up_proj.weight', 'model.model.layers.0.post_attention_layernorm.weight', 'model.model.layers.0.self_attn.k_proj.bias', 'model.model.layers.0.self_attn.k_proj.weight', 'model.model.layers.0.self_attn.o_proj.weight', 'model.model.layers.0.self_attn.q_proj.bias', 'model.model.layers.0.self_attn.q_proj.weight', 'model.model.layers.0.self_attn.v_proj.bias', 'model.model.layers.0.self_attn.v_proj.weight', 'model.model.layers.1.input_layernorm.weight', 'model.model.layers.1.mlp.down_proj.weight', 'model.model.layers.1.mlp.gate_proj.weight', 'model.model.layers.1.mlp.up_proj.weight', 'model.model.layers.1.post_attention_layernorm.weight', 'model.model.layers.1.self_attn.k_proj.bias', 'model.model.layers.1.self_attn.k_proj.weight', 'model.model.layers.1.self_attn.o_proj.weight', 'model.model.layers.1.self_attn.q_proj.bias', 'model.model.layers.1.self_attn.q_proj.weight', 'model.model.layers.1.self_attn.v_proj.bias', 'model.model.layers.1.self_attn.v_proj.weight', 'model.model.layers.10.input_layernorm.weight',
......
,'model.model.layers.9.mlp.down_proj.weight', 'model.model.layers.9.mlp.gate_proj.weight', 'model.model.layers.9.mlp.up_proj.weight', 'model.model.layers.9.post_attention_layernorm.weight', 'model.model.layers.9.self_attn.k_proj.bias', 'model.model.layers.9.self_attn.k_proj.weight', 'model.model.layers.9.self_attn.o_proj.weight', 'model.model.layers.9.self_attn.q_proj.bias', 'model.model.layers.9.self_attn.q_proj.weight', 'model.model.layers.9.self_attn.v_proj.bias', 'model.model.layers.9.self_attn.v_proj.weight', 'model.model.norm.weight']`

感觉上面的信息也给出了vllm部署报错的原因，权重没有用到，需要怎么调整呢

**Comment by Xu-Chen** [comment]
> @hzhwcmhf 谢谢回复！我尝试了`torch.save({"model." + k: v for k, v in sd.items()}, '/path/to/padded_model/pytorch_model.bin')`，使用vllm部署还是有一样的报错：`KeyError: 'model.model.model.embed_tokens.weight'`。
> 
> 我尝试使用_AutoGPTQForCausalLM.from_pretrained_加载了模型，等待了一段时间后控制台打印了下面的信息： `Some weights of the model checkpoint at /data/model-dev/qwen/Qwen2-72B-Instruct-padding were not used when initializing Qwen2ForCausalLM: ['model.lm_head.weight', 'model.model.embed_tokens.weight', 'model.model.layers.0.input_layernorm.weight', 'model.model.layers.0.mlp.down_proj.weight', 'model.model.layers.0.mlp.gate_proj.weight', 'model.model.layers.0.mlp.up_proj.weight', 'model.model.layers.0.post_attention_layernorm.weight', 'model.model.layers.0.self_attn.k_proj.bias', 'model.model.layers.0.self_attn.k_proj.weight', 'model.model.layers.0.self_attn.o_proj.weight', 'model.model.layers.0.self_attn.q_proj.bias', 'model.model.layers.0.self_attn.q_proj.weight', 'model.model.layers.0.self_attn.v_proj.bias', 'model.model.layers.0.self_attn.v_proj.weight', 'model.model.layers.1.input_layernorm.weight', 'model.model.layers.1.mlp.down_proj.weight', 'model.model.layers.1.mlp.gate_proj.weight', 'model.model.layers.1.mlp.up_proj.weight', 'model.model.layers.1.post_attention_layernorm.weight', 'model.model.layers.1.self_attn.k_proj.bias', 'model.model.layers.1.self_attn.k_proj.weight', 'model.model.layers.1.self_attn.o_proj.weight', 'model.model.layers.1.self_attn.q_proj.bias', 'model.model.layers.1.self_attn.q_proj.weight', 'model.model.layers.1.self_attn.v_proj.bias', 'model.model.layers.1.self_attn.v_proj.weight', 'model.model.layers.10.input_layernorm.weight', ...... ,'model.model.layers.9.mlp.down_proj.weight', 'model.model.layers.9.mlp.gate_proj.weight', 'model.model.layers.9.mlp.up_proj.weight', 'model.model.layers.9.post_attention_layernorm.weight', 'model.model.layers.9.self_attn.k_proj.bias', 'model.model.layers.9.self_attn.k_proj.weight', 'model.model.layers.9.self_attn.o_proj.weight', 'model.model.layers.9.self_attn.q_proj.bias', 'model.model.layers.9.self_attn.q_proj.weight', 'model.model.layers.9.self_attn.v_proj.bias', 'model.model.layers.9.self_attn.v_proj.weight', 'model.model.norm.weight']`
> 
> 感觉上面的信息也给出了vllm部署报错的原因，权重没有用到，需要怎么调整呢
可以试试
```python
import json
import os
from collections import OrderedDict
from typing import Dict

import torch
from safetensors import safe_open
from safetensors.torch import save_file
from tqdm import tqdm
from transformers.modeling_utils import (
    SAFE_WEIGHTS_INDEX_NAME,
    SAFE_WEIGHTS_NAME,
    WEIGHTS_INDEX_NAME,
    WEIGHTS_NAME,
    shard_checkpoint,
)

def save_weight(input_dir: str, output_dir: str, shard_size: str, save_safetensors: bool) -> str:
    qwen_state_dict: Dict[str, torch.Tensor] = OrderedDict()
    for filepath in tqdm(os.listdir(input_dir), desc="Load weights"):
        if os.path.isfile(os.path.join(input_dir, filepath)) and filepath.endswith(".safetensors"):
            with safe_open(os.path.join(input_dir, filepath), framework="pt", device="cpu") as f:
                for key in f.keys():
                    qwen_state_dict[key] = f.get_tensor(key)

    llama2_state_dict: Dict[str, torch.Tensor] = OrderedDict()
    torch_dtype = None
    for key, value in tqdm(qwen_state_dict.items(), desc="Convert format"):
        if torch_dtype is None:
            torch_dtype = value.dtype
        shape_list = [int(i) for i in value.shape]
        if len(shape_list) == 2:
            if shape_list[0] == 29568:
                value = torch.concat((value, torch.zeros([128, shape_list[1]], dtype=value.dtype)), dim=0)
            if shape_list[1] == 29568:
                value = torch.cat((value, torch.zeros([shape_list[0], 128], dtype=value.dtype)), dim=1)
        llama2_state_dict[key] = value

    weights_name = SAFE_WEIGHTS_NAME if save_safetensors else WEIGHTS_NAME
    shards, index = shard_checkpoint(llama2_state_dict, max_shard_size=shard_size, weights_name=weights_name)

    for shard_file, shard in tqdm(shards.items(), desc="Save weights"):
        if save_safetensors:
            save_file(shard, os.path.join(output_dir, shard_file), metadata={"format": "pt"})
        else:
            torch.save(shard, os.path.join(output_dir, shard_file))

    if index is None:
        print("Model weights saved in {}".format(os.path.join(output_dir, weights_name)))
    else:
        index_name = SAFE_WEIGHTS_INDEX_NAME if save_safetensors else WEIGHTS_INDEX_NAME
        with open(os.path.join(output_dir, index_name), "w", encoding="utf-8") as f:
            json.dump(index, f, indent=2, sort_keys=True)
        print("Model weights saved in {}".format(output_dir))

    return str(torch_dtype).replace("torch.", "")
```

**Comment by jklj077** [comment]
@Sebastian-Getts 

Hi, I think the problem is that you were using AutoGPTQForCausalLM to load the model in the padding step and it has a different state_dict layout causing the double model prefix. I have updated the script to add notes.

**Comment by jklj077** [comment]
@Xu-Chen 

Hi, may I know if padded that way, the model works after quantization?

**Comment by Xu-Chen** [comment]
> @Xu-Chen 
> 
> Hi, may I know if padded that way, the model works after quantization?

Yes.

**Comment by Sebastian-Getts** [comment]
🎉🎉🎉 成功了！谢谢各位的帮助 ，下面两种方式都可行~

方式一：https://github.com/QwenLM/Qwen2/issues/578#issuecomment-2175206751
方式二：https://github.com/QwenLM/Qwen2/issues/578#issuecomment-2193235546

**Comment by Hukongtao** [comment]
使用padding可以解决量化的问题。但是我这边发现使用原始的fp16的72B模型和使用padding之后的fp16的72B模型的推理结果不能完全一致。   
使用原始的fp16的72B模型推理两次的结果，是一模一样的
![image](https://github.com/user-attachments/assets/0b2da2c3-acf3-4434-89e4-f86bb3c33ddd)  
   
使用padding之后的fp16的72B模型推理两次的结果，也是一模一样的
![image](https://github.com/user-attachments/assets/6fda09ca-9cd7-4dd1-affd-1f283126b70c)

但是可以看到两种权重模型推理的结果在最后的几个token不是完全一致的，请问这是合理的吗？
我的推理代码：
```python

# https://huggingface.co/Qwen/Qwen2-72B-Instruct#quickstart

from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda"  # the device to load the model onto

# 分别用Qwen2-72B-Instruct和padded_model跑下推理，看看结果是否一致
# model_name = "Qwen2-72B-Instruct"
model_name = "./padded_model/"

model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype="auto", device_map="auto")
tokenizer = AutoTokenizer.from_pretrained(model_name)

prompt = "Give me a short introduction to large language model."
messages = [{"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": prompt}]
text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
model_inputs = tokenizer([text], return_tensors="pt").to(device)

generated_ids = model.generate(
    model_inputs.input_ids,
    max_new_tokens=512,
    do_sample=False,
    repetition_penalty=1.0,
    temperature=1.0,
    top_k=50,
    top_p=1.0,
)
generated_ids = [output_ids[len(input_ids) :] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
print(response)

```

**Comment by Hukongtao** [comment]
> 我的推理代码：

@jklj077 大佬 可以帮忙看下吗？padding前后的模型推理结果不能完全对齐，这个是合理的吗？

**Comment by Shuai-Xie** [comment]
> > Try the following:
> > ```
> > import torch
> > from torch.nn import functional as F
> > 
> > from transformers import AutoModelForCausalLM
> > 
> > # must use AutoModelForCausalLM
> > model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2-72B-Instruct", torch_dtype="auto")
> > 
> > # this size is Qwen2-72B only
> > pad_size = 128 
> > 
> > sd = model.state_dict()
> > 
> > for i, k in enumerate(sd):
> >     v = sd[k]
> >     print(k, i)
> >     # interleaving the padded zeros
> >     if ('mlp.up_proj.weight' in k) or ('mlp.gate_proj.weight' in k):
> >         prev_v = F.pad(v.unsqueeze(1), (0, 0, 0, 1, 0, 0)).reshape(29568*2, -1)[:pad_size*2]
> >         new_v = torch.cat([prev_v, v[pad_size:]], dim=0)
> >         sd[k] = new_v
> >     elif 'mlp.down_proj.weight' in k:
> >         prev_v= F.pad(v.unsqueeze(2), (0, 1)).reshape(8192, 29568*2)[:, :pad_size*2]
> >         new_v = torch.cat([prev_v, v[:, pad_size:]], dim=1)
> >         sd[k] = new_v
> > 
> > # this is a very large file; make sure your RAM is enough to load the model
> > torch.save(sd, '/path/to/padded_model/pytorch_model.bin')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This will save the padded checkpoint to the specified directory. Then copy other files from the original checkpoint to the new directory and modify the intermediate_size in config.json to 29696.
> 
> 你好，大佬，我看您代码，您是对权重中的一些参数的前128个维度，进行了交叉式的padded，想跟您确认一下，这样pad的依据或者好处是什么。可以帮忙解答一下么。

尝试回复一下：

如果只是为了 FP16 能在 vllm 推理，那么 Pad 的 0 在哪里都不影响，可以是 29568 这一维向左向右连续延伸 128；

如果是为了 FP16 之后，再用 AWQ 校准，那么基于一个已有的 group 去交叉插值 0 就合理了，因为这样至少有两个好处：
1. int4 zeros, scales 这些参数计算不会 divide_zero；
2. 将原来的 128个数均分到2个 group 后，分担了量化的总数，相当于两个 group 64 的量化，这部分精度也会更高一些；这种 tricks 甚至可用于量化 error 太大的 group_wise 量化。

作图表示一下
```bash
# 原始 tensor，假设 group_size = 4
[ a, b, c, d ]

# 交叉式 padded 扩展出来一个组
[ a, 0, b, 0, c, 0, d, 0 ]
```

**Comment by paxtonlin** [comment]
你好，感谢你的邮件，我会尽快查看并回复你的，再次感谢！--林攀学

**Comment by ArlanCooper** [comment]
> 🎉🎉🎉 成功了！谢谢各位的帮助 ，下面两种方式都可行~
> 
> 方式一：[#578 (comment)](https://github.com/QwenLM/Qwen2.5/issues/578#issuecomment-2175206751) 方式二：[#578 (comment)](https://github.com/QwenLM/Qwen2.5/issues/578#issuecomment-2193235546)

我还是报错，按照第一种方式，padding之后，运行在两个gpu上，会报错：
```
File ~/work/conda/envs/qwen2/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py:199, in <listcomp>(.0)
    195 driver_worker_output = driver_worker_method(*args, **kwargs)
    197 # Get the results of the workers.
    198 return [driver_worker_output
--> 199         ] + [output.get() for output in worker_outputs]

File ~/work/conda/envs/qwen2/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py:54, in ResultFuture.get(self)
     52 assert self.result is not None
     53 if self.result.exception is not None:
---> 54     raise self.result.exception
     55 return self.result.value

RuntimeError: start (1856) + length (1856) exceeds dimension size (3696).

```

**Comment by paxtonlin** [comment]
你好，感谢你的邮件，我会尽快查看并回复你的，再次感谢！--林攀学

**Comment by munian08** [comment]
> Try the following:
> 
> ```
> import torch
> from torch.nn import functional as F
> 
> from transformers import AutoModelForCausalLM
> 
> # must use AutoModelForCausalLM
> model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen2-72B-Instruct", torch_dtype="auto")
> 
> # this size is Qwen2-72B only
> pad_size = 128 
> 
> sd = model.state_dict()
> 
> for i, k in enumerate(sd):
>     v = sd[k]
>     print(k, i)
>     # interleaving the padded zeros
>     if ('mlp.up_proj.weight' in k) or ('mlp.gate_proj.weight' in k):
>         prev_v = F.pad(v.unsqueeze(1), (0, 0, 0, 1, 0, 0)).reshape(29568*2, -1)[:pad_size*2]
>         new_v = torch.cat([prev_v, v[pad_size:]], dim=0)
>         sd[k] = new_v
>     elif 'mlp.down_proj.weight' in k:
>         prev_v= F.pad(v.unsqueeze(2), (0, 1)).reshape(8192, 29568*2)[:, :pad_size*2]
>         new_v = torch.cat([prev_v, v[:, pad_size:]], dim=1)
>         sd[k] = new_v
> 
> # this is a very large file; make sure your RAM is enough to load the model
> torch.save(sd, '/path/to/padded_model/pytorch_model.bin')
> ```
> 
> This will save the padded checkpoint to the specified directory. Then copy other files from the original checkpoint to the new directory and modify the intermediate_size in config.json to 29696.

请问想要对72B模型运行这个代码需要多少资源，我在L20(48G）*4上对qwen2-vl-72B运行会报错oom

**Comment by paxtonlin** [comment]
你好，感谢你的邮件，我会尽快查看并回复你的，再次感谢！--林攀学
