### ISSUE TITLE
没有 get_num_tokens_from_messages() 

### ISSUE THREAD

**Issue by sugar5727** [QwenLM/Qwen2#579]
使用 fastchat 部署 Qwen2-7B-instruct 模型并使用 openai_api 调用。
在使用langchain.memory.ConversationSummaryBufferMemory时，
代码报错
``` errror
NotImplementedError: get_num_tokens_from_messages() is not presently implemented for model cl100k_base.See https://github.com/openai/openai-python/blob/main/chatml.md for information on how messages are converted to tokens.
```
是否有其他方法用于计算对话所用 token 数量。

**Comment by jklj077** [comment]
Hi, 

That is a method provided by langchain and please seek help from them.

I'm unfamilar with how langchain handles the messages, but in general, you can use the tokenizer shown in the readme to get the number of tokens.

**Comment by lhs0627** [comment]
请问你解决这个问题了吗
