### ISSUE TITLE
qwen2-72b-instruct-gptq-int4显存问题

### ISSUE THREAD

**Issue by ChenTao98** [QwenLM/Qwen2#603]
请问一下，官方benchmark说，2张a100的80G，vllm推理qwen2-72b-instruct-gptq-int4输入长度可以到128k，可是我这里4张a100 40G，输入长度到2w多，显存就要满了。这是什么情况呢。
启动参数python -m vllm.entrypoints.openai.api_server  --quantization gptq --tensor-parallel-size 4 --enforce-eager

**Comment by JoeFee2024** [comment]
--tensor-parallel-size 4  的原因？

**Comment by jklj077** [comment]
Hi, 

To be clear, vllm will preallocate the GPU memory for the paged attention, the precent of which is controled by the `--gpu-memory-utilization` argument. It has a default value of 0.9, that is, 90% of the GPU memory is preallocated. There is no way to tell how much it has actually used at present. 

If the maximum sequence length is too large for your setup, an error will be raised at the beginning. If you have set the length as in the modelcard and can start the service, you are fine.

**Comment by ChenTao98** [comment]
> --tensor-parallel-size 4 的原因？

tp应该是用n张卡就要设置成n吧

**Comment by ChenTao98** [comment]
> Hi,
> 
> To be clear, vllm will preallocate the GPU memory for the paged attention, the precent of which is controled by the `--gpu-memory-utilization` argument. It has a default value of 0.9, that is, 90% of the GPU memory is preallocated. There is no way to tell how much it has actually used at present.
> 
> If the maximum sequence length is too large for your setup, an error will be raised at the beginning. If you have set the length as in the modelcard and can start the service, you are fine.

我知道预分配的，预分配默认0.9。在达到一定长度之后，使用的显存还会超过0.9。
有点好奇，在[效率评估](https://qwen.readthedocs.io/zh-cn/latest/benchmark/speed_benchmark.html)中给出的72b-gptq-int4的测试中，默认设置max-model-len为32768，是怎么测试出输入长度超过32768的速度的。另外在vllm中，启动服务的时候，最大长度指定了为L，请求api的时候，不就token不允许超过L了吗。

**Comment by jklj077** [comment]
For sequences over 32K, please read the model card of the related models, especially the part related to rope scaling.

**Comment by HalcyonLiang** [comment]
> For sequences over 32K, please read the model card of the related models, especially the part related to rope scaling.

qwen2-72B-chat 用4张A800，max_model_len=5000，就开始OOM了，vllm0.4.3, gpu-memory-utilization=0.8
看GPU监控，第0卡明显不是0.8的占用，明显比其他3张卡多很多，所以第 0卡跑着跑着就OOM了，这个正常吗？

**Comment by jklj077** [comment]
@HalcyonLiang The CUDA graph can take up 1~3GB in extra if `--enforce-eager` is not set.

**Comment by HalcyonLiang** [comment]
> @HalcyonLiang The CUDA graph can take up 1~3GB in extra if `--enforce-eager` is not set.

What we observed is that the memory usage of GPU 0 is about 10G higher than that of other GPUs when using gpu-memory-utilization=0.8
And 4*A800 gpus shouldn’t be unable to support Qwen2-72B-chat for generate;

**Comment by jklj077** [comment]
@HalcyonLiang Hi, based on your description, I don't think it is related to Qwen2. Please check if you have met the same issue with other models and report to vllm if that's the case.
