### ISSUE TITLE
When running the `cli_demo` file, how can I resolve the `_queue.Empty` issue?

### ISSUE THREAD

**Issue by wulixianming** [QwenLM/Qwen2#657]
![1718598083448](https://github.com/QwenLM/Qwen2/assets/105635825/911e4328-5134-45b3-ad27-6bb0d9e06019)

**Comment by jklj077** [comment]
Hi, I don't think the provided screenshot shows the full error logs. Could you check if it is similar to <https://github.com/QwenLM/Qwen2/issues/331>?

**Comment by wulixianming** [comment]
It's something like #331, it's an issue about environment incompatibility or error, I solved it today when I reinstalled the environment, but when I ran cli_demo, this issue appeared again No module named 'tokenizers.tokenizers', and there is no problem when I ran the web_demo file, the exact reason  I don't know why.

**Comment by jklj077** [comment]
Please provide full logs containing the errors.

**Comment by daxian-lh** [comment]
![屏幕截图 2024-06-21 111429](https://github.com/QwenLM/Qwen2/assets/68174048/2a6adb53-5fa3-4df6-bf90-8db82c3dfbaa)

**Comment by jklj077** [comment]
@daxian-lh 
1. check if you can run the demo code in README
2. export CUDA_LAUNCH_BLOCKING=1 before running the cli_demo.py and show the errors
3. report the driver version and the pytorch cuda version
