### ISSUE TITLE
能否提供一个batch infer的示例

### ISSUE THREAD

**Issue by DongChenwei2000** [QwenLM/Qwen2#659]
相比于qwen，qwen2的文档中似乎缺少了进行batch infer的示例，能否提供一下呢？

**Comment by jklj077** [comment]
Hi,

Qwen2 is quite different Qwen1.0. You can conduct batch inference just as you would normally do with models in `transformers`. I think that it is general question on how to use the `transformers` package and there are plenty materials you could find online. If you are unfamilar with `transformers`, it has very good documentation on its site.
