### ISSUE TITLE
2卡用vllm跑qwen2无回复

### ISSUE THREAD

**Issue by YanXingyu1998** [QwenLM/Qwen2#661]

**Comment by jklj077** [comment]
I have to say this is textbook level how **not** to open issues on GitHub...

- What versions of the vllm, pytorch, cuda, driver were you using?
- What models were you using?
- When did it happen and how did it happen? Can it be reproduced reliably and how can it be reproduced?

**Comment by jklj077** [comment]
I see that you have opened an issue to vllm with much more information. Closed for now; feel free to reopen if we need to take action.
