### ISSUE TITLE
为什么qwen2-7B的max_position_embedding和qwen2-7B-instruct的不同

### ISSUE THREAD

**Issue by wqh17101** [QwenLM/Qwen2#663]
qwen2-7B
![image](https://github.com/QwenLM/Qwen2/assets/26429138/a1dd2aaf-2e26-445b-98f7-4c843b88bb5d)
qwen2-7B-instruct
![image](https://github.com/QwenLM/Qwen2/assets/26429138/99657ec2-4380-42a0-80c3-26bf43573bc0)

为什么qwen2-7B的max_position_embedding和qwen2-7B-instruct的不同

**Comment by jklj077** [comment]
Hi, please read the model card for the instruct model on how to extend sequence length and they are set that way delibrately to prevent misuse.

**Comment by wqh17101** [comment]
@jklj077 Do you mean that they are using two different ways to support 128K long seq length?
For qwen2-7B, it uses a static rope to support 128K.
For qwen2-7B-instruct, it uses YaRNScalingRotaryEmbedding to support 128K.
