### ISSUE TITLE
能提供官方的多轮对话的推理代码吗？

### ISSUE THREAD

**Issue by huxian0402** [QwenLM/Qwen2#664]
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "Qwen/Qwen2-7B-Instruct"
device = "cuda" # the device to load the model onto

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype="auto",
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained(model_name)

prompt = "Give me a short introduction to large language model."
messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(device)

generated_ids = model.generate(
    **model_inputs,
    max_new_tokens=512
)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
@hzhwcmhf @yijia2413 @Michaelvll @osanseviero 文档只给了单轮对话的推理代码，能提供多轮对话的推理代码吗？

**Comment by jklj077** [comment]
Hi,

I think that it is general question on how to use the `transformers` package and there are plenty materials you could find online. If you are unfamilar with `transformers`, it has very good documentation on its site. For example, take a look at <https://huggingface.co/docs/transformers/chat_templating>.

In short, just modify the `messages` variable and append the response as `{"role": "assistant", "content": response}` and then append the new user query/prompt.
