### ISSUE TITLE
量化后启动启动报错

### ISSUE THREAD

**Issue by lxb0425** [QwenLM/Qwen2#665]
swift lora微调了qwen2-72b-instruct，界面导出量化4位gptq，使用vllm单张卡启动成功，问答也ok，但是上下文长度太少
加了两张a100，同时增加了 rope_scalin配置，启动报错如下
![image](https://github.com/QwenLM/Qwen2/assets/50564015/081771a1-c3c7-4f77-b101-4975cfc2e0fd)

**Comment by jklj077** [comment]
Hi, how many cards were you using? Was it 3? What was the group size used in quantization?

The intermediate size has to be divisible by the group size multiplied by the tensor parallel size/number of cards. Otherwise, it won't run.

**Comment by lxb0425** [comment]
两张卡启动的

**Comment by lxb0425** [comment]
我现在改用3张卡 也报错啊
![image](https://github.com/QwenLM/Qwen2/assets/50564015/aebbd58e-1be9-4fc9-933e-fd1aa6bbf203)
