### ISSUE TITLE
按照快速开始指引，但是出现了矩阵不兼容的情况，初步怀疑是torch版本问题，请各位专家指导

### ISSUE THREAD

**Issue by GromZhang** [QwenLM/Qwen2#672]
如标题，我在huggingface上，下载了Qwen2-1.5B-Instruct的模型，并放在本地目录，按照快速指引，编写推理代码进行推理。但是出现异常。

**Comment by GromZhang** [comment]
我的代码只调整了model_name参数
![image](https://github.com/QwenLM/Qwen2/assets/23513264/b3e88bbe-0e55-477a-a4bf-1bf499ccee99)

**Comment by GromZhang** [comment]
我的显卡情况如下：
![image](https://github.com/QwenLM/Qwen2/assets/23513264/9780d8df-d101-4ca3-b528-5c0046d9bdd3)

**Comment by GromZhang** [comment]
错误信息如下：
![image](https://github.com/QwenLM/Qwen2/assets/23513264/ff6585bc-5624-4d2d-bc65-7a1dccfdad28)

**Comment by GromZhang** [comment]
因为在[手册](https://qwen.readthedocs.io/zh-cn/latest/inference/chat.html)中，我并没有找到比较严谨的依赖说明，所以如果各位老师能指引我一下，找到我当下服务器适配的依赖，还请发我一个链接地址。

**Comment by 1994** [comment]
cuda12.4 看起来太新了，尝试降级到12.1 或者安装nightly版本的pytorch：

> pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124

<img width="863" alt="image" src="https://github.com/QwenLM/Qwen2/assets/3808487/c5503f47-6077-418b-a5bb-0688d70464b1">

**Comment by xinyaofan** [comment]
我也没办法运行首页的code AttributeError: 'Qwen2ForCausalLM' object has no attribute 'max_seq_length'

**Comment by GromZhang** [comment]
> cuda12.4 看起来太新了，尝试降级到12.1 或者安装nightly版本的pytorch：
> 
> > pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124
> 
> <img alt="image" width="863" src="https://private-user-images.githubusercontent.com/3808487/340682196-c5503f47-6077-418b-a5bb-0688d70464b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NjAxNjYsIm5iZiI6MTcxODc1OTg2NiwicGF0aCI6Ii8zODA4NDg3LzM0MDY4MjE5Ni1jNTUwM2Y0Ny02MDc3LTQxOGItYTViYi0wNjg4ZDcwNDY0YjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMDExNzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDBlNWMzYzViMWIxYWU1MjhlZjA1ZDhjYWU0M2Y0MWE1NGY0MTkwMGZjZmFmMmUxNDRjMjNiOWE4Mzk3MjkxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c6NDqYMXatoGqB-Cf2gICQY1qoYfnD4AU9ypT-uivWo">

按照您说的方法更新了nightly，出现了如下异常，稍后我试一下降级cuda到12.1
![image](https://github.com/QwenLM/Qwen2/assets/23513264/084f5909-eaf6-4105-8b9b-596b2e88a8b1)
这样您看是不是可行的解决思路
![image](https://github.com/QwenLM/Qwen2/assets/23513264/016c0288-a75b-484c-b0d7-6f285f5d53d1)

**Comment by GromZhang** [comment]
更新cuda-toolkit至12.1
并更新torch等到适配版本，出现如下异常
![image](https://github.com/QwenLM/Qwen2/assets/23513264/dbccb461-38a0-4231-8ebf-80b2fee1ab29)

**Comment by GromZhang** [comment]
> 我的显卡情况如下： ![image](https://private-user-images.githubusercontent.com/23513264/340637662-9780d8df-d101-4ca3-b528-5c0046d9bdd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODQwNzYsIm5iZiI6MTcxODc4Mzc3NiwicGF0aCI6Ii8yMzUxMzI2NC8zNDA2Mzc2NjItOTc4MGQ4ZGYtZDEwMS00Y2EzLWI1MjgtNWMwMDQ2ZDliZGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA3NTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlZjI4NWZiYzA0MDc3ZmYyMTIyNDJhOWYyMzFhNTFlNjc3NDkyODkwNzEyNGUxZmU3Njk4ZTRkYWQ0YTM5M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EfIr-sg-OPnPw1gpGDYpb1eV81pPQfIqB4adshdzODQ)

driver的版本没有改变，只是更新cuda toolkit 到12.1

**Comment by 1994** [comment]
> 更新cuda-toolkit至12.1 并更新torch等到适配版本，出现如下异常 ![image](https://private-user-images.githubusercontent.com/23513264/340980166-dbccb461-38a0-4231-8ebf-80b2fee1ab29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODYwMjAsIm5iZiI6MTcxODc4NTcyMCwicGF0aCI6Ii8yMzUxMzI2NC8zNDA5ODAxNjYtZGJjY2I0NjEtMzhhMC00MjMxLThlYmYtODBiMmZlZTFhYjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA4Mjg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZjZjYWRiZWUxZDBkNjc0MDA3MjJmODI5ZWFkMmNjNTRkZmI0MmMxNjY5ZDliMzQ0ZGUwOTgwOTJhMWY2OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TOsSy52cF6yAgCStbP6kR0iLCIv9tGM2Su463ecTL_I)

cuda 异步操作失败了，添加CUDA_LAUNCH_BLOCKING=1 python  xxxx  追踪下当前出错的堆栈

**Comment by GromZhang** [comment]
> > 更新cuda-toolkit至12.1 并更新torch等到适配版本，出现如下异常 ![image](https://private-user-images.githubusercontent.com/23513264/340980166-dbccb461-38a0-4231-8ebf-80b2fee1ab29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODYwMjAsIm5iZiI6MTcxODc4NTcyMCwicGF0aCI6Ii8yMzUxMzI2NC8zNDA5ODAxNjYtZGJjY2I0NjEtMzhhMC00MjMxLThlYmYtODBiMmZlZTFhYjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA4Mjg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZjZjYWRiZWUxZDBkNjc0MDA3MjJmODI5ZWFkMmNjNTRkZmI0MmMxNjY5ZDliMzQ0ZGUwOTgwOTJhMWY2OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TOsSy52cF6yAgCStbP6kR0iLCIv9tGM2Su463ecTL_I)
> 
> cuda 异步操作失败了，添加CUDA_LAUNCH_BLOCKING=1 python xxxx 追踪下当前出错的堆栈

老师您好，很奇怪，这个问题没有再复现，反而执行时，异常日志重新变成了昨天的。目前我只更新了cuda-toolkit，driver的版本依然是昨天的那个550的，我觉得我不必要更新driver到530吧。
![image](https://github.com/QwenLM/Qwen2/assets/23513264/0eb9a302-d817-4b87-ad54-8abbd0d89ea0)

**Comment by 1994** [comment]
> > > 更新cuda-toolkit至12.1 并更新torch等到适配版本，出现如下异常 ![image](https://private-user-images.githubusercontent.com/23513264/340980166-dbccb461-38a0-4231-8ebf-80b2fee1ab29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODYwMjAsIm5iZiI6MTcxODc4NTcyMCwicGF0aCI6Ii8yMzUxMzI2NC8zNDA5ODAxNjYtZGJjY2I0NjEtMzhhMC00MjMxLThlYmYtODBiMmZlZTFhYjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA4Mjg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZjZjYWRiZWUxZDBkNjc0MDA3MjJmODI5ZWFkMmNjNTRkZmI0MmMxNjY5ZDliMzQ0ZGUwOTgwOTJhMWY2OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TOsSy52cF6yAgCStbP6kR0iLCIv9tGM2Su463ecTL_I)
> > 
> > 
> > cuda 异步操作失败了，添加CUDA_LAUNCH_BLOCKING=1 python xxxx 追踪下当前出错的堆栈
> 
> 老师您好，很奇怪，这个问题没有再复现，反而执行时，异常日志重新变成了昨天的。目前我只更新了cuda-toolkit，driver的版本依然是昨天的那个550的，我觉得我不必要更新driver到530吧。 ![image](https://private-user-images.githubusercontent.com/23513264/340995903-0eb9a302-d817-4b87-ad54-8abbd0d89ea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODcyODIsIm5iZiI6MTcxODc4Njk4MiwicGF0aCI6Ii8yMzUxMzI2NC8zNDA5OTU5MDMtMGViOWEzMDItZDgxNy00Yjg3LWFkNTQtOGFiYmQwZDg5ZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA4NDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNTQ5NTQ5ZDVjMmM0MjYwMjVmNTE1YTAxMWFmMWYyNmI1ZjUwN2MxN2E2MTk3YmU0MjY1YTRjZGVmNTIzMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3lcB3c_9rSSeF7e0sQUwLAsv0OtN7CMeFiUUN5i7KaY)
> 
> 我还做了以下看似无意义的验证。 ![image](https://private-user-images.githubusercontent.com/23513264/340996906-c252d91e-42f3-4c08-b5f6-c87904deeab1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODcyODIsIm5iZiI6MTcxODc4Njk4MiwicGF0aCI6Ii8yMzUxMzI2NC8zNDA5OTY5MDYtYzI1MmQ5MWUtNDJmMy00YzA4LWI1ZjYtYzg3OTA0ZGVlYWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA4NDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYTg5Nzg4OTk2Nzg4NTYxNDAzYzljMjU1MmNjYmFhYjM5YmRkOWZmMDk0ZDg5MDEyYmY4YTQzMjQ5Nzg4NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UjAAN18-0qkgXyjqgg0ni5aKcwP_vkbqfJ8BIDPsJSU)

看下来感觉是个环境兼容性问题，可以参考pytorch docker cuda 12.1 的环境列表，逐一检查下。或者直接用这docker试试
https://hub.docker.com/layers/pytorch/pytorch/2.3.1-cuda12.1-cudnn8-devel/images/sha256-a22a1fca37f8361c8a1e859cd6eb6bd9d1fb384f9c0dcb2cfc691a178eb03d17?context=explore

**Comment by GromZhang** [comment]
> > > > 更新cuda-toolkit至12.1 并更新torch等到适配版本，出现如下异常 ![image](https://private-user-images.githubusercontent.com/23513264/340980166-dbccb461-38a0-4231-8ebf-80b2fee1ab29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODYwMjAsIm5iZiI6MTcxODc4NTcyMCwicGF0aCI6Ii8yMzUxMzI2NC8zNDA5ODAxNjYtZGJjY2I0NjEtMzhhMC00MjMxLThlYmYtODBiMmZlZTFhYjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA4Mjg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZjZjYWRiZWUxZDBkNjc0MDA3MjJmODI5ZWFkMmNjNTRkZmI0MmMxNjY5ZDliMzQ0ZGUwOTgwOTJhMWY2OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TOsSy52cF6yAgCStbP6kR0iLCIv9tGM2Su463ecTL_I)
> > > 
> > > 
> > > cuda 异步操作失败了，添加CUDA_LAUNCH_BLOCKING=1 python xxxx 追踪下当前出错的堆栈
> > 
> > 
> > 老师您好，很奇怪，这个问题没有再复现，反而执行时，异常日志重新变成了昨天的。目前我只更新了cuda-toolkit，driver的版本依然是昨天的那个550的，我觉得我不必要更新driver到530吧。 ![image](https://private-user-images.githubusercontent.com/23513264/340995903-0eb9a302-d817-4b87-ad54-8abbd0d89ea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODcyODIsIm5iZiI6MTcxODc4Njk4MiwicGF0aCI6Ii8yMzUxMzI2NC8zNDA5OTU5MDMtMGViOWEzMDItZDgxNy00Yjg3LWFkNTQtOGFiYmQwZDg5ZWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA4NDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNTQ5NTQ5ZDVjMmM0MjYwMjVmNTE1YTAxMWFmMWYyNmI1ZjUwN2MxN2E2MTk3YmU0MjY1YTRjZGVmNTIzMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3lcB3c_9rSSeF7e0sQUwLAsv0OtN7CMeFiUUN5i7KaY)
> > 我还做了以下看似无意义的验证。 ![image](https://private-user-images.githubusercontent.com/23513264/340996906-c252d91e-42f3-4c08-b5f6-c87904deeab1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODcyODIsIm5iZiI6MTcxODc4Njk4MiwicGF0aCI6Ii8yMzUxMzI2NC8zNDA5OTY5MDYtYzI1MmQ5MWUtNDJmMy00YzA4LWI1ZjYtYzg3OTA0ZGVlYWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA4NDk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjYTg5Nzg4OTk2Nzg4NTYxNDAzYzljMjU1MmNjYmFhYjM5YmRkOWZmMDk0ZDg5MDEyYmY4YTQzMjQ5Nzg4NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UjAAN18-0qkgXyjqgg0ni5aKcwP_vkbqfJ8BIDPsJSU)
> 
> 看下来感觉是个环境兼容性问题，可以参考pytorch docker cuda 12.1 的环境列表，逐一检查下。或者直接用这docker试试 https://hub.docker.com/layers/pytorch/pytorch/2.3.1-cuda12.1-cudnn8-devel/images/sha256-a22a1fca37f8361c8a1e859cd6eb6bd9d1fb384f9c0dcb2cfc691a178eb03d17?context=explore

最终我还是选择了使用vLLM的镜像运行了推理的代码。感谢大佬的支持。但是在进行多卡推理的时候出现了nccl通信的问题，不知道大佬能否给些建议。
[nohup.log](https://github.com/user-attachments/files/15910921/nohup.log)

**Comment by GromZhang** [comment]
最终使用vllm的docker镜像完成了推理。
