### ISSUE TITLE
相同输入下，attn_implementation=sdpa和flash_attention_v2这两种加载方式下hidden_states有细微diff

### ISSUE THREAD

**Issue by xiaohuicomeon** [QwenLM/Qwen2#674]
非常感谢各位大佬的工作。
我在本地测试qwen2-7B的时候发现一个现象如题，按道理不同attn方式下的计算结果应该一致才对。
不同layer的hidden_states数值差异最大能到1.0，越接近lm_head的层误差越大。
不同layer的输出下，前10个step的hidden_states是一致的，step>10之后会出现差异。

环境变量:
transformer=4.38.2
torch=2.3.0post1
flash-attn=2.5.8

脚本如下: 
```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig

path = "path to Qwen2-7B"
model = AutoModelForCausalLM.from_pretrained(path, attn_implementation='flash_attention_2').to(dtype=torch.float32).cuda()
model.config.use_cache = False

model2 = AutoModelForCausalLM.from_pretrained(path, attn_implementation='sdpa').to(dtype=torch.float32).cuda()
model2.config.use_cache = False

tokenizer = AutoTokenizer.from_pretrained(path)

text = [
    "中华人民共和国成立于1949年",
    # "根据中国营养膳食均衡标准来看"
]
data = tokenizer(text, return_tensors='pt', padding='longest')
input_ids = data.input_ids.cuda()
attn_mask = data.attention_mask.cuda()

import ipdb; ipdb.set_trace()
try:
    with torch.cuda.amp.autocast(dtype=torch.bfloat16), torch.no_grad():
        res = model(input_ids=input_ids, attention_mask=attn_mask, output_hidden_states=True)
        res2 = model(input_ids=input_ids, output_hidden_states=True)
        res_sdpa = model2(input_ids=input_ids, attention_mask=attn_mask, output_hidden_states=True)
except Exception:
    import traceback
    print(traceback.print_exc())

for i in range(len(input_ids[0])):
    for j in range(len(input_ids)):
        if not (res['last_hidden_state'][j, i] == res2['last_hidden_state'][j, i]).all():
            print(f'v1. not equal, {j}, {i}')

for i in range(len(input_ids[0])):
    for j in range(len(input_ids)):
        if not (res2['last_hidden_state'][j, i] == res_sdpa['last_hidden_state'][j, i]).all():
            print(f'[flash and sdpa] not equal, {j}, {i}')

for i in range(29):  # 共29层
    for bs in range(len(input_ids)):
        for seq_len in range(len(input_ids[0])):
            if not (res['hidden_states'][i][bs, seq_len] == res_sdpa['hidden_states'][i][bs, seq_len]).all():
                print(f"[flash和sdpa] 各层差异", i, bs, seq_len, (res['hidden_states'][i][bs, seq_len] - res_sdpa['hidden_states'][i][bs, seq_len]).abs().max().item())

```

**Comment by jklj077** [comment]
Hi, that is very nice observation!

PyTorch official document does have explanation on this, and you can refer to <https://pytorch.org/docs/2.3/generated/torch.nn.functional.scaled_dot_product_attention.html>. 

In general, that's just how floating-point arithmetic behaves. Floating-point addition and multiplication are not necessarily associative or distributive, making the order of the operation essential for producing the same results. However, fused kernels like ones used in flash attention inevitably change the order of the operation, leading to different (but not necessarily _wrong_, they are just all inaccurate) results.

In fact, PyTorch supports 3 kinds of sdpa kernels (flash_attention, memory_efficient, and math) and their reuslts are all different from each other. This should not have a major effect on the output quality, but if you would like consistency, specifying the exact kernel you would to use is good practice.
