### ISSUE TITLE
[Question] The max_position_embeddings and sliding_window settings in the config.json for Qwen2-57B-A14B have been set to 131072. Is that correct?

### ISSUE THREAD

**Issue by CFTangT** [QwenLM/Qwen2#679]
The context length for Qwen2-57B-A14B is 32k, but the default setting of `max_position_embeddings` and `sliding_window` is 131072 in the config.json seems to be incorrect. In comparison, for Qwen2-57B-A14B-Instruct, the same setting is 32768, which appears to be more appropriate.

links:
https://huggingface.co/Qwen/Qwen2-57B-A14B/blob/main/config.json

**Comment by CFTangT** [comment]
Hi, are there any results? @hzhwcmhf @jklj077

**Comment by hzhwcmhf** [comment]
@CFTangT It is correct. All base models support the context length of 131072, and the context length of instruction models are different. (0.5/1.5B=32k; 57B-A14B=64k; 7/72B=128k.)

**Comment by ASC8384** [comment]
> @CFTangT It is correct. All base models support the context length of 131072, and the context length of instruction models are different. (0.5/1.5B=32k; 57B-A14B=64k; 7/72B=128k.)

However, the `max_position_embeddings` of 7/72B instruct only 32K, which made me:
`This model's maximum context length is 32768 tokens. However, you requested 40084 tokens in the messages, Please reduce the length of the messages.`
