### ISSUE TITLE
用qwen2-72b-instruct来生成一个reponse需要多久？

### ISSUE THREAD

**Issue by xinyaofan** [QwenLM/Qwen2#680]
我用首页的方式让qwen2-72b-instruct 做一次inference要5分钟左右？有没有什么并行的方式可以快速做inference呢？谢谢

**Comment by jklj077** [comment]
Hi, refer to our docs on the expected speed.
- https://qwen.readthedocs.io/zh-cn/latest/benchmark/speed_benchmark.html
