### ISSUE TITLE
qwen2 0.5B/1.5B llama Q4_k_M 量化后做rag的 bad case 回复混乱非常糟糕，不如qwen1.5 1.5B llama Q4_k_m 量化后的效果

### ISSUE THREAD

**Issue by siduoge** [QwenLM/Qwen2#681]
目前我在做一个在cpu上实现的Rag项目，预计用0.5-1.5B的qwe模型量化在llama上运行
基于新出的qwen2 0.5B/1.5B尝试了了几个llama  Q4_k_M 量化后的Case
结论：
   qwen2 0.5B/1.5B llama Q4_k_M 量化后 bad case 非常糟糕
   qwen1.5 1.5B  llama Q4_k_M 量化后的case 正常

# 基于cpu运行
rag的prompt: 
            '<指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题”，答案请使用中文。 </指令>\n'
            '<已知信息>{{ context }}</已知信息>\n'
            '<问题>{{ question }}</问题>\n',
qwen2 0.5B case:

<img width="418" alt="935c32063a3ba132feadd8e41b80f0f" src="https://github.com/QwenLM/Qwen2/assets/17908389/e8896f3a-8a37-4518-ac33-daa80f287a80">

qwen2 0.5 B  llama Q4_k_M 量化 case:
<img width="467" alt="868cc210a479d504d71fa475320972d" src="https://github.com/QwenLM/Qwen2/assets/17908389/96fa02ae-71fe-44af-9683-1d91de7c554e">

qwen2 1.5B case:
<img width="397" alt="43bf770a33894d450e543fadf88f47f" src="https://github.com/QwenLM/Qwen2/assets/17908389/7afa676c-cd9f-47d2-8bbd-5f415684a06f">
qwen2 1.5 B  llama Q4_k_M 量化 case:
<img width="406" alt="a79120ced0f32f539fccc956ffccf67" src="https://github.com/QwenLM/Qwen2/assets/17908389/597cf6e7-bad0-4b77-992d-ac6462adfe21">
qwen1.5 1.5 B  llama Q4_k_M 量化 case:
<img width="419" alt="60b459f3a047544ba376e655a366374" src="https://github.com/QwenLM/Qwen2/assets/17908389/e4845561-92da-4377-b548-365612cc9891">

**Comment by siduoge** [comment]
qwen2 0.5B/1.5B 用的是instruct 版本模型， qwen1.5 用的是chat版本模型

**Comment by jklj077** [comment]
Hi, can I know where did you get the quantized checkpoints or did you quantize yourself?

**Comment by siduoge** [comment]
我自己用llama.cpp工具量化的，为了保证效果的一致性，也用了huggingface上的0.5b的gguf确认，发现效果一样

**Comment by siduoge** [comment]
> Hi, can I know where did you get the quantized checkpoints or did you quantize yourself?

huggingface上的0.5b的qwe2 0.5B instruct 的 gguf 效果也是这样，在回答完问题后会随机生成一些奇怪的东西

**Comment by siduoge** [comment]
这个是完整的promt:
<指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题”，答案请使用中文。 </指令>\n'
            '<已知信息>{{稻香湖工作区园区为禁烟园区，严禁在园区内吸烟,违规吸烟者处以罚款，每次200元，如工作区物业有更高金额罚款规定或给公司造成更高金额损失的，员工应按照更高金额赔偿公司,7.严禁随意丢弃垃圾，注意垃圾分类；公司公共区域的清洁卫生工作由保洁人员负责，员工要爱惜、维护；员工个人办公区域由员工自行负责，确保各类用品摆放整齐、环境整洁、随手清洁、及时归位,6.严禁在办公楼、园区内吸烟；严禁在工作区内嬉戏打闹、大声喧哗，影响他人工作,5.共同维护良好、舒适的办公环境；9.未经许可携带违禁品、危险品、与工作无关的大型物品或宠物进入工作区的；,10.故意损坏公司、客户或同事财物,且损失金额在人民币10,000元以上的；9.严禁私接电源、拆改线路，私自增设大负荷用电设备，不得使用与办公无关的电气设备,不得私自改动办公区域内的电话线及信息点，不得擅自改变设备用途 }}</已知信息>\n'
            '<问题>{{办公区允许抽烟么 }}</问题>\n',

**Comment by jklj077** [comment]
Hi, I cannot reproduce this.

Using qwen2-0_5b-instruct-q4_k_m.gguf and llama-cpp (server):
![image](https://github.com/QwenLM/Qwen2/assets/17811943/3cd974fc-5a8c-4dd7-89a7-0ac5f3ad59e8)

(The input has newline which is not shown in the frontend.)

Using ollama:
![image](https://github.com/QwenLM/Qwen2/assets/17811943/c0e6ce8f-74ec-4e1b-9ae7-f761be68b3db)

**Comment by siduoge** [comment]
> Hi, I cannot reproduce this.
> 
> Using qwen2-0_5b-instruct-q4_k_m.gguf and llama-cpp (server): ![image](https://private-user-images.githubusercontent.com/17811943/341347197-3cd974fc-5a8c-4dd7-89a7-0ac5f3ad59e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzQ4NDksIm5iZiI6MTcxODg3NDU0OSwicGF0aCI6Ii8xNzgxMTk0My8zNDEzNDcxOTctM2NkOTc0ZmMtNWE4Yy00ZGQ3LTg5YTctMGFjNWYzYWQ1OWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YTkxNTg0ZTg4MzkwMzdlZTk5MDA3MGEwNDJhNjkxMzY1ZDljYTA2NWM5MTVjOTMzNDVlNmMzMzZlNjY5MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RgJEpgB4KHHX9QTTT6cuy_DrAjGpj-gBK5o_kEDNays)
> 
> (The input has newline which is not shown in the frontend.)
> 
> Using ollama: ![image](https://private-user-images.githubusercontent.com/17811943/341347885-c0e6ce8f-74ec-4e1b-9ae7-f761be68b3db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzQ4NDksIm5iZiI6MTcxODg3NDU0OSwicGF0aCI6Ii8xNzgxMTk0My8zNDEzNDc4ODUtYzBlNmNlOGYtNzRlYy00ZTFiLTlhZTctZjc2MWJlNjhiM2RiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMGQxODVkNDA5MTRhZTE4YTY0ZTRlZjIzMGI4MDJiYjNmN2U5YjE2M2IwNGNkM2M4NWQ0NDBlMmJjNmE5MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tmsiMa2ysqhfX_XRjG5aU3Y7YQMvTPpLc3JyVIlrWDM)

是不是需要一些特殊的prompt方式，我试试你的这个promot模式，感谢

**Comment by siduoge** [comment]
> llama.cpp 的promot格式一定要加<im_start> <im_end>么
> Hi, I cannot reproduce this.
> 
> Using qwen2-0_5b-instruct-q4_k_m.gguf and llama-cpp (server): ![image](https://private-user-images.githubusercontent.com/17811943/341347197-3cd974fc-5a8c-4dd7-89a7-0ac5f3ad59e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzQ4NDksIm5iZiI6MTcxODg3NDU0OSwicGF0aCI6Ii8xNzgxMTk0My8zNDEzNDcxOTctM2NkOTc0ZmMtNWE4Yy00ZGQ3LTg5YTctMGFjNWYzYWQ1OWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YTkxNTg0ZTg4MzkwMzdlZTk5MDA3MGEwNDJhNjkxMzY1ZDljYTA2NWM5MTVjOTMzNDVlNmMzMzZlNjY5MzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RgJEpgB4KHHX9QTTT6cuy_DrAjGpj-gBK5o_kEDNays)
> 
> (The input has newline which is not shown in the frontend.)
> 
> Using ollama: ![image](https://private-user-images.githubusercontent.com/17811943/341347885-c0e6ce8f-74ec-4e1b-9ae7-f761be68b3db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzQ4NDksIm5iZiI6MTcxODg3NDU0OSwicGF0aCI6Ii8xNzgxMTk0My8zNDEzNDc4ODUtYzBlNmNlOGYtNzRlYy00ZTFiLTlhZTctZjc2MWJlNjhiM2RiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMGQxODVkNDA5MTRhZTE4YTY0ZTRlZjIzMGI4MDJiYjNmN2U5YjE2M2IwNGNkM2M4NWQ0NDBlMmJjNmE5MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tmsiMa2ysqhfX_XRjG5aU3Y7YQMvTPpLc3JyVIlrWDM)

**Comment by jklj077** [comment]
Unfortunately, since we don't know what happens in your application (and ultimately, it is up to you to ensure the model is used properly), there is not much we can do. 

Qwen models has always used the ChatML template and frameworks should support that out of the box.

If you are using the basic completion mode/solely text generation, and the frameworks do not handle chat templates for you, the input for your example should be like this
```
<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
<指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题”，答案请使用中文。 </指令>
<已知信息>{{稻香湖工作区园区为禁烟园区，严禁在园区内吸烟,违规吸烟者处以罚款，每次200元，如工作区物业有更高金额罚款规定或给公司造成更高金额损失的，员工应按照更高金额赔偿公司,7.严禁随意丢弃垃圾，注意垃圾分类；公司公共区域的清洁卫生工作由保洁人员负责，员工要爱惜、维护；员工个人办公区域由员工自行负责，确保各类用品摆放整齐、环境整洁、随手清洁、及时归位,6.严禁在办公楼、园区内吸烟；严禁在工作区内嬉戏打闹、大声喧哗，影响他人工作,5.共同维护良好、舒适的办公环境；9.未经许可携带违禁品、危险品、与工作无关的大型物品或宠物进入工作区的；,10.故意损坏公司、客户或同事财物,且损失金额在人民币10,000元以上的；9.严禁私接电源、拆改线路，私自增设大负荷用电设备，不得使用与办公无关的电气设备,不得私自改动办公区域内的电话线及信息点，不得擅自改变设备用途 }}</已知信息>
<问题>{{办公区允许抽烟么 }}</问题><|im_end|>
<|im_start|>assistant
```
