### ISSUE TITLE
Qwen2-72B-Instruct无限输出，设置了stop_token_ids也无法停止

### ISSUE THREAD

**Issue by yunchao-scut** [QwenLM/Qwen2#688]
curl http://localhost:8081/v1/chat/completions \
    -H "Content-Type: application/json" \
    -d '{
    "model": "Qwen2-72B-Instruct",
    "stream": true,
    "stop_token_ids": [151645,151643],
    "stop": ["<|im_end|>"],
    "repetition_penalty": 1.9,
    "messages": [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "1+1等于几"}
    ]
    }'

**Comment by yunchao-scut** [comment]
使用的是vllm0.5.0部署

**Comment by jklj077** [comment]
The repetition_penalty was set too high, and the default value should be 1.05; setting it too high or too low will affect response quality, and we recommend adjusting the value near 1.0, which is the  neutral value.
