### ISSUE TITLE
Could you pls share scripts for SFT on qwen2-70B

### ISSUE THREAD

**Issue by yangfuwei** [QwenLM/Qwen2#689]
There's only example of fine-tuning 7B models, https://github.com/QwenLM/Qwen2/blob/main/examples/sft/finetune.sh, which uses deepspeed. However, considering qwen2-70B, maybe pipeline parallelism is needed? Did you use megatron-LM? Do you have any example scripts for reference? Thank you~

**Comment by jklj077** [comment]
We advise you to use training frameworks, including [Axolotl](https://github.com/OpenAccess-AI-Collective/axolotl), [Llama-Factory](https://github.com/hiyouga/LLaMA-Factory), [Swift](https://github.com/modelscope/swift), etc., to finetune your models with SFT, DPO, PPO, etc.

There have been Qwen2-72B finetuned models by the community with those frameworks and you should be able to finetune Qwen2-72B with them, too.
