### ISSUE TITLE
VQA Finetuning for Custom Data 

### ISSUE THREAD

**Issue by ajb8866** [QwenLM/Qwen2#691]
Hello, I wanted to ask if fine-tuning the model was similar to Qwen. I have some VQA data that I would love to test and benchmark on Qwen2, but I am unsure if it works just like it did for the Qwen model or if there is a different format.

**Comment by jklj077** [comment]
Hi, Qwen is a large language model and you need to adapt it yourself for VQA tasks. If you are looking for vision-language models, please see Qwen-VL.
