### ISSUE TITLE
请教针对chat模型进行awq量化的技术细节

### ISSUE THREAD

**Issue by SaiqiKing** [QwenLM/Qwen2#692]
请问qwen-chat模型在进行awq量化时，校验数据集是什么类型的数据集（对话或者通用文本？），另外校验集预处理过程是什么？在awq量化过程中选择了多少条样本？样本最大token长度限制为多少？感谢回答~

**Comment by jklj077** [comment]
1. Try using the most similar dataset and format for the targeted scenario as the calibration set for quantization.
2. Follow the AWQ guidelines accordingly.
