### ISSUE TITLE
 使用lm 加载qwen2  7b 设置flashattention 依然回复GGGGGGG 使用cpu又是乱码~

### ISSUE THREAD

**Issue by liu-super** [QwenLM/Qwen2#694]
![image](https://github.com/QwenLM/Qwen2/assets/5554605/2b122746-f928-4398-a243-8d77b5ed1770)

**Comment by jklj077** [comment]
Hi, I am not able to reproduce with LM Studio 0.2.25

![image](https://github.com/QwenLM/Qwen2/assets/17811943/0599b230-d703-415c-ac4a-5f27869bc65f)
