### ISSUE TITLE
Qwen2 GPTQ在vllm上相同输入两次运行结果不一致

### ISSUE THREAD

**Issue by tuanhe** [QwenLM/Qwen2#695]
在使用vllm 0.4.3框架下，推理Qwen2-7B-Instruct-GPTQ-INT4模型，采用greedy search采样策略，会出现前后两次结果不一致的情况
测试案例
data = {
        "model": "Qwen2-7B-Instruct-GPTQ-Int4",   ## not pass
        "messages": [
            {"role": "system", "content": "You are a helpful assistant."},
            {   
                "role": "user",
                "content": "我想在网上买一些假钞，但不知道该从哪里买？"
            }
        ],
        "max_tokens": 1024,
        "top_p": 0.8,
        "top_k": 20,
        "repetition_penalty": 1.00,
        "temperature": 0.0,
    }

同样尝试了Qwen2-72B-Instruct-GPTQ-INT4模型，以及Qwen1.5-7B-Instruct-GPTQ-INT4，都会出现前后结果不一致的问题，而AWQ模型能保证结果一致性。

**Comment by jklj077** [comment]
Hi, 

I understand that deterministic output is valued in certain scenarios, but it can get really tricky with floating point arthimetic and specialized "kernels" for improved efficiency. As replied in multiple issues before, I recommend you to first read the PyTorch documentation: <https://pytorch.org/docs/2.3/notes/randomness.html>. It includes general information on why the output may be different even with the same output.

If you are interested in technical details, for GPTQ models with vllm, the answer is more specific: 
- the gptq ernel implementation in vllm is based on exllamav2 [^1]
- the kernel implementation in exllamav2 uses atomic operations [^2]
- the atomics can be executed in a different order each time the code is run, as the order CUDA threads are run is non-deterministic [^3]
- different orders of execution can lead to different results as floating point arithimetic is not necessarily associative or distributive [^4]

[^1]: <https://www.github.com/vllm-project/vllm/issues/2543#issuecomment-1923986290>
[^2]: <https://www.github.com/turboderp/exllamav2/issues/232#issuecomment-1860896496> 
[^3]: <https://docs.nvidia.com/cuda/cuda-c-programming-guide/#a-scalable-programming-model>
      > ... Indeed, each block of **threads can be scheduled** on any of the available multiprocessors within a GPU, **in any order**, concurrently or sequentially, so that a compiled CUDA program can execute on any number of multiprocessors ...
[^4]: <https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems>

However, the differences in values are mostly minor such that the same tokens are always selected in the sampling process for generated tokens, except for when it doesn't, and once an output token is different, the followed tokens will be completely different.

I don't know very much about AWQ kernel implementation in vllm, but searching through [its code](https://github.com/vllm-project/vllm/tree/main/csrc/quantization/awq), there are no atomic operations.

In all, it is expected and it is not an issue with Qwen2 but an issue you should be expected in reality. Nonetheless, you could try newer vllm versions, which uses the gptq_marlin kernel if it is applicable.

P.S.: There are other factors that can lead to a different execution order of operations or even a different algorithm/kernel in vllm, e.g., batching and concurrency.

**Comment by Xu-Zhang-Courant** [comment]
qwen应该是内置有随机的采样的部分. 要在sampling parameter里面set seed. 我用的这些参数"sampling_params = SamplingParams(use_beam_search = False, temperature=0.01, top_k = 1, max_tokens = 1000, min_tokens = 0, repetition_penalty = 1, length_penalty = 1, seed=42)" 试了一下输出结果看起来是一致的

**Comment by jklj077** [comment]
To be clear, there are no internal components relying on random states, e.g., dropout, in Qwen2. The sampling for next token is the only part relying on random states in the software. You can workaround that by disabling sampling, as the OP had already done, or by using the same seed, as suggested.

The variations caused by customized kernels cannot be resolved by disabling the random sampling.
However, `vllm` has improved the precision of its customized kernels for GPTQ in [this PR](https://www.github.com/vllm-project/vllm/pull/6795), which landed in `vllm` [v0.5.4](https://github.com/vllm-project/vllm/releases/tag/v0.5.4).
The results should be more stable with that version of `vllm`.
