### ISSUE TITLE
autoawq model finetuning qwen72b instruct

### ISSUE THREAD

**Issue by fersebas** [QwenLM/Qwen2#698]
Hi! We are trying tu run a awq model after finetuning qwen72b but we got this error in vllm when we set tensor parallel to 4 gpus, how can I fix it?

"The input size is not aligned with the quantized weight shape. This can be caused by too large tensor parallel size."

Thanks in advanced

**Comment by jklj077** [comment]
Hi, it is similar to <https://github.com/QwenLM/Qwen2/issues/578>. 

There are several constraints for tensor parallel size and vllm will raise errors if the constraints ar not met. In generl, the tensor parallel size should be the divisor of
- the intermediate size of the MLP
- the number of attention heads
- (for quantized models only) the quantized weight shape, which depends on the quantization scheme, and normally is the intermediate size divided by the group size.

**Comment by jklj077** [comment]
Have you look at that issue?

**Comment by fersebas** [comment]
Yes, but i dont understand what can i do to replicate the qwen72binstructawq from huggingface that it works in 4 gpus :/

**Comment by jklj077** [comment]
run the code and pad your finetuned model first; the solution is right there?

**Comment by jklj077** [comment]
I think something is missing here. Your finetuned model is in the bnb format, right? It should be a quantized model by itself. What is the reason that you would like to quantize it again?

**Comment by fersebas** [comment]
Mmm, I saved as float16 full model then awq compression because in vllm i have got some errors with bits and bytes. But maybe it works directly . But i think i will have the problem with 4 gpus tensor paralell because intermediate size of mlp. This model we are finetuning https://huggingface.co/unsloth/Qwen2-72B-Instruct-bnb-4bit

**Comment by ArlanCooper** [comment]
i pad my awq model，
```
llm = LLM(model="/data/share/rwq/qwen25_awq_new",tensor_parallel_size=2,trust_remote_code=True,max_model_len=32768)

```





but got this error:


```
RuntimeError: start (1856) + length (1856) exceeds dimension size (3696).

```
