### ISSUE TITLE
qwen2 1.5B 评测结果无法对齐

### ISSUE THREAD

**Issue by momoyrz** [QwenLM/Qwen2#700]
您好，

我们使用了 qwen2 1.5B base 模型在 ceval、cmmlu 和 mmlu 数据集上进行了测试，结果分别为 70.621、66.761 和 51.11。我们发现只有 ceval 的评测结果与贵司的评测结果一致。我们的评测方法是与 opencompass 对齐的。

请问贵司在评测 cmmlu 和 mmlu 这两个数据集时的具体细节是什么？例如所使用的 5shot 和 prompt 是怎样的？谢谢！

**Comment by lonleyodd** [comment]
我利用llmuse框架在mmlu，c-eval上测Qwen2-7B-Instruct，得到的结果分别为69.52，71.73与官方的结果均不一致

**Comment by hzhwcmhf** [comment]
@lonleyodd  关于Instruct的ceva分数可以使用这个脚本复现
https://github.com/QwenLM/Qwen/blob/main/eval/evaluate_chat_ceval.py

Instruct的mmlu的话，根据inference引擎的不同，一个点的波动属于正常现象。如果想完全对齐setting，我们使用的是opencompass这里的prompt，注意chatml格式。
https://github.com/open-compass/opencompass/blob/26d077b080513b495b49aeb5794b6d0a6c32c96b/configs/datasets/mmlu/mmlu_gen_a484b3.py

base测试方法请 @liudayiheng 补充

**Comment by lonleyodd** [comment]
> @lonleyodd 关于Instruct的ceva分数可以使用这个脚本复现 https://github.com/QwenLM/Qwen/blob/main/eval/evaluate_chat_ceval.py
> 
> Instruct的mmlu的话，根据inference引擎的不同，一个点的波动属于正常现象。如果想完全对齐setting，我们使用的是opencompass这里的prompt，注意chatml格式。 https://github.com/open-compass/opencompass/blob/26d077b080513b495b49aeb5794b6d0a6c32c96b/configs/datasets/mmlu/mmlu_gen_a484b3.py
> 
> base测试方法请 @liudayiheng 补充
感谢你的分享，我根据你提供的ceval脚本在复现过程中发生了如下的报错：

**Comment by zjintheroom** [comment]
> @lonleyodd 关于Instruct的ceva分数可以使用这个脚本复现 https://github.com/QwenLM/Qwen/blob/main/eval/evaluate_chat_ceval.py
> 
> Instruct的mmlu的话，根据inference引擎的不同，一个点的波动属于正常现象。如果想完全对齐setting，我们使用的是opencompass这里的prompt，注意chatml格式。 https://github.com/open-compass/opencompass/blob/26d077b080513b495b49aeb5794b6d0a6c32c96b/configs/datasets/mmlu/mmlu_gen_a484b3.py
> 
> base测试方法请 @liudayiheng 补充

你好，我用opencompass评测ceval，发现opencompass评测出来的分数，比咱们官方给的分数要高不到7分。哦，评测模型为 qwen2-72B-instruct。能找您要一下chat模型 在gsm8k,math,humaneval以及ceval 这几个数据集的评测方法么。
