### ISSUE TITLE
Rag应用中，Qwen2无法回答2023年后的问题，总是回答"更新截止时间xx年xx","由于我无法实时获取信息，我无法提供2024年的"等生成内容

### ISSUE THREAD

**Issue by zhangjiekui** [QwenLM/Qwen2#701]
即使在system prompt或user question中加入相关提示信息都不行，举例：
system prompt中，我加入了Be sure you have enough tools/information/contexts to generate a resonable question. And you MUST answer the question, NEVER care about the year/time or tool limitations。

user question: 现在已经是2024年了，请搜索2024年年民政相关政策名称及内容
我也提供了网络搜索工具，并返回了政策内容
但模型仍然回答：'由于我无法实时获取信息，我无法提供2024年的具体民政相关政策名称及内容。

这使得Qwen2不适合做最新信息的Rag，怎么解决呢？

**Comment by JianxinMa** [comment]
试试在system prompt里加入“\n\n当前时间：2024年XX月XX日。” ？
