### ISSUE TITLE
单机多卡进行RLHF在第三步中使用Qwen模型作Actor Model报错

### ISSUE THREAD

**Issue by Dakai798** [QwenLM/Qwen2#703]
![微信图片_20240625102800](https://github.com/QwenLM/Qwen2/assets/56241957/13f01be8-8e28-4b30-8a31-c1447086004a)

**Comment by jklj077** [comment]
Please provide more details, what is this? Based on the errors, it is a bug in your code: latency is a float and self._total_batch_size is None.

**Comment by Dakai798** [comment]
问题已解决，在RLHF的第三步训练中在脚本运行前，关闭enable hybrid engine，但是不明白对于Qwen模型是为什么？
The problem has been resolved. In the third step of RLHF training, the enable hybrid engine was turned off before the script was run, but I am not sure what it is for the Qwen model?
![微信图片_20240625113642](https://github.com/QwenLM/Qwen2/assets/56241957/6d8edf71-3552-4e60-8017-9a3ac6db4c47)
