### ISSUE TITLE
Qwen2-7B-Instruct's performance gaps in evaluations of the GSM8K and MATH datasets with official scores

### ISSUE THREAD

**Issue by ArixLi** [QwenLM/Qwen2#709]
Hi,

I have used the lm-harness framework to evaluate metrics on the GSM8K and MATH datasets with Qwen2-7B models. However, I noticed performance gaps specifically with the Qwen2-Instruct models, whereas I can track performance well with the Base Model.

![20240627102705](https://github.com/QwenLM/Qwen2/assets/50404932/046c8347-bcfb-426e-a201-fd4f39f6ec8e)

Moreover, the Base model also has a performance gap on BBH-3_shots-CoT evaluation with nearly 0.1 gap (0.526 vs 0.626 on official website).

These metrics perform well with other series of models like LLaMA3-8B. When examining the eval/ folder in the Qwen1 repository, I observed significant differences in the pipeline and prompt between the Base and Instruct (Chat in Qwen1) models. Therefore, I am wondering if the performance gap stems from differences in prompt, answer extraction, or post-processing.

Thanks

**Comment by llltttppp** [comment]
可以试试opencompass，我自己测基本能对上

**Comment by canghongjian** [comment]
> You can try opencompass. I get the score close to the official result

Hi, could you please share the evaluation script of evaluating Qwen2 using opencompass? Thanks.
