### ISSUE TITLE
关于qwen2-72b-int4的一些压测及优化问题咨询

### ISSUE THREAD

**Issue by PeaceAndJoyAaron** [QwenLM/Qwen2#715]
我在两台V100的服务器上部署了qwen2-72b-int4模型，并成功跑通
但是我在尝试做一些推理操作的时候遇到了一些问题，如下：
1、推理速度很慢，例如帮我出某一个文案的时候需要大概20分钟左右，不知道如何能够优化这个速度，如果我提升服务器例如更换成A800能否提升效率？
2、我想做关于模型的压测时，发现在多线程情况下，模型的推理速度成倍数降低，似乎模型本身只支持单线程操作一样，多线程情况下线程之间会阻塞，不知道是因为我模型启动的问题还是如何
希望得到回复，谢谢！

**Comment by jklj077** [comment]
what frameworks were you using?
