### ISSUE TITLE
qwen2-72b和qwen2-72b-instruct中都没有开  use_sliding_window 是出于什么考虑呢

### ISSUE THREAD

**Issue by ehuaa** [QwenLM/Qwen2#716]
huggingface上qwen2-72b官方的config中都设置
"use_sliding_window": false,
想问下是出于什么考虑的呢，
是训练的时候就没有用SWA去优化么，这个是出于训练精度的层面考虑的么？因为毕竟用上了的话对于kvcache优化很大

**Comment by lonngxiang** [comment]
对，要怎么使用这128k长度呢

**Comment by JUN-ZZ** [comment]
@lonngxiang 大佬 怎么设置128k啊

**Comment by IgorZan** [comment]
same question？
