### ISSUE TITLE
工具调用进入死循环，有没有办法解决？

### ISSUE THREAD

**Issue by zhanweiw** [QwenLM/Qwen2#719]
我当前使用的还是QWen 1.0，参考如下文档写的代码：
https://github.com/QwenLM/Qwen/blob/main/examples/langchain_tooluse.ipynb

如下是调用函数：
```
query = "加拿大2022年的人口数量有多少？" # 所提问题
choose_tools = TOOLS # 选择备选工具
print("=" * 30)
main(query, choose_tools)

print()

query = "请问上海有哪些美食？"
choose_tools = TOOLS # 选择备选工具
print("=" * 30)
main(query, choose_tools)
```

对于第一个问题，能正常回答，但第二个问题在'Observation'后给出搜索答案后，还是一直回答"我应该使用搜索工具来查找相关信息。"

==============================

Question: 加拿大2022年的人口数量有多少？

Thought: 我需要查找加拿大的人口数量
Action: Search
Action Input: {"query": "加拿大 2022年人口数量"}
Observation:

Answer the following questions as best you can. You have access to the following tools:

Search: Call this tool to interact with the google search API. What is the google search API useful for? useful for when you need to answer questions about current events. Parameters: [{"name": "query", "type": "string", "description": "search query of google", "required": true}] Format the arguments as a JSON object.

Math: Call this tool to interact with the Wolfram Alpha API. What is the Wolfram Alpha API useful for? Useful for when you need to answer questions about Math, Science, Technology, Culture, Society and Everyday Life. Parameters: [{"name": "query", "type": "string", "description": "the problem to solved by Wolfram Alpha", "required": true}] Format the arguments as a JSON object.

python: Call this tool to interact with the python API. What is the python API useful for? A Python shell. Use this to execute python commands. When using this tool, sometimes output is abbreviated - Make sure it does not look abbreviated before using it in your answer. Don't add comments to your python code. Parameters: [{"name": "query", "type": "string", "description": "a valid python command.", "required": true}] Format the arguments as a JSON object.

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [Search,Math,python]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can be repeated zero or more times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: 加拿大2022年的人口数量有多少？
Thought: 我需要查找加拿大的人口数量
Action: Search
Action Input: {"query": "加拿大 2022年人口数量"}
Observation: {'type': 'population_result', 'place': 'Canada', 'population': '38.93 million', 'year': '2022'}
Thought: 我现在可以作答了。
Final Answer: 加拿大2022年的人口数量为38.93百万。
Thought: 我现在可以作答了。
Final Answer: 加拿大2022年的人口数量为38.93百万。

==============================

Question: 请问上海有哪些美食？

Thought: 我应该使用搜索工具来查找相关信息。
Action: Search
Action Input: {"query": "上海美食"}
Observation:

Answer the following questions as best you can. You have access to the following tools:

Search: Call this tool to interact with the google search API. What is the google search API useful for? useful for when you need to answer questions about current events. Parameters: [{"name": "query", "type": "string", "description": "search query of google", "required": true}] Format the arguments as a JSON object.

Math: Call this tool to interact with the Wolfram Alpha API. What is the Wolfram Alpha API useful for? Useful for when you need to answer questions about Math, Science, Technology, Culture, Society and Everyday Life. Parameters: [{"name": "query", "type": "string", "description": "the problem to solved by Wolfram Alpha", "required": true}] Format the arguments as a JSON object.

python: Call this tool to interact with the python API. What is the python API useful for? A Python shell. Use this to execute python commands. When using this tool, sometimes output is abbreviated - Make sure it does not look abbreviated before using it in your answer. Don't add comments to your python code. Parameters: [{"name": "query", "type": "string", "description": "a valid python command.", "required": true}] Format the arguments as a JSON object.

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [Search,Math,python]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can be repeated zero or more times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: 请问上海有哪些美食？
Thought: 我应该使用搜索工具来查找相关信息。
Action: Search
Action Input: {"query": "上海美食"}
Observation: ['说起上海菜，人们最先想到的经典美食就是小笼包，制作小笼包要先将面粉压成薄皮，再包入猪肉、虾肉、蟹肉或其他蔬菜，然后放入圆形竹笼中蒸熟。一口咬 开小 ...', 'Q：上海美食小吃類有哪些推薦必吃？ 推薦以下三間上海美食！老弄堂麵館，有勁道的麵體加上傳統的調味，麵食控不能錯過；萊萊小籠，小籠包鮮嫩多汁，值得 ...', '1. 生煎包：上海特色小吃，外皮酥脆，内馅多汁。 · 2. 南翔小笼包：以皮薄、馅大、汁多、味鲜、形美著称。 · 3. 鲜肉月饼：苏式月饼的一种，皮脆而韧，咸 ...', '【中國】上海十大必吃美食推薦：上海生煎包、小籠包、排骨年糕、蔥油拌麵一個都不能錯過（內附推薦店家及詳細交通方式） · 小籠湯包 · 生煎饅頭 · 排骨 ...', '【上海美食地圖】上海美食攻略 · 必吃上海美食餐廳一：小楊生煎 · 必吃上海美食餐廳二：外婆家 · 必吃上海美食餐廳三：南翔饅頭店 · 必吃上海美食餐廳四：桂滿隴 · 必吃 ...', '上海人称的本帮菜指的是上海本地风味的菜肴，特色可有用浓油赤酱（油多味浓、糖重、色艳）概括。本帮炒菜中，荤菜中特色菜有响油鳝糊、油爆河虾、油酱毛蟹、锅烧河 鳗、 ...', '爱上海的理由有千千万万，但其中一定不能漏掉的一点就是永远都有吃不完的美食！ 今天，小侬就将最具上海特色的美味汇集于此，一次让你馋个够！', 'https://zhuanlan.zhihu.com/p/51435306']

Thought: 我应该使用搜索工具来查找相关信息。
Action: Search
Action Input: {"query": "上海美食"}
Observation: 

Answer the following questions as best you can. You have access to the following tools:

Search: Call this tool to interact with the google search API. What is the google search API useful for? useful for when you need to answer questions about current events. Parameters: [{"name": "query", "type": "string", "description": "search query of google", "required": true}] Format the arguments as a JSON object.

Math: Call this tool to interact with the Wolfram Alpha API. What is the Wolfram Alpha API useful for? Useful for when you need to answer questions about Math, Science, Technology, Culture, Society and Everyday Life. Parameters: [{"name": "query", "type": "string", "description": "the problem to solved by Wolfram Alpha", "required": true}] Format the arguments as a JSON object.

python: Call this tool to interact with the python API. What is the python API useful for? A Python shell. Use this to execute python commands. When using this tool, sometimes output is abbreviated - Make sure it does not look abbreviated before using it in your answer. Don't add comments to your python code. Parameters: [{"name": "query", "type": "string", "description": "a valid python command.", "required": true}] Format the arguments as a JSON object.

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [Search,Math,python]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can be repeated zero or more times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: 请问上海有哪些美食？
Thought: 我应该使用搜索工具来查找相关信息。
Action: Search
Action Input: {"query": "上海美食"}
Observation: ['说起上海菜，人们最先想到的经典美食就是小笼包，制作小笼包要先将面粉压成薄皮，再包入猪肉、虾肉、蟹肉或其他蔬菜，然后放入圆形竹笼中蒸熟。一口咬 开小 ...', 'Q：上海美食小吃類有哪些推薦必吃？ 推薦以下三間上海美食！老弄堂麵館，有勁道的麵體加上傳統的調味，麵食控不能錯過；萊萊小籠，小籠包鮮嫩多汁，值得 ...', '1. 生煎包：上海特色小吃，外皮酥脆，内馅多汁。 · 2. 南翔小笼包：以皮薄、馅大、汁多、味鲜、形美著称。 · 3. 鲜肉月饼：苏式月饼的一种，皮脆而韧，咸 ...', '【中國】上海十大必吃美食推薦：上海生煎包、小籠包、排骨年糕、蔥油拌麵一個都不能錯過（內附推薦店家及詳細交通方式） · 小籠湯包 · 生煎饅頭 · 排骨 ...', '【上海美食地圖】上海美食攻略 · 必吃上海美食餐廳一：小楊生煎 · 必吃上海美食餐廳二：外婆家 · 必吃上海美食餐廳三：南翔饅頭店 · 必吃上海美食餐廳四：桂滿隴 · 必吃 ...', '上海人称的本帮菜指的是上海本地风味的菜肴，特色可有用浓油赤酱（油多味浓、糖重、色艳）概括。本帮炒菜中，荤菜中特色菜有响油鳝糊、油爆河虾、油酱毛蟹、锅烧河 鳗、 ...', '爱上海的理由有千千万万，但其中一定不能漏掉的一点就是永远都有吃不完的美食！ 今天，小侬就将最具上海特色的美味汇集于此，一次让你馋个够！', 'https://zhuanlan.zhihu.com/p/51435306']Thought: 我应该使用搜索工具来查找相关信息。

Action: Search
Action Input: {"query": "上海美食"}
Observation: ['说起上海菜，人们最先想到的经典美食就是小笼包，制作小笼包要先将面粉压成薄皮，再包入猪肉、虾肉、蟹肉或其他蔬菜，然后放入圆形竹笼中蒸熟。一口咬 开小 ...', 'Q：上海美食小吃類有哪些推薦必吃？ 推薦以下三間上海美食！老弄堂麵館，有勁道的麵體加上傳統的調味，麵食控不能錯過；萊萊小籠，小籠包鮮嫩多汁，值得 ...', '1. 生煎包：上海特色小吃，外皮酥脆，内馅多汁。 · 2. 南翔小笼包：以皮薄、馅大、汁多、味鲜、形美著称。 · 3. 鲜肉月饼：苏式月饼的一种，皮脆而韧，咸 ...', '【中國】上海十大必吃美食推薦：上海生煎包、小籠包、排骨年糕、蔥油拌麵一個都不能錯過（內附推薦店家及詳細交通方式） · 小籠湯包 · 生煎饅頭 · 排骨 ...', '【上海美食地圖】上海美食攻略 · 必吃上海美食餐廳一：小楊生煎 · 必吃上海美食餐廳二：外婆家 · 必吃上海美食餐廳三：南翔饅頭店 · 必吃上海美食餐廳四：桂滿隴 · 必吃 ...', '上海人称的本帮菜指的是上海本地风味的菜肴，特色可有用浓油赤酱（油多味浓、糖重、色艳）概括。本帮炒菜中，荤菜中特色菜有响油鳝糊、油爆河虾、油酱毛蟹、锅烧河 鳗、 ...', '爱上海的理由有千千万万，但其中一定不能漏掉的一点就是永远都有吃不完的美食！ 今天，小侬就将最具上海特色的美味汇集于此，一次让你馋个够！', 'https://zhuanlan.zhihu.com/p/51435306']
Thought: 我应该使用搜索工具来查找相关信息。
Action: Search
Action Input: {"query": "上海美食"}
Observation: 

```

**Comment by huangguifeng** [comment]
试过1.5，都有这个问题，尤其是上下文比较长的时候。你可以试试2.0，2.0好像没有这个问题了。
