### ISSUE TITLE
Qwen2 量化版本模型比原版推理速度慢

### ISSUE THREAD

**Issue by GL2010** [QwenLM/Qwen2#731]
同样的环境下，Qwen2-1.5B-Instruct-GPTQ-Int8 比 Qwen2-1.5B-Instruct 推理慢是什么原因呢？

环境如下：
auto-gptq                 0.6.0+cu118
optimum                   1.16.1
torch                     2.3.0+cu118
transformers              4.40.0

使用的GPU是T4

**Comment by jklj077** [comment]
GPTQ is weight quantization with a subsequent dequantization step. This process typically slows down model execution unless optimized kernel implementations are used, which fuse these operations and leverage reduced memory bandwidth from smaller parameter storage. Yet, even with such optimizations, performance gains are limited for higher bit-widths (e.g., 8-bit) and smaller models (like 1.5B parameters), as they inherently require less memory bandwidth. Consequently, while individual requests may still be slower, the reduced memory footprint enables higher concurrency, potentially enhancing overall system throughput.

**Comment by GL2010** [comment]
Qwen2-1.5B-Instruct-GPTQ-Int8 的推理速度大概只有3-5tokens/s，虽然我用的是T4，但是也不至于和测试差那么多吧
