### ISSUE TITLE
qwen2 1.5B not having lm_head? 

### ISSUE THREAD

**Issue by elfisworking** [QwenLM/Qwen2#733]
Seeing safetensor file , i can't find lm_head weight, but torch prints model  which shows us having lm_head weight. 
![qwen2_1_5B](https://github.com/QwenLM/Qwen2/assets/37609214/4378999f-588e-48cc-9827-d5b216cded8e)

**Comment by elfisworking** [comment]
have one can answer me that qwen2 1.5B has lm_head.weight ? 
 i see 7B 72B all having lm_head.weight?

**Comment by jklj077** [comment]
0.5B and 1.5B have tied word embedding
