### ISSUE TITLE
使用vllm0.5.0.post1部署Qwen-72B-Instruct，回答异常。

### ISSUE THREAD

**Issue by wangz1200** [QwenLM/Qwen2#735]
![图片](https://github.com/QwenLM/Qwen2/assets/30308361/932993db-da60-476a-a8aa-625e6e8f39dc)

**Comment by jklj077** [comment]
Hi, please provide steps to reproduce.

![image](https://github.com/QwenLM/Qwen2/assets/17811943/8b171045-0d26-474c-8d79-e8f6de130e00)

**Comment by wangz1200** [comment]
1、download models from "[modelscope.cn](https://modelscope.cn/models/qwen/Qwen2-72B-Instruct)"
2、then run command "CUDA_VISIBLE_DEVICES=4,5,6,7 python -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --port 9103 --model ./models/qwen2-72b-instruct --served-model-name gxllm --trust-remote-code --tensor-parallel-size 4 --disable-log-requests" with 4 A800 cards
3、last call openai client，there comes the problem.
other,my env is ubuntu22.04+cuda12.1+nccl 2.20.5,but the local nvidia driver display version 535.146 and cuda 12.2

**Comment by wangz1200** [comment]
maybe could I download the models from hf?

**Comment by jklj077** [comment]
1. try vllm docker image to rule out env issues
2. if possible, share the input

**Comment by wangz1200** [comment]
Qwen1.5-110B-chat works fine.
I try redownloading the checkpoint  again.
