### ISSUE TITLE
Qwen2-1.5B-Instruct-GPTQ-Int8推理速度慢

### ISSUE THREAD

**Issue by GL2010** [QwenLM/Qwen2#737]
Qwen2-1.5B-Instruct-GPTQ-Int8使用T4推理只有3-5 tokens/s，虽然没有使用vllm去推理，卡也比较弱，但是与评测的速度也差太多了，请问这种情况正常吗？

环境如下：
auto-gptq 0.6.0+cu118
optimum 1.16.1
torch 2.3.0+cu118
transformers 4.40.0

**Comment by jklj077** [comment]
provide running logs and look for "CUDA extension not installed"; if found, see the following on how to install auto-gptq with compatible versions: https://github.com/AutoGPTQ/AutoGPTQ/blob/main/docs/INSTALLATION.md
