### ISSUE TITLE
两张A800并行跑Qwen2大模型出错

### ISSUE THREAD

**Issue by CHNVigny** [QwenLM/Qwen2#743]
![3](https://github.com/QwenLM/Qwen2/assets/9402746/c5f097a1-7d0e-4710-90f3-3e252402e752)

我使用的CUDA版本为12.2，transformers版本为4.33.2，torch版本为2.0.1。

**Comment by jklj077** [comment]
https://github.com/QwenLM/Qwen2/issues/331
