### ISSUE TITLE
finetune.sh支持中断训练后 从某个checkpoint继续训练吗

### ISSUE THREAD

**Issue by xuelikanmeihua** [QwenLM/Qwen2#745]

**Comment by jklj077** [comment]
https://github.com/QwenLM/Qwen2/blob/d439e04e84ebe3734dea4e9769e17f380a8c72b8/examples/sft/finetune.py#L365-L374

it should be able to do that if LoRA is not used. but it appears that the issue on LoRA is resolved and I advise that you remove those checks and see if it works in your scenarios.

**Comment by xuelikanmeihua** [comment]
thank you！

**Comment by xuelikanmeihua** [comment]
thank you！

**Comment by xuelikanmeihua** [comment]
thank you！

**Comment by xuelikanmeihua** [comment]
I have tried it and it can run normally

**Comment by xuelikanmeihua** [comment]
![image](https://github.com/QwenLM/Qwen2/assets/27985780/231d23de-ebd5-4129-9217-0f3158fb65b9)
![image](https://github.com/QwenLM/Qwen2/assets/27985780/4c596f3e-c76b-4cb8-a175-5562c00267a2)
