### ISSUE TITLE
`Qwen2ForSequenceClassification` - What is the correct `pad_token_id` to use with `Qwen2ForSequenceClassification`?

### ISSUE THREAD

**Issue by RylanSchaeffer** [QwenLM/Qwen2#747]
In order to use `Qwen2ForSequenceClassification` , the `pad_token_id` must be set: https://github.com/huggingface/transformers/blob/main/src/transformers/models/qwen2/modeling_qwen2.py#L1418-L1419

What is the correct `pad_token_id` to use with `Qwen/Qwen2-7B-Instruct`?

**Comment by jklj077** [comment]
the docstring of the class says that it uses the last token of a sequence, and pad_token is only used to identify the last token, so i think you could set pad_token to <|endoftext|>.
