### ISSUE TITLE
请问开源的qwen2-72B-instruct是经过role play训练的吗

### ISSUE THREAD

**Issue by wanghao07456** [QwenLM/Qwen2#749]
rt，请教下，开源的qwen2-72B-instruct是不是已经经过了角色扮演的训练，也就是通过DITTO的方式，已经具备了一定的角色扮演能力？如果是的话，想请问下训练方式和语料支持英文了吗，多谢

**Comment by jklj077** [comment]
you are right in the sense that it supports role playing. English is supported.
