### ISSUE TITLE
相对qwen 1的改进

### ISSUE THREAD

**Issue by cdhx** [QwenLM/Qwen2#751]
目前好像只有qwen1的技术报告，想问下有那里可以找到qwen 2 的新改进吗，比如官方初步的blog，性能提升挺明显的，期待看到qwen 2的技术报告~

**Comment by Luoyang144** [comment]
您好请问您找到blog了吗

**Comment by jklj077** [comment]
blog is at https://qwenlm.github.io/blog/qwen2/
