### ISSUE TITLE
使用vllm部署qwen1.5后推理回答结果会出现截断

### ISSUE THREAD

**Issue by zhangshuyx** [QwenLM/Qwen2#752]
<img width="668" alt="image" src="https://github.com/QwenLM/Qwen2/assets/4592428/0b77b81b-3378-4848-9b9e-2a20f1779b97">

输入参数为：
```
{
  "model": "Qwen1_5_72B_Chat",
  "messages": [{"role": "user","content": "请给出一篇500字的中学作文，讲述海边游玩的经历"}],
  "max_tokens": 2000, 
  "stop": []
}
```

也尝试了不同的参数，但是不管输出内容长短 都会截断，导致回答不完整
最明显的是这个回答，我要求列出1到20的所有数字 输出也是截断：

![image](https://github.com/QwenLM/Qwen2/assets/4592428/35b1ea1b-9851-4167-a85f-1c4966b77aec)

输入参数为：
```
{
  "model": "Qwen1_5_72B_Chat",
  "messages": [{"role": "user","content": "请列出1到20的所有数字"}],
  "max_tokens": 1200, 
  "stop":["<|im_end|>", "<|endoftext|>", "<|im_start|>"],
  "stream":"False",
  "temperature":0.7
}
```

**Comment by jklj077** [comment]
the completion_tokens in usage did not match the number of tokens in choices[0].messages.content. it appears some tokens are lost. could you try reporting the issue to vllm?

**Comment by yoke233** [comment]
最新的 vllm==0.5.3.post1 遇到同样问题, 只能回退到 之前使用的版本vllm==0.4.0.post1
