### ISSUE TITLE
使用量化模型，输出错误。

### ISSUE THREAD

**Issue by eekarot** [QwenLM/Qwen2#756]
按照官方教程，输出全是！！！！！！！！！！！！！！！！！！！！！！！！
![image](https://github.com/QwenLM/Qwen2/assets/32899980/2f4b3eab-3d72-41d4-aca5-ce0c02d2f913)
![image](https://github.com/QwenLM/Qwen2/assets/32899980/1360578a-8607-4807-8204-3ac2113b2d1a)
加载权重时，报warning：
![image](https://github.com/QwenLM/Qwen2/assets/32899980/360642da-2aa5-49f7-b35f-6399aafa5acf)
请问这是什么原因呢？

**Comment by jklj077** [comment]
- https://github.com/QwenLM/Qwen2/issues/567
- https://github.com/QwenLM/Qwen2/issues/714

**Comment by lijiayi980130** [comment]
I have the same problem
