### ISSUE TITLE
How to return response in Japanese?

### ISSUE THREAD

**Issue by yudataguy** [QwenLM/Qwen2#757]
Hello, I've tried both English and Japanese system prompt, specifically ask it to return response in Japanese. But I always getting English responses. What system prompt should I use for it to return response consistently in Japanese? 

current system prompt:
`A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions. Please answer in Japanese. `
or
`あなたは誠実で優秀な日本人のアシスタントです。特に指示が無い場合は、常に日本語で回答してください。`

**Comment by jklj077** [comment]
which models were you using?

it appears to work on my end (with Qwen2-72B-Instruct)

![image](https://github.com/QwenLM/Qwen2/assets/17811943/ebe3a646-1785-4e51-83fc-760ba1c70f27)

![image](https://github.com/QwenLM/Qwen2/assets/17811943/09fe30eb-4822-4ed0-9868-5d8298d70f15)

![image](https://github.com/QwenLM/Qwen2/assets/17811943/6de4a2d7-36f9-4ac7-ae90-72fb5afddbe2)

![image](https://github.com/QwenLM/Qwen2/assets/17811943/34088222-996c-4c83-8275-002ee817a95b)

**Comment by jklj077** [comment]
Qwen uses the ChatML template. The system message is a message with the role system: 
```
<|im_start|>{{- role }}\n{{- content }}<|im_end|>
```
Actually, the chat template is in the model files (tokenizer_config.json) and vllm is able to load from it.
