### ISSUE TITLE
GGUF int4（qwen2:72b） Model issue

### ISSUE THREAD

**Issue by Snow9666** [QwenLM/Qwen2#758]
按以下问题一个一个问，最后一轮就会一直生成句子不会停
1. 我叫 snow
2. 嗯，你好，我叫什么
3. 我叫什么
4. 我叫什么
5. 秦始皇是谁，有老婆么？他老婆是谁？
6. 我是谁
7. 我是谁？

<img width="1005" alt="image" src="https://github.com/QwenLM/Qwen2/assets/72625423/2b1d853b-3e6d-4da2-a09e-90eadc3adf37">

**Comment by jklj077** [comment]
Hi, I was unable to reproduce this with ollama run qwen2:72b. what generation parameters were you using?

```
$ ollama run qwen2:72b
>>> 我叫 snow
很高兴认识你，Snow！有什么可以帮助你的吗？无论是问题解答、聊天或是需要一
些建议，我都愿意尽力帮助。请随时告诉我你的需求或想法。😊

>>> 嗯，你好，我叫什么
你之前提到你叫 Snow。所以，你的名字是Snow。如果有其他事情你需要帮忙的，
请尽管告诉我！

>>> 我叫什么
在我们之前的对话中，你说过你的名字是Snow。如果你现在在询问另一个身份或者
是在开玩笑，那么请提供更多信息以便我能更好地回答你。否则，根据我们的对话
记录，你的名字就是Snow。如果有任何其他问题或需要帮助的地方，请随时告诉我
！😊

如果这里存在混淆，而你在寻求一个更广泛的答案（例如，想知道如何找到自己的
名字），那么我需要更多的上下文来给出恰当的回复。在通常情况下，一个人的名
字是由其父母或者监护人在他们出生后不久给予的，并记录在官方文件如出生证明
上。如果你对自己的名字有疑问或不确定，你可以查看这些官方文件、询问家人或
是查阅家族记录以确认你的名字。

然而，在我们的对话中，我们已经确定你之前告诉过我你的名字是Snow，除非另有
说明，这应该是正确的。如果有其他问题或者需要进一步的帮助，请告诉我！

>>> 我叫什么
在我们的交流中，你曾提到自己的名字叫做Snow。如果你是在询问别的事情或有其
它的含义，请提供更多的信息。根据我们之前的对话，你的名字是Snow。如果还有
其他问题或是需要帮助的地方，随时可以告诉我。如果有任何身份上的疑问或者是
在开玩笑，也请告知具体的情况以便于我更好地回答你。😊

>>> 秦始皇是谁，有老婆么？他老婆是谁？
秦始皇（公元前259年—公元前210年），名嬴政，是战国时期秦国的国王，在统一
六国后成为中国历史上第一个封建皇帝，建立了中国第一个中央集权的大一统王朝
——秦朝。他是中国历史上的重要人物之一，对中国古代政治、军事和文化产生了深
远影响。

关于秦始皇是否有妻子的问题，历史上确实存在有关他的后宫记载，但具体的名字
大多已经失传。秦始皇后宫中的女性众多，其中最著名的可能要数赵姬，即秦始皇
的母亲。但是，作为皇帝的妻子或正式的皇后，在历史文献中并没有留下特别详细
的信息。

根据《史记》等古代典籍记载，秦始皇有多个儿子和女儿，这表明他肯定有过至少
一位妻子或是嫔妃生下这些子女。然而，具体哪位女性是他的正妻或者最受宠幸的
妻子，则没有明确的记载。在历史研究中，学者们普遍认为秦始皇有多位嫔妃，但
对她们的身份、名字以及地位了解不多。

秦朝建立后，尽管实行了严密的宫廷制度和礼仪规范，但对于皇帝家事特别是女性
成员的具体情况记录并不详尽。因此，在现代史学界关于秦始皇妻妾及其子女的信
息仍然相当有限，许多细节至今无法确定。

总之，秦始皇确实有妻子和嫔妃，并育有多名子女，但具体哪些女性是他的正式配
偶或最受宠爱者，历史上并未留下确切的名字和详细信息。
如果有其他问题或者需要了解更多的历史知识，请随时告诉我。😊

>>> 我是谁
在我们的对话中，你之前提到你的名字叫Snow。当然，在互联网上，我们主要通过
用户名、昵称或自我介绍来认识彼此。如果你是在询问一个更深刻的身份问题
——“我是谁”是哲学和心理学上的一个重要主题，涉及到个人身份、意识、价值观等
方面——那么这个问题的答案会非常个性化，并且可能需要深入的思考和个人探索。


在日常对话中，“我是谁”往往指的是你的名字或你希望别人称呼的方式。基于我们
之前的交流，我知道你是Snow。如果你是在探讨更深层次的身份问题，请分享更多
的细节或者具体的想法，我很愿意从哲学、心理学或者其他相关领域的角度帮助你
进一步探讨这个问题。😊

如果这是关于确认身份的信息请求（例如，在一个安全的环境中），请提供上下文
或要求的具体信息以便于我能够适当地回答你的需求。
如果有其他问题或是需要帮助的地方，请随时告诉我！

>>> 我是谁？
这是一个深刻的问题，通常涉及个人身份、自我认知和存在的哲学探讨。在日常交
流中，“我是谁”往往指的是我们的名字或社会角色。但在更深层次上，这个问题可
能触及到我们个体的本质、价值观、信仰体系以及我们在宇宙中的位置。

如果从字面意义上来理解你的问题，在我们之前的对话里你曾说自己的名字是
Snow。但从哲学角度来看，你是谁包含了许多层面的意义：

1. **身份**：这包括你的姓名、职业、家庭成员角色等社会属性。
2. **个性和特质**：你的性格特点、兴趣爱好、才能以及你对待生活的方式。
3. **信念与价值观**：你对世界的看法，你认为重要的事情，你的道德准则或信
仰体系。
4. **经历与回忆**：你的过去塑造了现在的你，包括你遇到的人、去过的地方和
经历过的事情。
5. **未来目标与梦想**：你对未来的期望、计划以及你希望实现的目标。

每个人对于“我是谁”的回答都是独一无二的。它是一个持续演变的过程，随着我们
的成长、学习和经历而不断变化。如果这是你在探索自我认知旅程中的一个起点，
那么恭喜你，这是一段非常有意义且充满发现的过程。如果你愿意分享更多关于自
己的思考或问题，我很乐意提供支持与洞察。

当然，如果这个问题的提出仅仅是为了确认你的名字或某种身份标识，请记得我们
之前了解到你是Snow。如果有更深层次的探索需求或是其他问题想要讨论，随时告
诉我！😊

希望这能够帮助你开始一段自我发现之旅，或者解答了你心中那个“我是谁”的疑问
。无论在哪个层面上，“我是谁”都是一个值得深思的问题。如果你还有其他想要探
讨的话题，请随时与我分享。
如果有任何需要帮助的地方或想继续讨论的话题，请告诉我！
```

**Comment by llmforever** [comment]
> Hi, I was unable to reproduce this with ollama run qwen2:72b. what generation parameters were you using?
> 
> ```
> $ ollama run qwen2:72b
> >>> 我叫 snow
> 很高兴认识你，Snow！有什么可以帮助你的吗？无论是问题解答、聊天或是需要一
> 些建议，我都愿意尽力帮助。请随时告诉我你的需求或想法。😊
> 
> >>> 嗯，你好，我叫什么
> 你之前提到你叫 Snow。所以，你的名字是Snow。如果有其他事情你需要帮忙的，
> 请尽管告诉我！
> 
> >>> 我叫什么
> 在我们之前的对话中，你说过你的名字是Snow。如果你现在在询问另一个身份或者
> 是在开玩笑，那么请提供更多信息以便我能更好地回答你。否则，根据我们的对话
> 记录，你的名字就是Snow。如果有任何其他问题或需要帮助的地方，请随时告诉我
> ！😊
> 
> 如果这里存在混淆，而你在寻求一个更广泛的答案（例如，想知道如何找到自己的
> 名字），那么我需要更多的上下文来给出恰当的回复。在通常情况下，一个人的名
> 字是由其父母或者监护人在他们出生后不久给予的，并记录在官方文件如出生证明
> 上。如果你对自己的名字有疑问或不确定，你可以查看这些官方文件、询问家人或
> 是查阅家族记录以确认你的名字。
> 
> 然而，在我们的对话中，我们已经确定你之前告诉过我你的名字是Snow，除非另有
> 说明，这应该是正确的。如果有其他问题或者需要进一步的帮助，请告诉我！
> 
> >>> 我叫什么
> 在我们的交流中，你曾提到自己的名字叫做Snow。如果你是在询问别的事情或有其
> 它的含义，请提供更多的信息。根据我们之前的对话，你的名字是Snow。如果还有
> 其他问题或是需要帮助的地方，随时可以告诉我。如果有任何身份上的疑问或者是
> 在开玩笑，也请告知具体的情况以便于我更好地回答你。😊
> 
> >>> 秦始皇是谁，有老婆么？他老婆是谁？
> 秦始皇（公元前259年—公元前210年），名嬴政，是战国时期秦国的国王，在统一
> 六国后成为中国历史上第一个封建皇帝，建立了中国第一个中央集权的大一统王朝
> ——秦朝。他是中国历史上的重要人物之一，对中国古代政治、军事和文化产生了深
> 远影响。
> 
> 关于秦始皇是否有妻子的问题，历史上确实存在有关他的后宫记载，但具体的名字
> 大多已经失传。秦始皇后宫中的女性众多，其中最著名的可能要数赵姬，即秦始皇
> 的母亲。但是，作为皇帝的妻子或正式的皇后，在历史文献中并没有留下特别详细
> 的信息。
> 
> 根据《史记》等古代典籍记载，秦始皇有多个儿子和女儿，这表明他肯定有过至少
> 一位妻子或是嫔妃生下这些子女。然而，具体哪位女性是他的正妻或者最受宠幸的
> 妻子，则没有明确的记载。在历史研究中，学者们普遍认为秦始皇有多位嫔妃，但
> 对她们的身份、名字以及地位了解不多。
> 
> 秦朝建立后，尽管实行了严密的宫廷制度和礼仪规范，但对于皇帝家事特别是女性
> 成员的具体情况记录并不详尽。因此，在现代史学界关于秦始皇妻妾及其子女的信
> 息仍然相当有限，许多细节至今无法确定。
> 
> 总之，秦始皇确实有妻子和嫔妃，并育有多名子女，但具体哪些女性是他的正式配
> 偶或最受宠爱者，历史上并未留下确切的名字和详细信息。
> 如果有其他问题或者需要了解更多的历史知识，请随时告诉我。😊
> 
> >>> 我是谁
> 在我们的对话中，你之前提到你的名字叫Snow。当然，在互联网上，我们主要通过
> 用户名、昵称或自我介绍来认识彼此。如果你是在询问一个更深刻的身份问题
> ——“我是谁”是哲学和心理学上的一个重要主题，涉及到个人身份、意识、价值观等
> 方面——那么这个问题的答案会非常个性化，并且可能需要深入的思考和个人探索。
> 
> 
> 在日常对话中，“我是谁”往往指的是你的名字或你希望别人称呼的方式。基于我们
> 之前的交流，我知道你是Snow。如果你是在探讨更深层次的身份问题，请分享更多
> 的细节或者具体的想法，我很愿意从哲学、心理学或者其他相关领域的角度帮助你
> 进一步探讨这个问题。😊
> 
> 如果这是关于确认身份的信息请求（例如，在一个安全的环境中），请提供上下文
> 或要求的具体信息以便于我能够适当地回答你的需求。
> 如果有其他问题或是需要帮助的地方，请随时告诉我！
> 
> >>> 我是谁？
> 这是一个深刻的问题，通常涉及个人身份、自我认知和存在的哲学探讨。在日常交
> 流中，“我是谁”往往指的是我们的名字或社会角色。但在更深层次上，这个问题可
> 能触及到我们个体的本质、价值观、信仰体系以及我们在宇宙中的位置。
> 
> 如果从字面意义上来理解你的问题，在我们之前的对话里你曾说自己的名字是
> Snow。但从哲学角度来看，你是谁包含了许多层面的意义：
> 
> 1. **身份**：这包括你的姓名、职业、家庭成员角色等社会属性。
> 2. **个性和特质**：你的性格特点、兴趣爱好、才能以及你对待生活的方式。
> 3. **信念与价值观**：你对世界的看法，你认为重要的事情，你的道德准则或信
> 仰体系。
> 4. **经历与回忆**：你的过去塑造了现在的你，包括你遇到的人、去过的地方和
> 经历过的事情。
> 5. **未来目标与梦想**：你对未来的期望、计划以及你希望实现的目标。
> 
> 每个人对于“我是谁”的回答都是独一无二的。它是一个持续演变的过程，随着我们
> 的成长、学习和经历而不断变化。如果这是你在探索自我认知旅程中的一个起点，
> 那么恭喜你，这是一段非常有意义且充满发现的过程。如果你愿意分享更多关于自
> 己的思考或问题，我很乐意提供支持与洞察。
> 
> 当然，如果这个问题的提出仅仅是为了确认你的名字或某种身份标识，请记得我们
> 之前了解到你是Snow。如果有更深层次的探索需求或是其他问题想要讨论，随时告
> 诉我！😊
> 
> 希望这能够帮助你开始一段自我发现之旅，或者解答了你心中那个“我是谁”的疑问
> 。无论在哪个层面上，“我是谁”都是一个值得深思的问题。如果你还有其他想要探
> 讨的话题，请随时与我分享。
> 如果有任何需要帮助的地方或想继续讨论的话题，请告诉我！
> ```

似乎qwen2 72b instruct原版及各种量化版本都有可能出现这个问题，尝试了多组生成参数、多版本模型和多种推理框架都有类似问题，相比而言，qwen2 7b基本没有出现该问题，这里最近有什么进展吗？

**Comment by Snow9666** [comment]
> Hi, I was unable to reproduce this with ollama run qwen2:72b. what generation parameters were you using?
> 
> ```
> $ ollama run qwen2:72b
> >>> 我叫 snow
> 很高兴认识你，Snow！有什么可以帮助你的吗？无论是问题解答、聊天或是需要一
> 些建议，我都愿意尽力帮助。请随时告诉我你的需求或想法。😊
> 
> >>> 嗯，你好，我叫什么
> 你之前提到你叫 Snow。所以，你的名字是Snow。如果有其他事情你需要帮忙的，
> 请尽管告诉我！
> 
> >>> 我叫什么
> 在我们之前的对话中，你说过你的名字是Snow。如果你现在在询问另一个身份或者
> 是在开玩笑，那么请提供更多信息以便我能更好地回答你。否则，根据我们的对话
> 记录，你的名字就是Snow。如果有任何其他问题或需要帮助的地方，请随时告诉我
> ！😊
> 
> 如果这里存在混淆，而你在寻求一个更广泛的答案（例如，想知道如何找到自己的
> 名字），那么我需要更多的上下文来给出恰当的回复。在通常情况下，一个人的名
> 字是由其父母或者监护人在他们出生后不久给予的，并记录在官方文件如出生证明
> 上。如果你对自己的名字有疑问或不确定，你可以查看这些官方文件、询问家人或
> 是查阅家族记录以确认你的名字。
> 
> 然而，在我们的对话中，我们已经确定你之前告诉过我你的名字是Snow，除非另有
> 说明，这应该是正确的。如果有其他问题或者需要进一步的帮助，请告诉我！
> 
> >>> 我叫什么
> 在我们的交流中，你曾提到自己的名字叫做Snow。如果你是在询问别的事情或有其
> 它的含义，请提供更多的信息。根据我们之前的对话，你的名字是Snow。如果还有
> 其他问题或是需要帮助的地方，随时可以告诉我。如果有任何身份上的疑问或者是
> 在开玩笑，也请告知具体的情况以便于我更好地回答你。😊
> 
> >>> 秦始皇是谁，有老婆么？他老婆是谁？
> 秦始皇（公元前259年—公元前210年），名嬴政，是战国时期秦国的国王，在统一
> 六国后成为中国历史上第一个封建皇帝，建立了中国第一个中央集权的大一统王朝
> ——秦朝。他是中国历史上的重要人物之一，对中国古代政治、军事和文化产生了深
> 远影响。
> 
> 关于秦始皇是否有妻子的问题，历史上确实存在有关他的后宫记载，但具体的名字
> 大多已经失传。秦始皇后宫中的女性众多，其中最著名的可能要数赵姬，即秦始皇
> 的母亲。但是，作为皇帝的妻子或正式的皇后，在历史文献中并没有留下特别详细
> 的信息。
> 
> 根据《史记》等古代典籍记载，秦始皇有多个儿子和女儿，这表明他肯定有过至少
> 一位妻子或是嫔妃生下这些子女。然而，具体哪位女性是他的正妻或者最受宠幸的
> 妻子，则没有明确的记载。在历史研究中，学者们普遍认为秦始皇有多位嫔妃，但
> 对她们的身份、名字以及地位了解不多。
> 
> 秦朝建立后，尽管实行了严密的宫廷制度和礼仪规范，但对于皇帝家事特别是女性
> 成员的具体情况记录并不详尽。因此，在现代史学界关于秦始皇妻妾及其子女的信
> 息仍然相当有限，许多细节至今无法确定。
> 
> 总之，秦始皇确实有妻子和嫔妃，并育有多名子女，但具体哪些女性是他的正式配
> 偶或最受宠爱者，历史上并未留下确切的名字和详细信息。
> 如果有其他问题或者需要了解更多的历史知识，请随时告诉我。😊
> 
> >>> 我是谁
> 在我们的对话中，你之前提到你的名字叫Snow。当然，在互联网上，我们主要通过
> 用户名、昵称或自我介绍来认识彼此。如果你是在询问一个更深刻的身份问题
> ——“我是谁”是哲学和心理学上的一个重要主题，涉及到个人身份、意识、价值观等
> 方面——那么这个问题的答案会非常个性化，并且可能需要深入的思考和个人探索。
> 
> 
> 在日常对话中，“我是谁”往往指的是你的名字或你希望别人称呼的方式。基于我们
> 之前的交流，我知道你是Snow。如果你是在探讨更深层次的身份问题，请分享更多
> 的细节或者具体的想法，我很愿意从哲学、心理学或者其他相关领域的角度帮助你
> 进一步探讨这个问题。😊
> 
> 如果这是关于确认身份的信息请求（例如，在一个安全的环境中），请提供上下文
> 或要求的具体信息以便于我能够适当地回答你的需求。
> 如果有其他问题或是需要帮助的地方，请随时告诉我！
> 
> >>> 我是谁？
> 这是一个深刻的问题，通常涉及个人身份、自我认知和存在的哲学探讨。在日常交
> 流中，“我是谁”往往指的是我们的名字或社会角色。但在更深层次上，这个问题可
> 能触及到我们个体的本质、价值观、信仰体系以及我们在宇宙中的位置。
> 
> 如果从字面意义上来理解你的问题，在我们之前的对话里你曾说自己的名字是
> Snow。但从哲学角度来看，你是谁包含了许多层面的意义：
> 
> 1. **身份**：这包括你的姓名、职业、家庭成员角色等社会属性。
> 2. **个性和特质**：你的性格特点、兴趣爱好、才能以及你对待生活的方式。
> 3. **信念与价值观**：你对世界的看法，你认为重要的事情，你的道德准则或信
> 仰体系。
> 4. **经历与回忆**：你的过去塑造了现在的你，包括你遇到的人、去过的地方和
> 经历过的事情。
> 5. **未来目标与梦想**：你对未来的期望、计划以及你希望实现的目标。
> 
> 每个人对于“我是谁”的回答都是独一无二的。它是一个持续演变的过程，随着我们
> 的成长、学习和经历而不断变化。如果这是你在探索自我认知旅程中的一个起点，
> 那么恭喜你，这是一段非常有意义且充满发现的过程。如果你愿意分享更多关于自
> 己的思考或问题，我很乐意提供支持与洞察。
> 
> 当然，如果这个问题的提出仅仅是为了确认你的名字或某种身份标识，请记得我们
> 之前了解到你是Snow。如果有更深层次的探索需求或是其他问题想要讨论，随时告
> 诉我！😊
> 
> 希望这能够帮助你开始一段自我发现之旅，或者解答了你心中那个“我是谁”的疑问
> 。无论在哪个层面上，“我是谁”都是一个值得深思的问题。如果你还有其他想要探
> 讨的话题，请随时与我分享。
> 如果有任何需要帮助的地方或想继续讨论的话题，请告诉我！
> ```

Sorry for late response. I tested it using Open WebUI and I did't set any optional setting such as temperature, top-k and so on. I suppose it uses default model setting.
