### ISSUE TITLE
qwen2-7b(或instruct),  float16精度的generate方法输出都是感叹号,  其它精度正常

### ISSUE THREAD

**Issue by sean-wade** [QwenLM/Qwen2#761]
![image](https://github.com/QwenLM/Qwen2/assets/42532862/cfe20ac1-5548-4cba-9f6d-36fba4849cd1)

如上图所示,  float16输出都是感叹号

![image](https://github.com/QwenLM/Qwen2/assets/42532862/1e4f86d3-2b33-4901-a076-7fc8c51ef671)
上图是bfloat16, 正常输出没有问题

代码就是readme中的example, 初步看了下, 好像fp16的logits中有很多nan值

**Comment by jklj077** [comment]
1. if you could run with bfloat16, please run with bfloat16
2. if you must run with float16, please try [this branch](https://github.com/jklj077/transformers/tree/qwen2-patch) and set attn_implementation="eager".

**Comment by sean-wade** [comment]
> 1. if you could run with bfloat16, please run with bfloat16
> 2. if you must run with float16, please try [this branch](https://github.com/jklj077/transformers/tree/qwen2-patch) and set attn_implementation="eager".

OK, thanks for reply. Is there any explanation about this problem? It will help me saving time to trace it.

**Comment by HalvesChen** [comment]
> > 1. if you could run with bfloat16, please run with bfloat16
> > 2. if you must run with float16, please try [this branch](https://github.com/jklj077/transformers/tree/qwen2-patch) and set attn_implementation="eager".
> 
> OK, thanks for reply. Is there any explanation about this problem? It will help me saving time to trace it.

你换成作者提供的transformer版本后可以用fp16推理或者训练吗？

**Comment by gg22mm** [comment]
model = AutoModelForCausalLM.from_pretrained("models/Qwen/Qwen1.5-7B-Chat",torch_dtype=torch.float16, device_map="auto") #即可解决
