### ISSUE TITLE
After executing 'qwen2', I interacted with it by posing several queries. Upon exiting the session and attempting to relaunch 'qwen2', I encountered an error

### ISSUE THREAD

**Issue by 20190441309** [QwenLM/Qwen2#767]
After executing 'qwen2', I interacted with it by posing several queries. Upon exiting the session and attempting to relaunch 'qwen2', I encountered an error
![71c4326d8538c2e646820db12aa5a08](https://github.com/QwenLM/Qwen2/assets/56188085/cf9b9134-f033-430e-a42c-61435a480834)
But the 'history' file does exist, and I am able to see its contents
![f9b98c4bee21bea2bf098c836159418](https://github.com/QwenLM/Qwen2/assets/56188085/ee0f2f6f-9073-4f70-8fba-73331e2a9925)
I'm not sure how to resolve this issue, seeking help from experienced individuals

**Comment by jklj077** [comment]
hi, have you tried restarting the ollama service? `sudo systemctl restart ollama`

**Comment by 20190441309** [comment]
> hi, have you tried restarting the ollama service? `sudo systemctl restart ollama`

Thank you, but I'm using a cloud server from a supercomputing platform, and I don't have root permissions, so I can't use the systemctl command. This solution won't work for me.
