### ISSUE TITLE
确定种子前提无法固定输出

### ISSUE THREAD

**Issue by icefairy** [QwenLM/Qwen2#769]
运行框架使用的ollama v0.2.1
请求参数中固定的seed和temperature 但输出结果不同，实测运行100次只有55次和第一次返回结果相同，另外45次的结果相比第一次会多一些其他内容；同样的请求参数情况用llama3也有一样的情况，但使用glm4:9b的版本 100次都会返回一模一样的。

```
{"model":"qwen2:7b","options":{"temperature":0.0,"seed":1,"num_keep":1,"num_ctx":2048},"stream":false,"messages":[{"role":"user","content":"从下文中提取(举报方式、举报电话)用中文表达并以json格式返回，需要提取的内容是：常态化扫黑除恶斗争以来，汕尾市公安机关持续对涉黑恶违法犯罪保持严打高压态势。近期，汕尾市纪委监委联合汕尾市公安局成功打掉陈水团等人犯罪团伙，抓获了陈水团、陈水胜、陈水荣、陈建圳、陈木蕊等违法犯罪人员共5人。  经进一步侦查发现，该犯罪团伙在陆丰铜锣湖等地长期实施多宗非法经营、窝藏等违法犯罪活动。为维护国家集体利益和人民生命财产安全，严厉打击违法犯罪行为，现就有关事项通告如下：  一、欢迎广大群众检举揭发陈水团及其犯罪团伙的违法犯罪线索，积极举报反映情况，公安机关将依法保护举报人的个人隐私和合法权益，并按照相关规定给予奖励。  二、公安机关敦促该犯罪团伙的在逃违法犯罪人员尽早向公安机关投案自首，争取宽大处理，到案后情节显著轻微或有重大立功表现的，可以依法从轻、减轻或者免除处罚。  三、凡帮助在逃人员藏匿、逃跑或者协助毁灭、伪造证据以及掩饰、隐瞒犯罪所得、犯罪所得收益的，公安机关将依法追究刑事责任。  四、凡是对举报人、证人进行威胁、恐吓、打击报复的，公安机关将依法从严从重惩处。  举报方式：电话、邮寄、邮箱或直接到公安机关举报  举报电话：19928530819（彭警官），19926991248（姚警官）  受理举报部门：汕尾市公安局扫黑办  邮寄地址：汕尾市公安局扫黑办（汕尾市城区红海中路）  邮政编码：516600"}]}
```

**Comment by jklj077** [comment]
did you use GPUs or was it running with CPUs

**Comment by icefairy** [comment]
gpu device: NVIDIA TITAN RTX 24G

**Comment by jklj077** [comment]
small variations with GPU is expected for Qwen2 models due to the floating point arithmetics. there is not much can be done. 

if the variation is significant, what is the extra content you do not want?

**Comment by icefairy** [comment]
What extra content is not important; what matters is that the model does not follow the rules and should output the same content multiple times.

**Comment by jklj077** [comment]
then you should use a framework and hardware that can produce deterministic output (bf16 on latest vllm for example)

**Comment by jklj077** [comment]
as ollama uses llama.cpp, you can also refer to the issue at <https://www.github.com/ggerganov/llama.cpp/issues/8593>
