### ISSUE TITLE
关于多机分布式训练部署问题

### ISSUE THREAD

**Issue by JACKzhuz** [QwenLM/Qwen2#775]
目前我看了咱们qwen2的readme，并没有看到一些关于咱们多太机器以及多卡的分布式训练的方式以及命令，可以更新一下这类的readme吗？

**Comment by jklj077** [comment]
the finetune script mostly uses accelerate to handle distributed training and it does support multi-gpu on multi-node. please refer to accelerate's documentation: https://huggingface.co/docs/accelerate/basic_tutorials/launch#multi-node-training

**Comment by jklj077** [comment]
We advise you to use training frameworks, including [Axolotl](https://github.com/OpenAccess-AI-Collective/axolotl), [Llama-Factory](https://github.com/hiyouga/LLaMA-Factory), [Swift](https://github.com/modelscope/swift), etc., to finetune your models with SFT, DPO, PPO, etc.
