### ISSUE TITLE
What gpus can finetune qwen2 72B by using qlora?

### ISSUE THREAD

**Issue by mars-ch** [QwenLM/Qwen2#780]
Is 8*24G possible?

**Comment by mars-ch** [comment]
I read the previous issue and got the conclusion that qlora must load all model parameters on a single GPU, so as a result it is not possible to use 24G. Is this the right understanding?

Another question is that it doesn't make sense to fine-tune a model that has been quantized, such as int4, right? It can only be quantized by fintuning with lora or qlora and then awq or gptq.

**Comment by guotong1988** [comment]
same question
