### ISSUE TITLE
What is the difference between id_to_token() and decode() in tokenizer?

### ISSUE THREAD

**Issue by yileld** [QwenLM/Qwen2#782]
![6CDB801D-5CC9-481c-90B3-2035F015004E](https://github.com/user-attachments/assets/834db409-bb6e-421d-a630-e48551e78882)
If I use tokenizer.id_to_token(), the text is very strange, but if I use tokenizer.decode() to decode ids, the result is right. Are these two method different?

**Comment by zdxff** [comment]
decode会有special token的处理，在使用wordpiece、bpe分词的时候，能把带##的后缀拼接回去
