### ISSUE TITLE
Terminology can not be translated correctly

### ISSUE THREAD

**Issue by clearwater1990** [QwenLM/Qwen2#783]
model
model_name_or_path: model/Qwen2-7b-instruct

Task: translation

Prompt:
请按照专业的写作风格将下面专利内容翻译成英文，直接输出翻译结果，不要添加额外内容：
在一种可选地实现方式中，所述配置信息至少包括各用户分配的子载波的位置索引；所述根据OFDM子载波数和用户数，确定所述配置信息，包括：根据OFDM子载波数，采用二次多项式置换QPP交织器，所述QPP交织器输出伪随机序列；根据所述伪随机序列和所述用户数，确定各用户分配的子载波的位置索引。

Output:
In an optionally implemented embodiment, the configuration information at least comprises the position indices of subcarriers allocated to each user. The determination of the configuration information based on the number of OFDM subcarriers and the number of users includes: utilizing a quadratic polynomial permutation (QPP)交织器 with the number of OFDM subcarriers as input, which generates a pseudo-random sequence. Subsequently, based on this pseudo-random sequence and the number of users, the position indices of the subcarriers allocated to each user are determined.

Problem:
The term "QPP交织器" is not translated correctly. It should be "QPP interleaver" instead of "QPP交织器".

**Comment by jklj077** [comment]
![image](https://github.com/user-attachments/assets/5a287da2-7315-4580-aa1c-dddfc76d0028)

please provide steps to reproduce

**Comment by clearwater1990** [comment]
Yeah, i found the problem. I using LlamaFactory to start an api service and call by the openapi style. The temperature param was setted to 0. When modify it to 0.95, the problem was fixed.
![old](https://github.com/user-attachments/assets/c4218d55-6570-483e-9a7b-087b8ff6f31d)
![fix](https://github.com/user-attachments/assets/b9811c32-b53a-47c0-8e5c-c6ae6115a371)
