### ISSUE TITLE
gptq版本与vllm版本冲突问题

### ISSUE THREAD

**Issue by cbigeyes** [QwenLM/Qwen2#784]
请问一下我试用qwen2 int4 qptq，所需pytorch版本2.1或2.2，与vllm所需2.3相冲突，不知道如何解决，请教一下，谢谢

**Comment by jklj077** [comment]
install vllm in a separate environment (conda or virtualenv)

**Comment by cbigeyes** [comment]
> install vllm in a separate environment (conda or virtualenv)

我不太能理解，可以说的更具体一点不。我看操作指令 python -m vllm.entrypoints.openai.api_server --served-model-name Qwen2-72B-Instruct-GPTQ-Int4 --model path/to/weights，还是在具有vllm的环境下加载qwen2，那gptq的版本冲突也解决不了啊

**Comment by jklj077** [comment]
I cannot undestand your description either. just install vllm in a new environment as in <https://docs.vllm.ai/en/stable/getting_started/installation.html> and it will work. if you don't know how to use conda or virtual env, search the web.

GPTQ is an algorithm and it does not have requirements. if you mean auto_gptq, it is an implmentation of GPTQ and mostly relies on transformers. vllm has its own GPTQ implementation and you don't need auto_gptq.

**Comment by cbigeyes** [comment]
> I cannot undestand your description either. just install vllm in a new environment as in https://docs.vllm.ai/en/stable/getting_started/installation.html and it will work. if you don't know how to use conda or virtual env, search the web.
> 
> GPTQ is an algorithm and it does not have requirements. if you mean auto_gptq, it is an implmentation of GPTQ and mostly relies on transformers. vllm has its own GPTQ implementation and you don't need auto_gptq.

理解了，我试试
