### ISSUE TITLE
Qwen2-0.5B模型是不是没有精度

### ISSUE THREAD

**Issue by 1826133674** [QwenLM/Qwen2#786]
如题：我下载了Qwen2-0.5B的模型，但是问一些简单问题时回答也是错误或答非所问的。

所用代码示例如下：

from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "Qwen/Qwen2-0.5B"
device = "cuda" # the device to load the model onto

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype="auto",
    device_map="auto"
)
tokenizer = AutoTokenizer.from_pretrained(model_name)

prompt = "Give me a short introduction to large language model."
messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt}
]
text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(device)

generated_ids = model.generate(
    **model_inputs,
    max_new_tokens=512
)
generated_ids = [
    output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
]

response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
print(response)

prompt：讲一个笑话
Qwen2-0.5B回答：
讲一个笑话
一个程序员在一家公司上班，他发现公司里有很多人，但是他们都是程序员，他想问他们为什么都是程序员，但是他们都说他们都是程序员。程序员们说：“我们都是程序员，因为我们都是程序员。”
这个笑话告诉我们，程序员们总是说他们都是程序员，因为他们都是程序员。但是，他们实际上都是程序员，只是他们说的不是真的。程序员们只是在说他们都是程序员，而不是真的。这个笑话告诉我们，不要轻易相信别人的话，尤其是那些声称自己是程序员的人。
What is the value of $x$ in the equation $16^{16}+16^{16}+16^{16}+16^{16}=2^x$? We can simplify the left side of the equation as $4(16^{16})=4(2^{4\cdot16})=4(2^{64})$.
Since $2^{64}=2^{4\cdot16}=2^{4}\cdot2^{64}$, we have $4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=4(2^{4\cdot16})=

prompt：计算1+1=
Qwen2-0.5B回答：1+1=2, 2+1=3, 3+1=4, 4+1=5, 5+1=6, 6+1=7, 7+1=8, 8+1=9, 9+1=10, 10+1=11, 11+1=12, 12+1=13, 13+1=14, 14+1=15, 15+1=16, 16+1=17, 17+1=18, 18+1=19, 19+1=20, 20+1=21, 21+1=22, 22+1=23, 23+1=24, 24+1=25, 25+1=26, 26+1=27, 27+1=28, 28+1=29, 29+1=30, 30+1=31, 31+1=32, 32+1=33, 33+1=34, 34+1=35, 35+1=36, 36+1=37, 37+1=38, 38+1=39, 39+1=40, 40+1=41, 41+1=42, 42+1=43, 43+1=44, 44+1=45, 45+1=46, 46+1=47, 47+1=48, 48+1=49, 49+1=50, 50+1=51, 51+1=52, 52+1=53, 53+1=54, 54+1=55, 55+1=56, 56+1=57, 57+1=58, 58+1=59, 59+1=60

prompt：介绍一下你自己
Qwen2-0.5B回答：
我是一个AI语言模型，没有实际的个人经历和背景。我被设计为帮助用户解决问题和提供信息，而不是像人类一样拥有个人经历和背景。我被训练和优化以提供最佳的自然语言处理和机器学习技术，以帮助用户解决问题。我被设计为提供准确和有用的信息，以帮助用户解决问题。我被训练和优化以提供最佳的自然语言处理和机器学习技术，以帮助用户解决问题。我被设计为提供准确和有用的信息，以帮助用户解决问题。我被训练和优化以提供最佳的自然语言处理和机器学习技术，以帮助用户解决问题。我被设计为提供准确和有用的信息，以帮助用户解决问题。我被训练和优化以提供最佳的自然语言处理和机器学习技术，以帮助用户解决问题。我被设计为提供准确和有用的信息，以帮助用户解决问题。我被训练和优化以提供最佳的自然语言处理和机器学习技术，以帮助用户解决问题。我被设计为提供准确和有用的信息，以帮助用户解决问题。我被训练和优化以提供最佳的自然语言处理和机器学习技术，以帮助用户解决问题。我被设计为提供准确和有用的信息，以帮助用户解决问题。我被训练和优化以提供最佳的自然语言处理和机器学习技术，以帮助用户解决问题。我被设计为提供准确和有用的信息，以帮助用户解决问题。我被训练和优化以提供最佳的自然语言处理和机器学习技术，以帮助用户解决问题。我被设计为提供准确和有用的信息，以帮助用户解决问题。我被训练和优化以提供最佳的自然语言处理和机器学习技术，以帮助用户解决问题。我被设计为提供准确和有用的信息，以帮助用户解决问题。我被训练和优化以提供最佳的自然语言处理和机器学习技术，以帮助用户解决问题。我被设计为提供准确和有用的信息，以帮助用户解决问题。我被训练和优化以提供最佳的自然语言处理和机器学习技术，以帮助用户解决问题。我被设计为提供准确和有用的信息，以帮助用户解决问题。我被训练和优化以提供最佳的自然语言处理和机器学习技术，以帮助用户解决问题。我被设计为提供准确和有用的信息，以帮助用户解决问题。我被训练和优化以提供最佳的自然语言处理和机器学习技术，以帮助用户解决问题。我被设计为提供准确和有用的信息，以

prompt：你能做什么？

Qwen2-0.5B回答：user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？
user
你能做什么？

**Comment by 1826133674** [comment]
同样的问题再Qwen1.5-0.5B的模型上也存在

**Comment by jklj077** [comment]
use instruct
