### ISSUE TITLE
instruct和base模型区别是什么呢？微调应该采用哪个比较好？

### ISSUE THREAD

**Issue by yangkang2318** [QwenLM/Qwen2#788]
您好！
我想请问instruct模型和base模型的区别是什么？instruct模型是经过RLHF对齐了吗？base模型只是在数据上进行预训练吗？在下游任务上微调应该用哪一个比较好？
谢谢！

**Comment by jklj077** [comment]
please see the technical report for difference between base and instruct models.

for finetuning, you can use either the base or the instruct. but instruct should be easier for you to get started.

**Comment by yangkang2318** [comment]
@jklj077 请问是否可以根据公开的性能表现来选取用base模型和instruct模型。

**Comment by jklj077** [comment]
I don't think so. They are for different purposes.
