### ISSUE TITLE
如何微调base模型？

### ISSUE THREAD

**Issue by mars-ch** [QwenLM/Qwen2#789]
使用chat模型相同的方式微调，得到的结果会在<|im_end|>后继续生成微调出现过的数据。这是为什么呢？

**Comment by jklj077** [comment]
change eos_token eos_token_id in config.json generation_config.json to <|im_end|> 151645

**Comment by mars-ch** [comment]
谢谢您的回答。我还想知道的是如果不采用对话问答，而是文本生成的任务。应该如何设计数据格式以及如何进行微调呢？

**Comment by yangjianxin1** [comment]
> 谢谢您的回答。我还想知道的是如果不采用对话问答，而是文本生成的任务。应该如何设计数据格式以及如何进行微调呢？
麻烦你对该问题进行更详细的描述，或者举个例子。我猜测你想表达的是：让模型像base模型一样进行续写任务，而不是对话任务？

**Comment by mars-ch** [comment]
是的，如果不用对话数据来训练，而是输入文本等待模型续写，并且它知道在何时停止，这样应该如何做呢？On Aug 1, 2024, at 20:16, Yang JianXin ***@***.***> wrote:﻿

谢谢您的回答。我还想知道的是如果不采用对话问答，而是文本生成的任务。应该如何设计数据格式以及如何进行微调呢？

麻烦你对该问题进行更详细的描述，或者举个例子。我猜测你想表达的是：让模型像base模型一样进行续写任务，而不是对话任务？
