### ISSUE TITLE
文档“使用AutoAWQ量化你的模型”章节示范代码有误

### ISSUE THREAD

**Issue by Renpf2022** [QwenLM/Qwen2#790]
位置：https://qwen.readthedocs.io/zh-cn/latest/quantization/awq.html#quantize-your-own-model-with-autoawq
“““
data = []
for msg in messages:
    msg = c['messages']
    text = tokenizer.apply_chat_template(msg, tokenize=False, add_generation_prompt=False)
    data.append(text.strip())
”””
“msg = c['messages']”这句代码里的c在代码中是没有定义的

**Comment by jklj077** [comment]
Hi, good catch! this should be fixed in the latest docs.
