### ISSUE TITLE
sft 7B model_max_length=90000 24 A00 OOM

### ISSUE THREAD

**Issue by gk-cv** [QwenLM/Qwen2#794]
参考这里https://qwen.readthedocs.io/zh-cn/latest/training/SFT/example.html脚本

使用 24张A100，对7B sft，model_max_length超过2w时，OOM

**Comment by gk-cv** [comment]
请问配置问题吗

**Comment by jklj077** [comment]
I don't think it's a configuration issue per se. It's just that script is not expected to be used for finetuning in that scale. You'd be better use dedicated finetuning or frameworks as mentioned in the README. You may want to also try pretraining framework like mcore for that kind of finetuning.
