### ISSUE TITLE
Qwen2-7B 输出结果一直重复，只到max_new_tokens长度

### ISSUE THREAD

**Issue by shilei4260** [QwenLM/Qwen2#796]
我用的是Qwen2-7B 不是Qwen2-7B-Instruct 因为Qwen2-7B 是128k ,Qwen2-7B-Instruct 32k 用vllm推理Qwen2-7B默认的参数会一直重复直到max_new_tokens的长度，我修改tokenizer_config.json中eos_token为<|im_end|>后有时候还是会出现一直重复直到max_new_tokens的长度。
{'messages': [{'role': 'user', 'content': '1+1'}], 'model': 'Qwen2-7B', "stream":true,}
![Uploading 捕获2.JPG…]()

**Comment by shilei4260** [comment]
![捕获2](https://github.com/user-attachments/assets/ebcd665b-620c-4f87-9bba-e4cdfa3dd04f)

**Comment by jklj077** [comment]
use Qwen2-7B-Instruct and follow the steps in [the modelcard](https://huggingface.co/Qwen/Qwen2-7B-Instruct#processing-long-texts) to configure 128K sequence length.

**Comment by shilei4260** [comment]
谢谢

**Comment by 297106271** [comment]
解决了嘛 怎么修改 能告诉我下嘛
