### ISSUE TITLE
 是否有计划支持JSON MODE

### ISSUE THREAD

**Issue by FlowHS** [QwenLM/Qwen2#797]
类似于与openai的https://platform.openai.com/docs/guides/json-mode

**Comment by codewen77** [comment]
我也想知道 。

**Comment by DoiiarX** [comment]
> 如果是vllm的话，vllm自身就带json mode这个功能的。https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html 这个文档里搜索下json。
> 
> 如果是阿里云的模型服务的话，在开发中。

ollama都支持了，阿里云模型打算多久支持呢？

**Comment by jklj077** [comment]
百炼OpenAI兼容接口已支持。
