### ISSUE TITLE
我是用8张T4卡部署32B模型，为什么感觉处理会很慢呢？

### ISSUE THREAD

**Issue by DAAworld** [QwenLM/Qwen2#798]
CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7" python -m fastchat.serve.model_worker --model-path data/Qwen1.5-32B-Chat  --host 0.0.0.0 --dtype float16  --model-names   --gpus 8
我用上面的命令行启动大模型服务，但是我同时发送大约3-5个响应的时候，模型的返回就非常慢，感觉像是不支持多一点的并发一样，而且只有一两张卡的使用效率会达到七八十%，其余卡仿佛大概就10%左右，感觉在闲置，每个请求大约有1分钟的响应时间。是不是我的参数配置的不对呢？卡的使用效率太低了。

**Comment by jklj077** [comment]
use vllm

**Comment by DAAworld** [comment]
> use vllm

使用fastchat的vllmworker？

**Comment by jklj077** [comment]
hi, you can refer to the docs: https://qwen.readthedocs.io/zh-cn/latest/deployment/vllm.html

**Comment by DAAworld** [comment]
> hi, you can refer to the docs: https://qwen.readthedocs.io/zh-cn/latest/deployment/vllm.html

think
