### ISSUE TITLE
微调Qwen2-7B-Instruct，用的bf16，训练一段时间后loss=nan，请问这个有什么方法解决吗？

### ISSUE THREAD

**Issue by Alex-Songs** [QwenLM/Qwen2#799]
微调Qwen2-7B-Instruct，用的bf16，训练一段时间后loss=nan，请问这个有什么方法解决吗？

**Comment by jklj077** [comment]
Hi, any more info you could share? as a start, what is the finetuing framework you used? was the finetuning with lora?

**Comment by Alex-Songs** [comment]
@jklj077 yes， use deepspeed and lora
