### ISSUE TITLE
Can't find 'adapter_config.json'   用项目微调代码完成训练后，文件中包含有adapter_config.json但是一直提示找不到adapter_config.json。训练过程loss正常下降

### ISSUE THREAD

**Issue by zwt0204** [QwenLM/Qwen2#80]

**Comment by zwt0204** [comment]
![微信截图_20240223101439](https://github.com/QwenLM/Qwen1.5/assets/39355180/20be60e9-e396-4807-a74d-e033448b0b17)

**Comment by xiaoer2498** [comment]
请问这个问题解决了吗 我也遇到这个问题不知什么原因

**Comment by jklj077** [comment]
Please provide the code you used to load the model.

**Comment by geniusroad** [comment]
同问

**Comment by geniusroad** [comment]
去看你的配置文件llama3_lora_sft.yaml所在位置是否改变了原有的层级结构，然后看配置文件中的adapter_name_or_path配置的路径，如果是相对路径，即`saves/...`，那么要求llama3_lora_sft.yaml必须在`/LLaMA-Factory-main/examples/merge_lora`下，否则无法通过相对路径找到adapter_config.json，如果llama3_lora_sft.yaml已经改变了位置，adapter_name_or_path的路径必须是绝对路径
