### ISSUE TITLE
单机8卡A100-80G可以全参数训练qwen72b嘛？

### ISSUE THREAD

**Issue by NLPJCL** [QwenLM/Qwen2#804]
8 卡 a100 80g，zero 3 加上 CPU offload(优化器和模型都使用)，可以全量训练 72b 的模型吗？

我目前训练过程中遇到的错误是，应该是保存模型的时候，遇到这个错误了。
torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 0 (pid: 24418) of binary: /usr/bin/python

搜索发现是服务器内存不足导致的。但是我这边已经给docker分-shm-size 800G 。

**Comment by frankang** [comment]
模型参数（72*2 G）和梯度参数(72*2 G) 或许可以分布地放在显卡上。优化器用adam需要72 * 12 = 864G 显存/内存，800G还是太少了。

可以考虑类似Galore的算法
https://github.com/jiaweizzhao/GaLore

**Comment by NLPJCL** [comment]
batch size =4, sequence length =2560. This method mainly  needs large RAM in linux machine.

**Comment by NLPJCL** [comment]
> > 我这边跑起来了。 8 卡 a100 80g，zero 3 加上 CPU offload。内存不足的问题，可以把offload的pin_memory false来解决。
> 
> Hi, i am also interested in fine tuning Qwen2 72B.
> 
> What is your batch size and sequence length in your training period ?


batch size =4, sequence length =2560. This method mainly needs large RAM in linux machine.

**Comment by syspider** [comment]
> > > 我这边跑起来了。 8 卡 a100 80g，zero 3 加上 CPU offload。内存不足的问题，可以把offload的pin_memory false来解决。
> > 
> > 
> > Hi, i am also interested in fine tuning Qwen2 72B.
> > What is your batch size and sequence length in your training period ?
> 
> batch size =4, sequence length =2560. This method mainly needs large RAM in linux machine.

Thank you for the info !

By the way, do you use Qwen2 72B instruct (the original version) or Qwen2 72B intruct GPTQ Int4 (the quantized version) ?

**Comment by NLPJCL** [comment]
Qwen2 72B instruct (the original version)&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月1日(周四) 下午3:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [QwenLM/Qwen2] 单机8卡A100-80G可以全参数训练qwen72b嘛？ (Issue #804)




    
我这边跑起来了。 8 卡 a100 80g，zero 3 加上 CPU offload。内存不足的问题，可以把offload的pin_memory false来解决。
  
Hi, i am also interested in fine tuning Qwen2 72B.
 What is your batch size and sequence length in your training period ?
  
batch size =4, sequence length =2560. This method mainly needs large RAM in linux machine.
  
Thank you for the info !
 
By the way, do you use Qwen2 72B instruct (the original version) or Qwen2 72B intruct GPTQ Int4 (the quantized version) ?

**Comment by syspider** [comment]
> Qwen2 72B instruct (the original version)&nbsp;
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年8月1日(周四) 下午3:43 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [QwenLM/Qwen2] 单机8卡A100-80G可以全参数训练qwen72b嘛？ (Issue #804) 我这边跑起来了。 8 卡 a100 80g，zero 3 加上 CPU offload。内存不足的问题，可以把offload的pin_memory false来解决。 Hi, i am also interested in fine tuning Qwen2 72B. What is your batch size and sequence length in your training period ? batch size =4, sequence length =2560. This method mainly needs large RAM in linux machine. Thank you for the info ! By the way, do you use Qwen2 72B instruct (the original version) or Qwen2 72B intruct GPTQ Int4 (the quantized version) ? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

Really appreciate that.
