### ISSUE TITLE
qwen2-7b-instruct，作了SFT微调之后，在预测过程中，出现错误

### ISSUE THREAD

**Issue by QinHsiu** [QwenLM/Qwen2#808]
前面3600step预测正常
从3600step开始就预测报错，报错如下：
  File "/mnt/pfs/jinfeng_team/MMGroup/Yaguang/tool/miniconda3/envs/ragDemo/lib/python3.9/site-packages/transformers/generation/utils.py", line 1525, in generate
    return self.sample(
  File "/mnt/pfs/jinfeng_team/MMGroup/Yaguang/tool/miniconda3/envs/ragDemo/lib/python3.9/site-packages/transformers/generation/utils.py", line 2658, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
请问这种是因为数据集的原因吗，但是测试200step～3600step保存的模型都没有问题，可以正常预测结果
训练配置如下：

prompt_template = PROMPT_TEMPLATE.qwen_chat #llama2_chat
max_length = 4096
pack_to_max_length = True
batch_size = 1  # per_device
accumulative_counts = 4  # 1bs * 16acc * 4gpu = 64 batchsize
dataloader_num_workers = 0
max_epochs = 10
optim_type = AdamW
lr = 3e-4
betas = (0.9, 0.999)
weight_decay = 0
max_norm = 1  # grad clip
warmup_ratio = 0.01
save_steps = 200
save_total_limit = -1  # Maximum checkpoints to keep (-1 means unlimited)
evaluation_freq = 1000
SYSTEM = ''
evaluation_inputs = [
    'x + y = 5, x - y = 3'
]

请问这种原因可以怎么解决呢？

**Comment by jklj077** [comment]
Hi, it suggests traininig stability issues and it normally depends on how you finetune the model to find the way to mitgate the issue. without more information, lowering learning rate appears to be a reasonable starting point.

**Comment by QinHsiu** [comment]
> Hi, it suggests traininig stability issues and it normally depends on how you finetune the model to find the way to mitgate the issue. without more information, lowering learning rate appears to be a reasonable starting point.

Thank you!

**Comment by yangjianxin1** [comment]
如果是全量参数训练，3e-4的学习率大了些，可能会导致训练时梯度爆炸。建议考虑e-5或者e-6的学习率。

**Comment by QinHsiu** [comment]
非常感谢你的回复，我会先做尝试，后续如有问题再来请较，非常感谢！



---原始邮件---
发件人: "Yang ***@***.***&gt;
发送时间: 2024年8月1日(周四) 晚上6:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [QwenLM/Qwen2] qwen2-7b-instruct，作了SFT微调之后，在预测过程中，出现错误 (Issue #808)




 
如果是全量参数训练，3e-4的学习率大了些，可能会导致训练时梯度爆炸。建议考虑e-5或者e-6的学习率。
