### ISSUE TITLE
gte_Qwen2-7B-instruct能部署在ollama上吗？

### ISSUE THREAD

**Issue by CHNVigny** [QwenLM/Qwen2#811]
我用最新版本的llama.cpp转换得到了gte_Qwen2-7B-instruct的gguf文件，但是在ollama中加载的时候就会报错：
root@bccf6f1eb00f:/data/models# ollama create gte_qwen2:7b -f Modelfile
transferring model data 
Error: invalid file magic

我的ModelFile是：
FROM gte_qwen2.gguf
TEMPLATE "{{ if .Prompt }}<|im_start|>user
{{ .Prompt }}<|im_end|>
{{ end }}<|im_start|>assistant
{{ .Response }}<|im_end|>
"
PARAMETER stop <|im_start|>
PARAMETER stop <|im_end|>

**Comment by jklj077** [comment]
Hi, unfortunately, that model is not maintained by us and we don't exactly know how to help. But I think you could open an issue at the huggingface hub repo or the github ollama repo.
