### ISSUE TITLE
刚入坑，问下72B要多大GPU跑LoRA fine-tune

### ISSUE THREAD

**Issue by guotong1988** [QwenLM/Qwen2#813]
thank you very much!

**Comment by yangjianxin1** [comment]
具体可以参考LlamaFactory的估算，大约至少需要160GB的显存。如果是新手入坑，建议可以优先考虑从小参数量的模型开始训练，或者考虑更低成本的训练方法，例如QLoRA。
![image](https://github.com/user-attachments/assets/375fb9a7-6b1a-417e-b611-fd737521b2ca)
