### ISSUE TITLE
微调7B模型function calling的能力大概需要标注多少条数据

### ISSUE THREAD

**Issue by lifucong** [QwenLM/Qwen2#817]
微调7B模型function calling的能力大概需要标注多少条数据

**Comment by yangjianxin1** [comment]
可以尝试先标注两三千条数据，训练完后，模型会有一定的function call的能力。也可以先使用一些开源的function call数据做一些尝试，例如modelscope-agent开源的数据。

**Comment by yangjianxin1** [comment]
MSAgent-Bench数据：https://modelscope.cn/datasets/iic/MSAgent-Bench

**Comment by Linuxstyle** [comment]
微调时，需要多少GPU呢，我目前用了4块3090微调，提示我显存不足。
