### ISSUE TITLE
长文本sft

### ISSUE THREAD

**Issue by misaka23** [QwenLM/Qwen2#823]
请问，现有代码是否支持长文本的sft，32k长度的数据。

**Comment by jklj077** [comment]
hi, sorry for the inconvenience, but we are in the process of deprecating the examples/sft/finetune.py script. in the meantime, we advise you to use training frameworks, including Axolotl, Llama-Factory, Swift, etc., to finetune your models with SFT, DPO, PPO, etc. for your specific question, please refer to the documentation of those frameworks.
