### ISSUE TITLE
When I change the model from `Qwen1.5-7B-Chat` to `Qwen2-7B-Instruct`, the same error is still there.

### ISSUE THREAD

**Issue by chansonzhang** [QwenLM/Qwen2#827]
When I change the model from `Qwen1.5-7B-Chat` to `Qwen2-7B-Instruct`, the same error is still there.

_Originally posted by @chansonzhang in https://github.com/QwenLM/Qwen/issues/1307#issuecomment-2264659388_

**Comment by jklj077** [comment]
which finetune.py were you using? did you mix the use of Qwen and Qwen2 model and code?

**Comment by jklj077** [comment]
we are also in the process of deprecating the finetune.py in this repo and we advise you to use training frameworks, including [Axolotl](https://github.com/OpenAccess-AI-Collective/axolotl), [Llama-Factory](https://github.com/hiyouga/LLaMA-Factory), [Swift](https://github.com/modelscope/swift), etc., to finetune your models with SFT, DPO, PPO, etc.

**Comment by chansonzhang** [comment]
> which finetune.py were you using? did you mix the use of Qwen and Qwen2 model and code?

I'm using [Qwen/finetune.py](https://github.com/QwenLM/Qwen/blob/main/finetune.py).

I was finetuning Qwen 1.5 with model_max_length 32768, and encountered the [issue#1307](https://github.com/QwenLM/Qwen/issues/1307). 

I was wondering if it is a bug in Qwen 1.5 and perhaps already been solved in Qwen 2.0. So I tried with Qwen 2.0 by the way, and was not expecting it to work. 

However, the error messages and exception stacks are exactly the same when I changed the model. see [comment in issue#1307](https://github.com/QwenLM/Qwen/issues/1307#issuecomment-2264398936).

I want to know what caused this error and how can I work around it.

**Comment by chansonzhang** [comment]
> we are also in the process of deprecating the finetune.py in this repo and we advise you to use training frameworks, including [Axolotl](https://github.com/OpenAccess-AI-Collective/axolotl), [Llama-Factory](https://github.com/hiyouga/LLaMA-Factory), [Swift](https://github.com/modelscope/swift), etc., to finetune your models with SFT, DPO, PPO, etc.

@jklj077 Thank you! Is there any quick start for that?

**Comment by jklj077** [comment]
ping @yangjianxin1. he is currently working on the quick start using llama-factory. 

for now, there is a very simple version at <https://qwen.readthedocs.io/en/latest/training/SFT/llama_factory.html>.

**Comment by chansonzhang** [comment]
@yangjianxin1 where can I found `src/train.py` mentioned in https://qwen.readthedocs.io/en/latest/training/SFT/llama_factory.html?
![image](https://github.com/user-attachments/assets/70612cd6-3d52-4c0b-9129-a8f4d90ce999)

**Comment by chansonzhang** [comment]
how should I set the param `--flash_attn`
![image](https://github.com/user-attachments/assets/1e378c36-b8df-442e-a024-f730f4cb38ea)

There is an error msg "**train.py: error: argument --flash_attn: expected one argument**"
