### ISSUE TITLE
单卡 vllm 部署的Qwen2-72B-Instruct-GPTQ-Int4  无法正常问答，出现乱码

### ISSUE THREAD

**Issue by sycamore792** [QwenLM/Qwen2#833]
这是我的环境信息

![image](https://github.com/user-attachments/assets/de012974-108b-46fd-bc6c-1457572e83f5)

![image](https://github.com/user-attachments/assets/47ab96cc-bbdb-4368-a11d-8653888d246f)

运行结果：
![image](https://github.com/user-attachments/assets/721dc15a-6887-4740-9d4f-958bf1d44f9a)

**Comment by jklj077** [comment]
likely driver or cuda mismatch. can you run the [collect_env.py](https://github.com/vllm-project/vllm/blob/main/collect_env.py) code from vllm and provide the result?
