### ISSUE TITLE
How does DCA integrate with Yarn?

### ISSUE THREAD

**Issue by cizhenshi** [QwenLM/Qwen2#837]
In the technical report of Qwen2, "To expand the context window of Qwen2, we implement Dual Chunk Attention (DCA, An et al., 2024), which segments long sequences into chunks of manageable lengths." How does DCA integrate with Yarn? I only found Yarn-related configurations in the configuration file. Where can I find content related to DCA?

**Comment by KKCDD** [comment]
Also confused here, DCA looks like a training free method for inference, how does DCA used in the long-context pretraining phase?

I didn't find any clue from both hugging face and pai-megatron-patch.

**Comment by hzhwcmhf** [comment]
@cizhenshi https://github.com/vllm-project/vllm/pull/6139 Here is a PR implementing DCA in vLLM, and you can find an example. 
Integrating YARN with DCA just scales ``query \dot key`` by a scalar ``mscale``, as implemented in the original repo of DCA: https://github.com/HKUNLP/ChunkLlama/blob/8a28f1464b2a5def03eb07e8d91f5bf4d00f667d/chunkllama_attn_replace.py#L39-L67

@KKCDD Your understanding is correct. DCA is not required in pre-training and only works in the inference stage.

**Comment by cizhenshi** [comment]
> @cizhenshi [vllm-project/vllm#6139](https://github.com/vllm-project/vllm/pull/6139) Here is a PR implementing DCA in vLLM, and you can find an example. Integrating YARN with DCA just scales `query \dot key` by a scalar `mscale`, as implemented in the original repo of DCA: https://github.com/HKUNLP/ChunkLlama/blob/8a28f1464b2a5def03eb07e8d91f5bf4d00f667d/chunkllama_attn_replace.py#L39-L67
> 
> @KKCDD Your understanding is correct. DCA is not required in pre-training and only works in the inference stage.

For the scenario of expanding from 32k to 128k, what is the recommended configuration?

I understand there are two options:

1.For DCA, according to the description in the paper, set the chunk size to 3/4 of 32k, i.e., 24k. However, with this setting, in most cases, the position ids will not exceed 32k. How will YARN function in this situation?

2. Treat the context expanded by YARN as the model's context. For example, if the YARN scale is set to 2, treat the model as 64k, and set the trunk size to 96k.

Could you provide some insights? Thanks!

**Comment by hzhwcmhf** [comment]
@cizhenshi We encourage using the first option. You can set ``chunk_size`` to 24k or 32k, and ``max_original_position_embedding`` to 32k.
We find it could lead to better performance by making the position ids not exceed the pre-training length, and setting ``original_max_position_embedding`` for yarn scaling also to the pre-training length.

**Comment by cizhenshi** [comment]
I will try it! Thank you very much!

**Comment by secain** [comment]
> @cizhenshi We encourage using the first option. You can set `chunk_size` to 24k or 32k, and `max_original_position_embedding` to 32k. We find it could lead to better performance by making the position ids not exceed the pre-training length, and setting `original_max_position_embedding` for yarn scaling also to the pre-training length.

why the latest model qwen2-72B's max_position_embedding is 130K?

**Comment by hzhwcmhf** [comment]
@secain Both Qwen2 base and instruction models are trained with 32k context length. For base models, direct length extrapolation from 32k to 128k will not lead to significant degradation in PPL evaluation, so the max_position_embedding is set to 128k. For instruction models, you should incorporate YARN or DCA for better long-context performance, as described in model card (https://huggingface.co/Qwen/Qwen2-72B-Instruct).
