### ISSUE TITLE
Qwen2 models malfunction with vLLM FP8 Cache, but Qwen1.5 models are fine

### ISSUE THREAD

**Issue by Jeremy-Hibiki** [QwenLM/Qwen2#840]
We originally deployed a Qwen1.5 14B model using vLLM and enabled FP8 KV Cache to reduce VRAM usage. 

Recently, we are testing the new Qwen2 series and find they don't work as expected. After several words, the output starts repeating and becomes totally nonsense. The penalty param doesn't work either.

Finally it turns out the issue is 'FP8 Cache'. Once i changed it to 'auto', everything works fine.

- [x] I've tested Qwen2 7B models with FP16, AWQ, 2 GPTQ, and 3rd party FP8 weights, and also 1.5B and 0.5B ones. 
- [x] I've double-checked the wieght files' hash with huggingface repo.
- [x] I've tried different vLLM version from 0.5.0, 0.5.2, 0.5.3.post1, to the latest 0.5.4, and even 0.4.2
- [x] I've also tried different envrioment with NV Driver 545, 555, 560, CUDA 12.1 12.4, RTX 4070 Ti Super, RTX 4090 and L40S.

Yeah we probably dont need FP8 cache since all qwen2 models are using GQA heads, but it is really weired. 

I don't know whether it is an upstream issue or a Qwen related issue because the same starting args can work with other models like mistral, glm4, and even Qwen1.5.

Some examples:

w/o fp8 cache:

```bash
$ typer vllm-offline-demo.py run summary --no-fp8-cache --lang zh --model-name /data/GPT/models/Qwen2-7B-Instruct-GPTQ-Int4
```

> 这段文本描述了一种自偏置缓冲器电路及其在存储器设备中的应用。自偏置缓冲器电路包括缓冲单元和偏置调整单元。缓冲单元基于参考电压提供自偏置电压，根据该自偏置电压驱动，并比较输入信号与参考电压以生成输出信号。偏置调整单元根据参考电压提升自偏置电压。
>
> 具体来说，偏置调整单元可以包括响应于参考电压开启的增强型晶体管，用于提升自偏置电压。偏置调整单元可以进一步包括在电源使能信号的反转信号下控制其操作的功率 MOS 晶体管和/或接地 MOS 晶体管，以确保在电源电压和接地电压之间稳定地提供自偏置电压。
>
> 缓冲单元可以包括差分单元，用于基于参考信号和输入信号生成自偏置电压和输出信号，以及偏置单元，用于根据自偏置电压驱动差分单元。差分单元可以包括参考单元和输入/输出单元，其中参考单元提供自偏置电压，输入/输出单元生成输出信号。
>
> 偏置调整单元可以包括功率单元和接地单元，用于在参考电压高于或等于启动电压时提升自偏置电压。当参考电压低于或等于启动电压时，偏置调整单元可以对自偏置电压进行对称调整。
>
> 存储器设备包括存储核心、自偏置缓冲器电路和控制单元。存储核心存储或输出数据，自偏置缓冲器电路接收存储核心的数据或向存储核心传输外部数据，响应于控制信号。控制单元生成控制信号以控制存储核心和自偏置缓冲器电路。
>
> 自偏置缓冲器电路可以用于提高存储器设备的运行速度和可靠性，通过使用适合操作特性的自偏置电压来增加操作速度和可靠性。通过调整自偏置电压，可以确保自偏置缓冲器电路在参考电压为 VDD/2 时对称工作，从而选择最宽的数据获取窗口的参考电压 VDD/2 作为自偏置电压的参考电压，以提高存储器设备的运行速度。
>
> 此外，自偏置缓冲器电路可以应用于各种数字系统，其中使用存储器设备以提高系统的运行速度。

w/ fp8 cache:

```bash
$ typer vllm-offline-demo.py run summary --fp8-cache --lang zh --model-name /data/GPT/models/Qwen2-7B-Instruct-GPTQ-Int4
```

> 这段描述描述描述一种自偏偏置缓冲器缓冲器电路电路，并 to improve 一种自偏偏的置缓冲的的电路。该。，该一种自偏偏偏的的当缓冲的的。.。该一种自偏偏偏偏偏的的缓冲缓冲的的。....一种自偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏偏

Repo of the reproduction demo: https://github.com/Jeremy-Hibiki/qwen2-vllm-repro

**Comment by jklj077** [comment]
> Yeah we probably dont need FP8 cache since all qwen2 models are using GQA heads

this is quite the solution (and possibly the reason). 

the intermediate activations of the 7B models (or the smaller ones, sometimes) do not play well with dtypes with limited exponents such as fp16 or fp8 (e5m2). repeating characters often indicates that overflows have happened in the process (e.g., a hidden state full of infs before softmax), and the general recommendation is to use bf16 or specialized attention kernels that conduct upcasting, which is not viable for KV Cache quantization.

there is also an interesting discussion on this issue at <https://www.github.com/turboderp/exllamav2/issues/493>. I think it is worthing reading.

**Comment by Jeremy-Hibiki** [comment]
Got it. Thanks for explanation.
