### ISSUE TITLE
微调qwen2使用 --lr_scheduler_type "cosine" 但是无效，学习率的变化并不是按照cosine的形态进行的

### ISSUE THREAD

**Issue by TAOSHss** [QwenLM/Qwen2#846]
使用的微调代码为Qwen2/examples/sft/finetune.sh除去修改了数据来源，其余的都没有进行修改，能解答一下吗
![Uploading CEFEF966-9385-435B-885C-8CC82C947D4A.png…]()

**Comment by jklj077** [comment]
see this: https://github.com/QwenLM/Qwen2/issues/577

in addition, we advise you to use training frameworks, including [Axolotl](https://github.com/OpenAccess-AI-Collective/axolotl), [Llama-Factory](https://github.com/hiyouga/LLaMA-Factory), [Swift](https://github.com/modelscope/swift), etc., to finetune your models with SFT, DPO, PPO, etc.
