### ISSUE TITLE
Qwen2 7B具备Function Calling能力吗？

### ISSUE THREAD

**Issue by dengxiang1995** [QwenLM/Qwen2#847]
Qwen2 7B具备Function Calling能力吗？如果想做电力领域的工具调用，是直接使用Qwen Agent进行工具调用，还是需要进一步微调才能识别出电力领域的工具

**Comment by jklj077** [comment]
Hi, Qwen2-7B-Instruct should support tool use/function calling. Following the instructions in Qwen-Agent, you should be able to use tools even if they are new to the model.

**Comment by phamnhuvu-dev** [comment]
Hi @jklj077, can I use Qwen2's `function calling` with langchain instead of Qwen-Agent?

**Comment by joelhy** [comment]
@jklj077 with Ollama support tool calling: https://ollama.com/blog/tool-support
When will Quanwen2 support tool calling directly?

**Comment by jklj077** [comment]
In general, please refer to <https://github.com/QwenLM/Qwen-Agent/issues/216#issuecomment-2264539369>

For ollama specifically, please also see <https://github.com/ollama/ollama/issues/6007>.

**Comment by dengxiang1995** [comment]
> 你好，Qwen2-7B-Instruct 应该支持工具使用/函数调用。按照 Qwen-Agent 中的说明，你应该能够使用工具，即使它们是模型中的新工具。但是，准确性可能会有所不同。建议您先尝试不进行微调，如果性能需要改进，再进行进一步的微调。

你好，具体的微调方法有官方教程吗

**Comment by dengxiang1995** [comment]
> 你好，Qwen2-7B-Instruct 应该支持工具使用/函数调用。按照 Qwen-Agent 中的说明，你应该能够使用工具，即使它们是模型中的新工具。但是，准确性可能会有所不同。建议您先尝试不进行微调，如果性能需要改进，再进行进一步的微调。

你好，具体的微调方法有教程吗
