### ISSUE TITLE
想确定一个SFT的一个细节

### ISSUE THREAD

**Issue by xiaomao19970819** [QwenLM/Qwen2#853]
若使用官方给定的transformers的trainner进行训练，在计算ce loss时，prompt对应的token的loss没有被mask掉，我的理解是对的吗？
<img width="802" alt="KIM20240815-913516" src="https://github.com/user-attachments/assets/81e5a2a2-367e-4805-8032-b0e554f92d46">

**Comment by jklj077** [comment]
This has been raised mutiple times in the issues; please refer to those issues first.

We advise you to use training frameworks, including [Axolotl](https://github.com/OpenAccess-AI-Collective/axolotl), [Llama-Factory](https://github.com/hiyouga/LLaMA-Factory), [Swift](https://github.com/modelscope/swift), etc., to finetune your models with SFT, DPO, PPO, etc.
