### ISSUE TITLE
【bug】token分词问题，湖北，或其他中文的前方加入空格会导致乱码。

### ISSUE THREAD

**Issue by DoiiarX** [QwenLM/Qwen2#864]
【bug】token分词问题，湖北，或其他中文的前方加入空格会导致乱码。

![image](https://github.com/user-attachments/assets/f57259bc-d3df-4a6c-afaf-a776d3fd0cd6)

回复也会乱码

**Comment by jklj077** [comment]
Hi, I would advise you to look up learning materials on byte-level BPE first. If you don't know how to use the tokenizer, you can take a look at its [API](https://huggingface.co/docs/transformers/main_classes/tokenizer).

```
In [1]: from transformers import AutoTokenizer

In [2]: tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2-7B-Instruct")

In [3]: tokenizer.decode([6567, 117, 244, 48309])
Out[3]: ' 湖北'
```

**Comment by DoiiarX** [comment]
> Hi, I would advise you to look up learning materials on byte-level BPE first. If you don't know how to use the tokenizer, you can take a look at its [API](https://huggingface.co/docs/transformers/main_classes/tokenizer).
> 
> ```
> In [1]: from transformers import AutoTokenizer
> 
> In [2]: tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2-7B-Instruct")
> 
> In [3]: tokenizer.decode([6567, 117, 244, 48309])
> Out[3]: ' 湖北'
> ```

我检查后发现，实际上的问题是，qwen的流式传输接口在返回结果时，不会预先判断字节是否完整。会出现utf-8单字字节分多次返回的情况。这时候如果解码会出现异常字符。我在自己的代码中做了处理，我希望qwen在本身流式返回上处理这些问题。我使用的qwen-plus模型。

这是我的解决方案。
```python
responses = Generation.call(
        model="qwen-plus-0806",
        messages=messages,
        api_key=api_key,
        seed=random.randint(1, 10000),
        result_format='message',
        stream=True,
        incremental_output=True,
        temperature=0.5,
        top_k=20,
        top_p=0.9,
    )

    full_content = ''
    response = None
    buffer = io.BytesIO()

    def flush_buffer():
        buffer_content = buffer.getvalue().decode('utf-8', errors='ignore')
        print(buffer_content, end='', flush=True)
        return buffer_content

    for response in responses:
        if response.status_code == HTTPStatus.OK:
            chunk_content = response.output.choices[0]['message']['content']
            chunk_bytes = chunk_content.encode('utf-8')

            for byte in chunk_bytes:
                buffer.write(bytes([byte]))

                # 检查是否有完整的UTF-8字符
                try:
                    buffer.getvalue().decode('utf-8')
                    full_content += flush_buffer()
                    buffer = io.BytesIO()
                except UnicodeDecodeError:
                    # 如果解码失败，继续累积字节
                    pass
```

**Comment by jklj077** [comment]
Hi, this the repo for the open-weight Qwen models and the open-source ecosystem (transformers, vllm, ...).
For issues regarding the commercial service, e.g., the proprietary models, DashScope API, ModelStudio, please directly contact customer service from Alibaba Cloud.

**Comment by jklj077** [comment]
Update: DashScope states that the issue has been fixed last Friday.
