### ISSUE TITLE
请问一下qwen2-gptq的量化做了哪些具体的量化，只优化权重weight？

### ISSUE THREAD

**Issue by xiangxinhello** [QwenLM/Qwen2#865]

**Comment by jklj077** [comment]
Hi, 

The gptq checkpoints are quantized using the GPTQ algorithm using the `auto_gptq` package. As described in [the original paper](https://arxiv.org/abs/2210.17323), GPTQ is a post-training quantization (PTQ) and weight quantization method. It does not "optimize" the weights as in quantization-aware training (QAT).
The parameters which are quantized can be found in the `auto_gptq` source code [here](https://github.com/AutoGPTQ/AutoGPTQ/blob/097dd04e2fd02bc6664908cd91b7ef8c6302a332/auto_gptq/modeling/qwen2.py#L8-L13).
