### ISSUE TITLE
Qwen2/Qwen2-7B-Instruct 使用V100 FP16推理/训练出现大量的数值溢出(nan)问题

### ISSUE THREAD

**Issue by wykk00** [QwenLM/Qwen2#868]
``` Python
# 导入模型格式
model = transformers.AutoModelForCausalLM.from_pretrained(MODEL_ID, device_map='auto', torch_dtype=torch.float16, trust_remote_code=True)
```

CUDA Version: 11.4
```shell
transformers==4.43.4
torch==2.0.1
```

**Comment by jklj077** [comment]
As the original model was trained using bfloat16, changing to float16 may cause numerical instabilities, which is expected. Please search the issue area first for previous responses:
- https://github.com/QwenLM/Qwen2/issues/721
- https://github.com/QwenLM/Qwen2/issues/722
- https://github.com/QwenLM/Qwen2/issues/761

For this model to run in fp16, you need CUDA fused kernels with fp32 accumulate
- for newer cards, upgrading nvidia drivers, pytorch, and transformers to latest will cut it
- for older cards, consider using [this patch](https://github.com/jklj077/transformers/tree/qwen2-patch)
