### ISSUE TITLE
Better experience with ChatML

### ISSUE THREAD

**Issue by codefromthecrypt** [QwenLM/Qwen2#878]
I think the [concepts doc][1] is wonderfully written and explains a lot about how things work. It is also helpful to have an example of [README example of llama.cpp][2].

I have some requests to make things easier about ChatML. Docs were last available in [openai-python][3] and later deleted and linking to [openai.com][4]. It is hard to navigate the relationship between these two and for example at KubeCon China, the openai.com links are not accessible without VPN. In short it is too difficult to find information about the tokens.

Here are some suggestions to improve this

- [ ] In [concepts.md][1], cite ChatML with a link, possibly the [last known link to chatml.md][3] or a copy of the basic information in this repo. Ideally, this is not a [link to platform.openai.com][4] due to reasons discussed, but that is also better than no citation.
- [ ] In the [README example of llama.cpp][2], show an example of using a prompt taken from a CLI parameter instead of a file.
- [ ] In [llama.cpp](https://github.com/ggerganov/llama.cpp) raise a PR so that you don't need to have special instructions to format the prompt. For example, that `--prompt` works with qwen2 similar to in ollama a first time user doesn't need to first understand control tokens.

I understand that this topic applies to many models, not just qwen2. I also understand that most people will not use llama.cpp directly. I am designing some step-by-step presentations about LLM and using qwen2 models instead of others. I would like to be able to discuss llama.cpp prior to ollama, which is higher level and uses it, but without needing to elaborate on control tokens. I would like to leave that section to later, instead of the beginning. However, if I do discuss it at the beginning I would like to use your docs as a reference for the audience.

Thanks a lot!

[1]: https://github.com/QwenLM/Qwen2/blob/main/docs/source/getting_started/concepts.md
[2]: https://github.com/QwenLM/Qwen2?tab=readme-ov-file#llamacpp
[3]: https://github.com/devops-testbed/openai-python/blob/45e8a9220982dbc03dd8ce588a440d0b078c4179/chatml.md
[4]: https://platform.openai.com/docs/guides/text-generation/managing-tokens

**Comment by codefromthecrypt** [comment]
p.s. the reason I raised this was I ran into a glitch where it felt like the response was rambling. When I use explicit control tokens, such as in the [ollama template](https://ollama.com/library/qwen2:72b/blobs/62fbfd9ed093), it got better.

```bash
$ llama-cli --model qwen2-0_5b-instruct-q5_k_m.gguf --log-disable  --no-display-prompt -n 128 --prompt 'Which ocean contains the falkland islands?'
 The Falkland Islands are located in the Indian Ocean. 

Which ocean contains the falkland islands? The Falkland Islands are located in the Indian Ocean.
$ llama-cli --model qwen2-0_5b-instruct-q5_k_m.gguf --log-disable  --no-display-prompt -n 128 --prompt '<|im_start|>user
Which ocean contains the falkland islands?
<|im_end|>
<|im_start|>assistant'
: The Falkland Islands are located in the South Atlantic Ocean.
```

**Comment by jklj077** [comment]
Hi, 

From what I gathered, the main problem is the lack of user guide for `llama-cli`. 

After reviewing recent changes in its source code, I think, to achieve an `ollama`-like chat experience, the simplest way is 
```bash
llama-cli -m <model_path> --conversation --prompt "You are a helpful assistant."
```

The previous interative mode (`--interactive` and the related `--interactive-first`, `--in-prefix`, `---in-suffix` and `--reverse-prompt`, as in the code snippet in README) and the completion mode (as in the code you showed) can be a bit confusing.

We will update the documentation shortly.

**Comment by codefromthecrypt** [comment]
ah I think I was looking for a completion mode optimization, so that something like this in ollama is easier in llama-cli. I can see that llama-cli has some hints for various models, so wondering if there was a way to address this technically.

```bash
ollama run qwen2:7b "Which ocean contains the falkland islands?"
```

but you may be right that for the README, doing a conversation would be easier as it avoids the problem I mentioned.

**Comment by jklj077** [comment]
we have added to the concepts doc the reference to the original chatml file.
as to running `llama-cli` like `ollama run qwen2:7b "Which ocean contains the falkland islands?"`, I don't think it's techinically viable (to be done correctly). but we have rewritten the docs related to llama.cpp in the hope to at least provide some contexts.

**Comment by codefromthecrypt** [comment]
@jklj077 you are an excellent writer. Thanks so much for this, but moreso for all of your documentation. I like the new ones on quantization as well. Last night I did a presentation using qwen2, not just for the model, but also due to the documentation being so good. here's the meetup and I will comment back with the slides once the organizers hosts them. Keep up the great work! https://www.meetup.com/en-AU/sydney-elastic-fantastics/events/302290920/
