### ISSUE TITLE
vllm inference Qwen2-72B-Instruct-GPTQ-Int4 Occasionally garbled characters appear ����

### ISSUE THREAD

**Issue by zhanaali** [QwenLM/Qwen2#881]

**Comment by zhanaali** [comment]
vllm: 0.5.0.post1

**Comment by jklj077** [comment]
hi, could you share the prompts and the steps that could help us to reproduce?

**Comment by zhanaali** [comment]
[package.txt](https://github.com/user-attachments/files/16757140/package.txt)
[code.txt](https://github.com/user-attachments/files/16757150/code.txt)
