### ISSUE TITLE
[transformers+sdpa] 推理时遇到flash-attn报错

### ISSUE THREAD

**Issue by YcHades** [QwenLM/Qwen2#892]
```
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 37/37 [00:14<00:00,  2.61it/s]
WARNING:root:Some parameters are on the meta device device because they were offloaded to the cpu.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token.As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Traceback (most recent call last):
  File "/raid/workspace_dgx/yc_dgx/composition-reason/Model/qwen2_test.py", line 23, in <module>
    generated_ids = model.generate(
                    ^^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/transformers/generation/utils.py", line 1989, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/transformers/generation/utils.py", line 2932, in _sample
    outputs = self(**model_inputs, return_dict=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1054, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 856, in forward
    layer_outputs = decoder_layer(
                    ^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 596, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
                                                          ^^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dgx/miniconda3/envs/yc_rs_perception/lib/python3.12/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 521, in forward
    attn_output = torch.nn.functional.scaled_dot_product_attention(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: FlashAttention only supports Ampere GPUs or newer.
```

当我运行hugging face上的quick start示例代码时遇到以上错误，我使用的是A800，似乎是支持flash-attn的。更关键的问题在于实际上官方示例代码好像也并没有使用flash-attn，因此这个报错让我很疑惑。
我的transformers版本是4.44.2

**Comment by jklj077** [comment]
For relations among `transformers`, `torch`, and `flash-attn`, please first refer to [our guide](https://qwen.readthedocs.io/zh-cn/latest/inference/chat.html#id1).

Your error seems odd, because `torch` normally will not select that backend at the first place if the device does not support it. Please provide the results of `pip list` and `nvidia-smi`.

**Comment by YcHades** [comment]
> For relations among `transformers`, `torch`, and `flash-attn`, please first refer to [our guide](https://qwen.readthedocs.io/zh-cn/latest/inference/chat.html#fa2).
> 
> Your error seems odd, because `torch` normally will not select that backend at the first place if the device does not support it. Please provide the results of `pip list` and `nvidia-smi`.

Thanks for your reply. 

More INFO
pip list:
`Package                  Version
------------------------ -----------
accelerate               0.31.0
aiohttp                  3.9.5
aiosignal                1.3.1
annotated-types          0.7.0
anyio                    4.4.0
asttokens                2.4.1
attrs                    23.2.0
bitsandbytes             0.43.1
Brotli                   1.0.9
certifi                  2024.6.2
charset-normalizer       2.0.4
comm                     0.2.2
contourpy                1.2.1
cycler                   0.12.1
dashscope                1.19.3
debugpy                  1.8.1
decorator                5.1.1
distro                   1.9.0
einops                   0.8.0
exceptiongroup           1.2.0
executing                2.0.1
filelock                 3.13.1
flash-attn               2.5.9.post1
fonttools                4.53.0
frozenlist               1.4.1
fsspec                   2024.6.0
gmpy2                    2.1.2
greenlet                 3.0.3
h11                      0.14.0
httpcore                 1.0.5
httpx                    0.27.0
huggingface-hub          0.23.4
idna                     3.7
importlib_metadata       7.1.0
ipykernel                6.29.4
ipython                  8.25.0
jedi                     0.19.1
Jinja2                   3.1.4
jsonpatch                1.33
jsonpointer              3.0.0
jupyter_client           8.6.2
jupyter_core             5.7.2
kiwisolver               1.4.5
langchain                0.2.5
langchain-core           0.2.7
langchain-openai         0.1.8
langchain-text-splitters 0.2.1
langsmith                0.1.77
MarkupSafe               2.1.3
matplotlib               3.9.0
matplotlib-inline        0.1.7
mkl-fft                  1.3.8
mkl-random               1.2.4
mkl-service              2.4.0
mpmath                   1.3.0
multidict                6.0.5
nest_asyncio             1.6.0
networkx                 3.2.1
ninja                    1.11.1.1
numpy                    1.26.4
openai                   1.34.0
orjson                   3.10.5
packaging                24.1
parso                    0.8.4
peft                     0.11.1
pexpect                  4.9.0
pickleshare              0.7.5
pillow                   10.3.0
pip                      24.0
platformdirs             4.2.2
prompt_toolkit           3.0.47
psutil                   5.9.8
ptyprocess               0.7.0
pure-eval                0.2.2
pydantic                 2.7.4
pydantic_core            2.18.4
Pygments                 2.18.0
pyparsing                3.1.2
PySocks                  1.7.1
python-dateutil          2.9.0.post0
PyYAML                   6.0.1
pyzmq                    26.0.3
regex                    2024.5.15
requests                 2.32.2
safetensors              0.4.3
sentencepiece            0.2.0
setuptools               70.0.0
six                      1.16.0
sniffio                  1.3.1
SQLAlchemy               2.0.30
stack-data               0.6.2
sympy                    1.12
tenacity                 8.3.0
tiktoken                 0.7.0
timm                     1.0.3
tokenizers               0.19.1
torch                    2.3.1
torchaudio               2.3.1
torchvision              0.18.1
tornado                  6.4.1
tqdm                     4.66.4
traitlets                5.14.3
transformers             4.44.2
triton                   2.3.1
typing_extensions        4.12.2
urllib3                  2.2.1
wcwidth                  0.2.13
wheel                    0.43.0
yarl                     1.9.4
zipp                     3.19.2`

nvidia-smi:
`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.105.01   Driver Version: 515.105.01   CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A800-SXM...  Off  | 00000000:01:00.0 Off |                    0 |
| N/A   34C    P0    56W / 275W |      9MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A800-SXM...  Off  | 00000000:47:00.0 Off |                    0 |
| N/A   34C    P0    58W / 275W |      9MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A800-SXM...  Off  | 00000000:81:00.0 Off |                    0 |
| N/A   33C    P0    59W / 275W |      9MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA DGX Display  Off  | 00000000:C1:00.0 Off |                  N/A |
| 33%   34C    P8    N/A /  50W |    180MiB /  4096MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA A800-SXM...  Off  | 00000000:C2:00.0 Off |                    0 |
| N/A   33C    P0    59W / 275W |      9MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3297      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A      5833      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A      3297      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A      5833      G   /usr/lib/xorg/Xorg                  4MiB |
|    2   N/A  N/A      3297      G   /usr/lib/xorg/Xorg                  4MiB |
|    2   N/A  N/A      5833      G   /usr/lib/xorg/Xorg                  4MiB |
|    3   N/A  N/A      3297      G   /usr/lib/xorg/Xorg                 39MiB |
|    3   N/A  N/A      5833      G   /usr/lib/xorg/Xorg                 78MiB |
|    3   N/A  N/A      5957      G   /usr/bin/gnome-shell               52MiB |
|    4   N/A  N/A      3297      G   /usr/lib/xorg/Xorg                  4MiB |
|    4   N/A  N/A      5833      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+`

**Comment by jklj077** [comment]
NVIDIA driver appears a bit out-dated; please consider upgrading to at least R535: https://docs.nvidia.com/datacenter/tesla/tesla-release-notes-535-183-06/index.html

After upgrading the driver, please also install `torch` with a CUDA version supported by the driver: 535 is 12.1; 550/560 is 12.4.

**Comment by YcHades** [comment]
I'm sorry, but the issue still persists. I have already updated the driver to version 560 and also updated CUDA and PyTorch. Below is the current information about my environment.

![image](https://github.com/user-attachments/assets/6b61bddd-32d0-43fc-afc6-df36a093b9f8)
![image](https://github.com/user-attachments/assets/47a1b9ac-f09c-4d30-a990-a14b352ad443)

**Comment by jklj077** [comment]
Hi, based on the new screenshot, I wonder if you had place the model on the DGX Display GPU? The DGX A100 manual suggests that:

> The DGX Station A100 comes equipped with four high performance NVIDIA A100 GPUs and one DGX Display GPU. The NVIDIA A100 GPU is used to run high performance and AI workloads, and the DGX Display card is used to drive a high-quality display on a monitor.
> 
> When running applications on this system, it is important to identify the best method to launch applications and workloads to make sure the high performance NVIDIA A100 GPUs are used

(https://docs.nvidia.com/dgx/dgx-station-a100-user-guide/getting-started-station-a100.html)

I believe you can try `export CUDA_VISIBLE_DEVICES=0,1,2,4` before running your script.

**Comment by YcHades** [comment]
Thank you so much for your detailed responses, and I really appreciate your help. The issue has been resolved, and it turns out that the display GPU was indeed being used during inference. However, I didn't encounter this issue before when using distributed training with the accelerate library on other models. Could this be related to the new version of the transformers library?
Either way, I am truly grateful for your assistance!

**Comment by wedu-nvidia** [comment]
thanks. by export device that I can solve the exact same issue
