### ISSUE TITLE
vllm部署qwen2失效

### ISSUE THREAD

**Issue by RyanOvO** [QwenLM/Qwen2#895]
参考 [vllm部署](https://qwen.readthedocs.io/zh-cn/latest/deployment/vllm.html#openai-api-compatible-api-service)  发现不能调接口。

model: qwen2-7b-instruct
vllm: 0.5.1

![image](https://github.com/user-attachments/assets/52d8ee11-9c61-424f-9a8a-25059016f81c)
![image](https://github.com/user-attachments/assets/25d69d90-e20b-4df7-92ba-6d791467c41d)
![image](https://github.com/user-attachments/assets/008e47ac-a66f-40c6-9a49-b63f328056c0)

docs接口列表只有两个接口，是vllm版本不对么？

**Comment by jklj077** [comment]
it appearts you started a vllm api server (`python -m vllm.entrypoints.api_server`) not a vllm **openai** api server (`python -m vllm.entrypoints.openai.api_server`)

**Comment by RyanOvO** [comment]
好的，还真是遗漏了。
