### ISSUE TITLE
是否有计划支持和openai一样输入100%的json

### ISSUE THREAD

**Issue by lwdnxu** [QwenLM/Qwen2#901]
是否有计划支持和openai一样输入100%的json，如果有的话，是否可以告知大致的时间

**Comment by jklj077** [comment]
Hi, 

I think that you may have mixed two different abilities: 
- the ability of the model to generate JSON 
- the ability of the inference frameworks to force the generated texts to only contain valid JSON (with constraint decoding or guided decoding), the so-called "100%" JSON

The first has already been supported and the second depends on the inference framework you choose.
For Alibaba Cloud's Model Studio, you can enable it by setting [resposne_format](https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format) to the OpenAI-compatible API.
Open-source solutions such as vllm and sglang also support similar functionality.

**Comment by jklj077** [comment]
see also https://github.com/QwenLM/Qwen2/issues/797
