### ISSUE TITLE
这个钢印好象掰不过来了~~

### ISSUE THREAD

**Issue by gg22mm** [QwenLM/Qwen2#903]
这个钢印好象掰不过来了~~

![fe08d3c8ec65e818a007a0cb56c18d6](https://github.com/user-attachments/assets/2a818572-9384-4b0c-82b9-ed22eb835b20)

**Comment by jklj077** [comment]
![image](https://github.com/user-attachments/assets/a434f290-c3c1-48c4-af32-2fce5b45ece0)

![image](https://github.com/user-attachments/assets/8567a2a9-aafc-4e50-bc26-c243eee5866e)

**Comment by gg22mm** [comment]
厉害~~
