### ISSUE TITLE
千问2-7b智能体Agent模型-GGUF

### ISSUE THREAD

**Issue by Samsogo** [QwenLM/Qwen2#908]
该模型和普通的qwen2-7B-Instruct的模型有什么区别吗，是针对agent做的优化后的模型吗

**Comment by jklj077** [comment]
Hi, where is this model?

**Comment by Samsogo** [comment]
> Hi, where is this model? I don't think it is in our org: https://huggingface.co/Qwen

https://modelscope.cn/models/swift/qwen2-7b-agent-instruct-GGUF

**Comment by jklj077** [comment]
hi, this is maintained by swift and we don't know much about it. please refer to its readme or modelscope github or swift github for info.
