### ISSUE TITLE
关于奖励模型reward model

### ISSUE THREAD

**Issue by RyanOvO** [QwenLM/Qwen2#909]
如下图：
![image](https://github.com/user-attachments/assets/bda650bf-28fe-4018-bee9-c98d517123da)

在modelscope和huggingface上没有找到rw model，是没有放出来么？

**Comment by jklj077** [comment]
Hi, thank you for your interest in the reward models. I believe that you were referencing the Qwen technical report (which does not reflect the status of Qwen1.5/Qwen2) for the Qwen1.0 series (which we do not update anymore). Nonetheless, I don't think it is mentioned that the reward model will be released.

**Comment by RyanOvO** [comment]
> Hi, thank you for your interest in the reward models. I believe that you were referencing the Qwen technical report (which does not reflect the status of Qwen1.5/Qwen2) for the Qwen1.0 series (which we do not update anymore). Nonetheless, I don't think it is mentioned that the reward model will be released.

copy.
