### ISSUE TITLE
Qwen2-7B-Instruct (fp16) 在 LongBench/passage_retrieval_zh 数据集下采用 eager attention 计算时出现 nan/inf

### ISSUE THREAD

**Issue by condy0919** [QwenLM/Qwen2#910]
作为对比，如果使用 flash-attn2 或者 sdpa，则精度都没有太大问题，而使用 eager 则会产生许多 `!` token。我观察到在采用 eager attention 时, Q @ K^T 就会出现大值，它超出了 fp16 表示范围，于是变成了 inf/-inf. 后面经过 softmax 就变成了 nan 了。而 flash-attn2 和 sdpa 由于是融合算子，正好没这个问题。

附 LongBench/passage_retrieval_zh 测试结果，左侧为 eager, 右侧为 flash-attn2
![image](https://github.com/user-attachments/assets/58f6b57e-eb56-4ae7-a65d-9b3a437dbeab)

**Comment by jklj077** [comment]
Hi, please refer to the forth one at https://qwen.readthedocs.io/en/latest/inference/chat.html#troubleshooting

**Comment by condy0919** [comment]
非常感谢！
