### ISSUE TITLE
[QA] Number of training tokens

### ISSUE THREAD

**Issue by RicardoDominguez** [QwenLM/Qwen2#97]
Hi,

What is the number of training tokens for the base models Qwen 1.5 0.5B, 1.8B, 4B, 7B, 14B, 72B models?

Thanks for the great work!

**Comment by JustinLin610** [comment]
2.4, 2.4, 2.4, 4, 4, 3 trillion tokens

**Comment by RicardoDominguez** [comment]
Many thanks!

**Comment by guijinSON** [comment]
Thanks for the great work. can you also share how many tokens the 110B model was trained on?

**Comment by guijinSON** [comment]
and the 32 B model as well.

**Comment by RicardoDominguez** [comment]
Yes, it would be great to know the number of tokens of both the 110B and 32B
